/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import org.giwi.nifi.tester.model.RevisionDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ActivateControllerServicesEntity
 */
@JsonPropertyOrder({
  ActivateControllerServicesEntity.JSON_PROPERTY_COMPONENTS,
  ActivateControllerServicesEntity.JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED,
  ActivateControllerServicesEntity.JSON_PROPERTY_ID,
  ActivateControllerServicesEntity.JSON_PROPERTY_STATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ActivateControllerServicesEntity {
  public static final String JSON_PROPERTY_COMPONENTS = "components";
  @javax.annotation.Nullable
  private Map<String, RevisionDTO> components = new HashMap<>();

  public static final String JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED = "disconnectedNodeAcknowledged";
  @javax.annotation.Nullable
  private Boolean disconnectedNodeAcknowledged;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  /**
   * The desired state of the descendant components
   */
  public enum StateEnum {
    ENABLED(String.valueOf("ENABLED")),
    
    DISABLED(String.valueOf("DISABLED"));

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nullable
  private StateEnum state;

  public ActivateControllerServicesEntity() {
  }

  public ActivateControllerServicesEntity components(@javax.annotation.Nullable Map<String, RevisionDTO> components) {
    
    this.components = components;
    return this;
  }

  public ActivateControllerServicesEntity putComponentsItem(String key, RevisionDTO componentsItem) {
    if (this.components == null) {
      this.components = new HashMap<>();
    }
    this.components.put(key, componentsItem);
    return this;
  }

  /**
   * Optional services to schedule. If not specified, all authorized descendant controller services will be used.
   * @return components
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPONENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, RevisionDTO> getComponents() {
    return components;
  }


  @JsonProperty(JSON_PROPERTY_COMPONENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComponents(@javax.annotation.Nullable Map<String, RevisionDTO> components) {
    this.components = components;
  }

  public ActivateControllerServicesEntity disconnectedNodeAcknowledged(@javax.annotation.Nullable Boolean disconnectedNodeAcknowledged) {
    
    this.disconnectedNodeAcknowledged = disconnectedNodeAcknowledged;
    return this;
  }

  /**
   * Acknowledges that this node is disconnected to allow for mutable requests to proceed.
   * @return disconnectedNodeAcknowledged
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisconnectedNodeAcknowledged() {
    return disconnectedNodeAcknowledged;
  }


  @JsonProperty(JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisconnectedNodeAcknowledged(@javax.annotation.Nullable Boolean disconnectedNodeAcknowledged) {
    this.disconnectedNodeAcknowledged = disconnectedNodeAcknowledged;
  }

  public ActivateControllerServicesEntity id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * The id of the ProcessGroup
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public ActivateControllerServicesEntity state(@javax.annotation.Nullable StateEnum state) {
    
    this.state = state;
    return this;
  }

  /**
   * The desired state of the descendant components
   * @return state
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StateEnum getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@javax.annotation.Nullable StateEnum state) {
    this.state = state;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivateControllerServicesEntity activateControllerServicesEntity = (ActivateControllerServicesEntity) o;
    return Objects.equals(this.components, activateControllerServicesEntity.components) &&
        Objects.equals(this.disconnectedNodeAcknowledged, activateControllerServicesEntity.disconnectedNodeAcknowledged) &&
        Objects.equals(this.id, activateControllerServicesEntity.id) &&
        Objects.equals(this.state, activateControllerServicesEntity.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(components, disconnectedNodeAcknowledged, id, state);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivateControllerServicesEntity {\n");
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("    disconnectedNodeAcknowledged: ").append(toIndentedString(disconnectedNodeAcknowledged)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

