/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.giwi.nifi.tester.model.AuthenticationConfigurationDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AuthenticationConfigurationEntity
 */
@JsonPropertyOrder({
  AuthenticationConfigurationEntity.JSON_PROPERTY_AUTHENTICATION_CONFIGURATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class AuthenticationConfigurationEntity {
  public static final String JSON_PROPERTY_AUTHENTICATION_CONFIGURATION = "authenticationConfiguration";
  @javax.annotation.Nullable
  private AuthenticationConfigurationDTO authenticationConfiguration;

  public AuthenticationConfigurationEntity() {
  }

  public AuthenticationConfigurationEntity authenticationConfiguration(@javax.annotation.Nullable AuthenticationConfigurationDTO authenticationConfiguration) {
    
    this.authenticationConfiguration = authenticationConfiguration;
    return this;
  }

  /**
   * Get authenticationConfiguration
   * @return authenticationConfiguration
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTHENTICATION_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuthenticationConfigurationDTO getAuthenticationConfiguration() {
    return authenticationConfiguration;
  }


  @JsonProperty(JSON_PROPERTY_AUTHENTICATION_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthenticationConfiguration(@javax.annotation.Nullable AuthenticationConfigurationDTO authenticationConfiguration) {
    this.authenticationConfiguration = authenticationConfiguration;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticationConfigurationEntity authenticationConfigurationEntity = (AuthenticationConfigurationEntity) o;
    return Objects.equals(this.authenticationConfiguration, authenticationConfigurationEntity.authenticationConfiguration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authenticationConfiguration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticationConfigurationEntity {\n");
    sb.append("    authenticationConfiguration: ").append(toIndentedString(authenticationConfiguration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

