/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.giwi.nifi.tester.model.NodeSearchResultDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ClusterSearchResultsEntity
 */
@JsonPropertyOrder({
  ClusterSearchResultsEntity.JSON_PROPERTY_NODE_RESULTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ClusterSearchResultsEntity {
  public static final String JSON_PROPERTY_NODE_RESULTS = "nodeResults";
  @javax.annotation.Nullable
  private List<NodeSearchResultDTO> nodeResults = new ArrayList<>();

  public ClusterSearchResultsEntity() {
  }

  public ClusterSearchResultsEntity nodeResults(@javax.annotation.Nullable List<NodeSearchResultDTO> nodeResults) {
    
    this.nodeResults = nodeResults;
    return this;
  }

  public ClusterSearchResultsEntity addNodeResultsItem(NodeSearchResultDTO nodeResultsItem) {
    if (this.nodeResults == null) {
      this.nodeResults = new ArrayList<>();
    }
    this.nodeResults.add(nodeResultsItem);
    return this;
  }

  /**
   * Get nodeResults
   * @return nodeResults
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NODE_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NodeSearchResultDTO> getNodeResults() {
    return nodeResults;
  }


  @JsonProperty(JSON_PROPERTY_NODE_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNodeResults(@javax.annotation.Nullable List<NodeSearchResultDTO> nodeResults) {
    this.nodeResults = nodeResults;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterSearchResultsEntity clusterSearchResultsEntity = (ClusterSearchResultsEntity) o;
    return Objects.equals(this.nodeResults, clusterSearchResultsEntity.nodeResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nodeResults);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterSearchResultsEntity {\n");
    sb.append("    nodeResults: ").append(toIndentedString(nodeResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

