/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ComponentValidationResultDTO
 */
@JsonPropertyOrder({
  ComponentValidationResultDTO.JSON_PROPERTY_ACTIVE_THREAD_COUNT,
  ComponentValidationResultDTO.JSON_PROPERTY_CURRENTLY_VALID,
  ComponentValidationResultDTO.JSON_PROPERTY_ID,
  ComponentValidationResultDTO.JSON_PROPERTY_NAME,
  ComponentValidationResultDTO.JSON_PROPERTY_PROCESS_GROUP_ID,
  ComponentValidationResultDTO.JSON_PROPERTY_REFERENCE_TYPE,
  ComponentValidationResultDTO.JSON_PROPERTY_RESULTANT_VALIDATION_ERRORS,
  ComponentValidationResultDTO.JSON_PROPERTY_RESULTS_VALID,
  ComponentValidationResultDTO.JSON_PROPERTY_STATE,
  ComponentValidationResultDTO.JSON_PROPERTY_VALIDATION_ERRORS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ComponentValidationResultDTO {
  public static final String JSON_PROPERTY_ACTIVE_THREAD_COUNT = "activeThreadCount";
  @javax.annotation.Nullable
  private Integer activeThreadCount;

  public static final String JSON_PROPERTY_CURRENTLY_VALID = "currentlyValid";
  @javax.annotation.Nullable
  private Boolean currentlyValid;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_PROCESS_GROUP_ID = "processGroupId";
  @javax.annotation.Nullable
  private String processGroupId;

  /**
   * The type of this component
   */
  public enum ReferenceTypeEnum {
    PROCESSOR(String.valueOf("PROCESSOR")),
    
    CONTROLLER_SERVICE(String.valueOf("CONTROLLER_SERVICE")),
    
    INPUT_PORT(String.valueOf("INPUT_PORT")),
    
    OUTPUT_PORT(String.valueOf("OUTPUT_PORT")),
    
    REMOTE_INPUT_PORT(String.valueOf("REMOTE_INPUT_PORT")),
    
    REMOTE_OUTPUT_PORT(String.valueOf("REMOTE_OUTPUT_PORT")),
    
    STATELESS_GROUP(String.valueOf("STATELESS_GROUP"));

    private String value;

    ReferenceTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ReferenceTypeEnum fromValue(String value) {
      for (ReferenceTypeEnum b : ReferenceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_REFERENCE_TYPE = "referenceType";
  @javax.annotation.Nullable
  private ReferenceTypeEnum referenceType;

  public static final String JSON_PROPERTY_RESULTANT_VALIDATION_ERRORS = "resultantValidationErrors";
  @javax.annotation.Nullable
  private List<String> resultantValidationErrors = new ArrayList<>();

  public static final String JSON_PROPERTY_RESULTS_VALID = "resultsValid";
  @javax.annotation.Nullable
  private Boolean resultsValid;

  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nullable
  private String state;

  public static final String JSON_PROPERTY_VALIDATION_ERRORS = "validationErrors";
  @javax.annotation.Nullable
  private List<String> validationErrors = new ArrayList<>();

  public ComponentValidationResultDTO() {
  }

  public ComponentValidationResultDTO activeThreadCount(@javax.annotation.Nullable Integer activeThreadCount) {
    
    this.activeThreadCount = activeThreadCount;
    return this;
  }

  /**
   * The number of active threads for the referencing component.
   * @return activeThreadCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTIVE_THREAD_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getActiveThreadCount() {
    return activeThreadCount;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE_THREAD_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActiveThreadCount(@javax.annotation.Nullable Integer activeThreadCount) {
    this.activeThreadCount = activeThreadCount;
  }

  public ComponentValidationResultDTO currentlyValid(@javax.annotation.Nullable Boolean currentlyValid) {
    
    this.currentlyValid = currentlyValid;
    return this;
  }

  /**
   * Whether or not the component is currently valid
   * @return currentlyValid
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENTLY_VALID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCurrentlyValid() {
    return currentlyValid;
  }


  @JsonProperty(JSON_PROPERTY_CURRENTLY_VALID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrentlyValid(@javax.annotation.Nullable Boolean currentlyValid) {
    this.currentlyValid = currentlyValid;
  }

  public ComponentValidationResultDTO id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * The UUID of this component
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public ComponentValidationResultDTO name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of this component.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public ComponentValidationResultDTO processGroupId(@javax.annotation.Nullable String processGroupId) {
    
    this.processGroupId = processGroupId;
    return this;
  }

  /**
   * The UUID of the Process Group that this component is in
   * @return processGroupId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCESS_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProcessGroupId() {
    return processGroupId;
  }


  @JsonProperty(JSON_PROPERTY_PROCESS_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessGroupId(@javax.annotation.Nullable String processGroupId) {
    this.processGroupId = processGroupId;
  }

  public ComponentValidationResultDTO referenceType(@javax.annotation.Nullable ReferenceTypeEnum referenceType) {
    
    this.referenceType = referenceType;
    return this;
  }

  /**
   * The type of this component
   * @return referenceType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFERENCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ReferenceTypeEnum getReferenceType() {
    return referenceType;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReferenceType(@javax.annotation.Nullable ReferenceTypeEnum referenceType) {
    this.referenceType = referenceType;
  }

  public ComponentValidationResultDTO resultantValidationErrors(@javax.annotation.Nullable List<String> resultantValidationErrors) {
    
    this.resultantValidationErrors = resultantValidationErrors;
    return this;
  }

  public ComponentValidationResultDTO addResultantValidationErrorsItem(String resultantValidationErrorsItem) {
    if (this.resultantValidationErrors == null) {
      this.resultantValidationErrors = new ArrayList<>();
    }
    this.resultantValidationErrors.add(resultantValidationErrorsItem);
    return this;
  }

  /**
   * The validation errors that will apply to the component if the Parameter Context is changed
   * @return resultantValidationErrors
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULTANT_VALIDATION_ERRORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getResultantValidationErrors() {
    return resultantValidationErrors;
  }


  @JsonProperty(JSON_PROPERTY_RESULTANT_VALIDATION_ERRORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResultantValidationErrors(@javax.annotation.Nullable List<String> resultantValidationErrors) {
    this.resultantValidationErrors = resultantValidationErrors;
  }

  public ComponentValidationResultDTO resultsValid(@javax.annotation.Nullable Boolean resultsValid) {
    
    this.resultsValid = resultsValid;
    return this;
  }

  /**
   * Whether or not the component will be valid if the Parameter Context is changed
   * @return resultsValid
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULTS_VALID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getResultsValid() {
    return resultsValid;
  }


  @JsonProperty(JSON_PROPERTY_RESULTS_VALID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResultsValid(@javax.annotation.Nullable Boolean resultsValid) {
    this.resultsValid = resultsValid;
  }

  public ComponentValidationResultDTO state(@javax.annotation.Nullable String state) {
    
    this.state = state;
    return this;
  }

  /**
   * The scheduled state of a processor or reporting task referencing a controller service. If this component is another controller service, this field represents the controller service state.
   * @return state
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@javax.annotation.Nullable String state) {
    this.state = state;
  }

  public ComponentValidationResultDTO validationErrors(@javax.annotation.Nullable List<String> validationErrors) {
    
    this.validationErrors = validationErrors;
    return this;
  }

  public ComponentValidationResultDTO addValidationErrorsItem(String validationErrorsItem) {
    if (this.validationErrors == null) {
      this.validationErrors = new ArrayList<>();
    }
    this.validationErrors.add(validationErrorsItem);
    return this;
  }

  /**
   * The validation errors for the component.
   * @return validationErrors
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALIDATION_ERRORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getValidationErrors() {
    return validationErrors;
  }


  @JsonProperty(JSON_PROPERTY_VALIDATION_ERRORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidationErrors(@javax.annotation.Nullable List<String> validationErrors) {
    this.validationErrors = validationErrors;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComponentValidationResultDTO componentValidationResultDTO = (ComponentValidationResultDTO) o;
    return Objects.equals(this.activeThreadCount, componentValidationResultDTO.activeThreadCount) &&
        Objects.equals(this.currentlyValid, componentValidationResultDTO.currentlyValid) &&
        Objects.equals(this.id, componentValidationResultDTO.id) &&
        Objects.equals(this.name, componentValidationResultDTO.name) &&
        Objects.equals(this.processGroupId, componentValidationResultDTO.processGroupId) &&
        Objects.equals(this.referenceType, componentValidationResultDTO.referenceType) &&
        Objects.equals(this.resultantValidationErrors, componentValidationResultDTO.resultantValidationErrors) &&
        Objects.equals(this.resultsValid, componentValidationResultDTO.resultsValid) &&
        Objects.equals(this.state, componentValidationResultDTO.state) &&
        Objects.equals(this.validationErrors, componentValidationResultDTO.validationErrors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeThreadCount, currentlyValid, id, name, processGroupId, referenceType, resultantValidationErrors, resultsValid, state, validationErrors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComponentValidationResultDTO {\n");
    sb.append("    activeThreadCount: ").append(toIndentedString(activeThreadCount)).append("\n");
    sb.append("    currentlyValid: ").append(toIndentedString(currentlyValid)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    processGroupId: ").append(toIndentedString(processGroupId)).append("\n");
    sb.append("    referenceType: ").append(toIndentedString(referenceType)).append("\n");
    sb.append("    resultantValidationErrors: ").append(toIndentedString(resultantValidationErrors)).append("\n");
    sb.append("    resultsValid: ").append(toIndentedString(resultsValid)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    validationErrors: ").append(toIndentedString(validationErrors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

