/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.giwi.nifi.tester.model.RevisionDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ControllerServiceRunStatusEntity
 */
@JsonPropertyOrder({
  ControllerServiceRunStatusEntity.JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED,
  ControllerServiceRunStatusEntity.JSON_PROPERTY_REVISION,
  ControllerServiceRunStatusEntity.JSON_PROPERTY_STATE,
  ControllerServiceRunStatusEntity.JSON_PROPERTY_UI_ONLY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ControllerServiceRunStatusEntity {
  public static final String JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED = "disconnectedNodeAcknowledged";
  @javax.annotation.Nullable
  private Boolean disconnectedNodeAcknowledged;

  public static final String JSON_PROPERTY_REVISION = "revision";
  @javax.annotation.Nullable
  private RevisionDTO revision;

  /**
   * The run status of the ControllerService.
   */
  public enum StateEnum {
    ENABLED(String.valueOf("ENABLED")),
    
    DISABLED(String.valueOf("DISABLED"));

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nullable
  private StateEnum state;

  public static final String JSON_PROPERTY_UI_ONLY = "uiOnly";
  @javax.annotation.Nullable
  private Boolean uiOnly;

  public ControllerServiceRunStatusEntity() {
  }

  public ControllerServiceRunStatusEntity disconnectedNodeAcknowledged(@javax.annotation.Nullable Boolean disconnectedNodeAcknowledged) {
    
    this.disconnectedNodeAcknowledged = disconnectedNodeAcknowledged;
    return this;
  }

  /**
   * Acknowledges that this node is disconnected to allow for mutable requests to proceed.
   * @return disconnectedNodeAcknowledged
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisconnectedNodeAcknowledged() {
    return disconnectedNodeAcknowledged;
  }


  @JsonProperty(JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisconnectedNodeAcknowledged(@javax.annotation.Nullable Boolean disconnectedNodeAcknowledged) {
    this.disconnectedNodeAcknowledged = disconnectedNodeAcknowledged;
  }

  public ControllerServiceRunStatusEntity revision(@javax.annotation.Nullable RevisionDTO revision) {
    
    this.revision = revision;
    return this;
  }

  /**
   * Get revision
   * @return revision
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RevisionDTO getRevision() {
    return revision;
  }


  @JsonProperty(JSON_PROPERTY_REVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRevision(@javax.annotation.Nullable RevisionDTO revision) {
    this.revision = revision;
  }

  public ControllerServiceRunStatusEntity state(@javax.annotation.Nullable StateEnum state) {
    
    this.state = state;
    return this;
  }

  /**
   * The run status of the ControllerService.
   * @return state
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StateEnum getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@javax.annotation.Nullable StateEnum state) {
    this.state = state;
  }

  public ControllerServiceRunStatusEntity uiOnly(@javax.annotation.Nullable Boolean uiOnly) {
    
    this.uiOnly = uiOnly;
    return this;
  }

  /**
   * Indicates whether or not responses should only include fields necessary for rendering the NiFi User Interface. As such, when this value is set to true, some fields may be returned as null values, and the selected fields may change at any time without notice. As a result, this value should not be set to true by any client other than the UI. 
   * @return uiOnly
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UI_ONLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUiOnly() {
    return uiOnly;
  }


  @JsonProperty(JSON_PROPERTY_UI_ONLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUiOnly(@javax.annotation.Nullable Boolean uiOnly) {
    this.uiOnly = uiOnly;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ControllerServiceRunStatusEntity controllerServiceRunStatusEntity = (ControllerServiceRunStatusEntity) o;
    return Objects.equals(this.disconnectedNodeAcknowledged, controllerServiceRunStatusEntity.disconnectedNodeAcknowledged) &&
        Objects.equals(this.revision, controllerServiceRunStatusEntity.revision) &&
        Objects.equals(this.state, controllerServiceRunStatusEntity.state) &&
        Objects.equals(this.uiOnly, controllerServiceRunStatusEntity.uiOnly);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disconnectedNodeAcknowledged, revision, state, uiOnly);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ControllerServiceRunStatusEntity {\n");
    sb.append("    disconnectedNodeAcknowledged: ").append(toIndentedString(disconnectedNodeAcknowledged)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    uiOnly: ").append(toIndentedString(uiOnly)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

