/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import org.giwi.nifi.tester.model.ExternalControllerServiceReference;
import org.giwi.nifi.tester.model.ParameterProviderReference;
import org.giwi.nifi.tester.model.VersionedConnection;
import org.giwi.nifi.tester.model.VersionedFunnel;
import org.giwi.nifi.tester.model.VersionedLabel;
import org.giwi.nifi.tester.model.VersionedParameterContext;
import org.giwi.nifi.tester.model.VersionedPort;
import org.giwi.nifi.tester.model.VersionedProcessGroup;
import org.giwi.nifi.tester.model.VersionedProcessor;
import org.giwi.nifi.tester.model.VersionedRemoteProcessGroup;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The response from copying.
 */
@JsonPropertyOrder({
  CopyResponseEntity.JSON_PROPERTY_CONNECTIONS,
  CopyResponseEntity.JSON_PROPERTY_EXTERNAL_CONTROLLER_SERVICE_REFERENCES,
  CopyResponseEntity.JSON_PROPERTY_FUNNELS,
  CopyResponseEntity.JSON_PROPERTY_ID,
  CopyResponseEntity.JSON_PROPERTY_INPUT_PORTS,
  CopyResponseEntity.JSON_PROPERTY_LABELS,
  CopyResponseEntity.JSON_PROPERTY_OUTPUT_PORTS,
  CopyResponseEntity.JSON_PROPERTY_PARAMETER_CONTEXTS,
  CopyResponseEntity.JSON_PROPERTY_PARAMETER_PROVIDERS,
  CopyResponseEntity.JSON_PROPERTY_PROCESS_GROUPS,
  CopyResponseEntity.JSON_PROPERTY_PROCESSORS,
  CopyResponseEntity.JSON_PROPERTY_REMOTE_PROCESS_GROUPS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class CopyResponseEntity {
  public static final String JSON_PROPERTY_CONNECTIONS = "connections";
  @javax.annotation.Nullable
  private Set<VersionedConnection> connections = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_EXTERNAL_CONTROLLER_SERVICE_REFERENCES = "externalControllerServiceReferences";
  @javax.annotation.Nullable
  private Map<String, ExternalControllerServiceReference> externalControllerServiceReferences = new HashMap<>();

  public static final String JSON_PROPERTY_FUNNELS = "funnels";
  @javax.annotation.Nullable
  private Set<VersionedFunnel> funnels = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_INPUT_PORTS = "inputPorts";
  @javax.annotation.Nullable
  private Set<VersionedPort> inputPorts = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_LABELS = "labels";
  @javax.annotation.Nullable
  private Set<VersionedLabel> labels = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_OUTPUT_PORTS = "outputPorts";
  @javax.annotation.Nullable
  private Set<VersionedPort> outputPorts = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_PARAMETER_CONTEXTS = "parameterContexts";
  @javax.annotation.Nullable
  private Map<String, VersionedParameterContext> parameterContexts = new HashMap<>();

  public static final String JSON_PROPERTY_PARAMETER_PROVIDERS = "parameterProviders";
  @javax.annotation.Nullable
  private Map<String, ParameterProviderReference> parameterProviders = new HashMap<>();

  public static final String JSON_PROPERTY_PROCESS_GROUPS = "processGroups";
  @javax.annotation.Nullable
  private Set<VersionedProcessGroup> processGroups = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_PROCESSORS = "processors";
  @javax.annotation.Nullable
  private Set<VersionedProcessor> processors = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_REMOTE_PROCESS_GROUPS = "remoteProcessGroups";
  @javax.annotation.Nullable
  private Set<VersionedRemoteProcessGroup> remoteProcessGroups = new LinkedHashSet<>();

  public CopyResponseEntity() {
  }

  public CopyResponseEntity connections(@javax.annotation.Nullable Set<VersionedConnection> connections) {
    
    this.connections = connections;
    return this;
  }

  public CopyResponseEntity addConnectionsItem(VersionedConnection connectionsItem) {
    if (this.connections == null) {
      this.connections = new LinkedHashSet<>();
    }
    this.connections.add(connectionsItem);
    return this;
  }

  /**
   * The connections being copied.
   * @return connections
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONNECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<VersionedConnection> getConnections() {
    return connections;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_CONNECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConnections(@javax.annotation.Nullable Set<VersionedConnection> connections) {
    this.connections = connections;
  }

  public CopyResponseEntity externalControllerServiceReferences(@javax.annotation.Nullable Map<String, ExternalControllerServiceReference> externalControllerServiceReferences) {
    
    this.externalControllerServiceReferences = externalControllerServiceReferences;
    return this;
  }

  public CopyResponseEntity putExternalControllerServiceReferencesItem(String key, ExternalControllerServiceReference externalControllerServiceReferencesItem) {
    if (this.externalControllerServiceReferences == null) {
      this.externalControllerServiceReferences = new HashMap<>();
    }
    this.externalControllerServiceReferences.put(key, externalControllerServiceReferencesItem);
    return this;
  }

  /**
   * The external controller service references.
   * @return externalControllerServiceReferences
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTERNAL_CONTROLLER_SERVICE_REFERENCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, ExternalControllerServiceReference> getExternalControllerServiceReferences() {
    return externalControllerServiceReferences;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_CONTROLLER_SERVICE_REFERENCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalControllerServiceReferences(@javax.annotation.Nullable Map<String, ExternalControllerServiceReference> externalControllerServiceReferences) {
    this.externalControllerServiceReferences = externalControllerServiceReferences;
  }

  public CopyResponseEntity funnels(@javax.annotation.Nullable Set<VersionedFunnel> funnels) {
    
    this.funnels = funnels;
    return this;
  }

  public CopyResponseEntity addFunnelsItem(VersionedFunnel funnelsItem) {
    if (this.funnels == null) {
      this.funnels = new LinkedHashSet<>();
    }
    this.funnels.add(funnelsItem);
    return this;
  }

  /**
   * The funnels being copied.
   * @return funnels
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FUNNELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<VersionedFunnel> getFunnels() {
    return funnels;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_FUNNELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFunnels(@javax.annotation.Nullable Set<VersionedFunnel> funnels) {
    this.funnels = funnels;
  }

  public CopyResponseEntity id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * The id for this copy action.
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public CopyResponseEntity inputPorts(@javax.annotation.Nullable Set<VersionedPort> inputPorts) {
    
    this.inputPorts = inputPorts;
    return this;
  }

  public CopyResponseEntity addInputPortsItem(VersionedPort inputPortsItem) {
    if (this.inputPorts == null) {
      this.inputPorts = new LinkedHashSet<>();
    }
    this.inputPorts.add(inputPortsItem);
    return this;
  }

  /**
   * The input ports being copied.
   * @return inputPorts
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPUT_PORTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<VersionedPort> getInputPorts() {
    return inputPorts;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_INPUT_PORTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInputPorts(@javax.annotation.Nullable Set<VersionedPort> inputPorts) {
    this.inputPorts = inputPorts;
  }

  public CopyResponseEntity labels(@javax.annotation.Nullable Set<VersionedLabel> labels) {
    
    this.labels = labels;
    return this;
  }

  public CopyResponseEntity addLabelsItem(VersionedLabel labelsItem) {
    if (this.labels == null) {
      this.labels = new LinkedHashSet<>();
    }
    this.labels.add(labelsItem);
    return this;
  }

  /**
   * The labels being copied.
   * @return labels
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<VersionedLabel> getLabels() {
    return labels;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabels(@javax.annotation.Nullable Set<VersionedLabel> labels) {
    this.labels = labels;
  }

  public CopyResponseEntity outputPorts(@javax.annotation.Nullable Set<VersionedPort> outputPorts) {
    
    this.outputPorts = outputPorts;
    return this;
  }

  public CopyResponseEntity addOutputPortsItem(VersionedPort outputPortsItem) {
    if (this.outputPorts == null) {
      this.outputPorts = new LinkedHashSet<>();
    }
    this.outputPorts.add(outputPortsItem);
    return this;
  }

  /**
   * The output ports being copied.
   * @return outputPorts
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OUTPUT_PORTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<VersionedPort> getOutputPorts() {
    return outputPorts;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_OUTPUT_PORTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutputPorts(@javax.annotation.Nullable Set<VersionedPort> outputPorts) {
    this.outputPorts = outputPorts;
  }

  public CopyResponseEntity parameterContexts(@javax.annotation.Nullable Map<String, VersionedParameterContext> parameterContexts) {
    
    this.parameterContexts = parameterContexts;
    return this;
  }

  public CopyResponseEntity putParameterContextsItem(String key, VersionedParameterContext parameterContextsItem) {
    if (this.parameterContexts == null) {
      this.parameterContexts = new HashMap<>();
    }
    this.parameterContexts.put(key, parameterContextsItem);
    return this;
  }

  /**
   * The referenced parameter contexts.
   * @return parameterContexts
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARAMETER_CONTEXTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, VersionedParameterContext> getParameterContexts() {
    return parameterContexts;
  }


  @JsonProperty(JSON_PROPERTY_PARAMETER_CONTEXTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParameterContexts(@javax.annotation.Nullable Map<String, VersionedParameterContext> parameterContexts) {
    this.parameterContexts = parameterContexts;
  }

  public CopyResponseEntity parameterProviders(@javax.annotation.Nullable Map<String, ParameterProviderReference> parameterProviders) {
    
    this.parameterProviders = parameterProviders;
    return this;
  }

  public CopyResponseEntity putParameterProvidersItem(String key, ParameterProviderReference parameterProvidersItem) {
    if (this.parameterProviders == null) {
      this.parameterProviders = new HashMap<>();
    }
    this.parameterProviders.put(key, parameterProvidersItem);
    return this;
  }

  /**
   * The referenced parameter providers.
   * @return parameterProviders
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARAMETER_PROVIDERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, ParameterProviderReference> getParameterProviders() {
    return parameterProviders;
  }


  @JsonProperty(JSON_PROPERTY_PARAMETER_PROVIDERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParameterProviders(@javax.annotation.Nullable Map<String, ParameterProviderReference> parameterProviders) {
    this.parameterProviders = parameterProviders;
  }

  public CopyResponseEntity processGroups(@javax.annotation.Nullable Set<VersionedProcessGroup> processGroups) {
    
    this.processGroups = processGroups;
    return this;
  }

  public CopyResponseEntity addProcessGroupsItem(VersionedProcessGroup processGroupsItem) {
    if (this.processGroups == null) {
      this.processGroups = new LinkedHashSet<>();
    }
    this.processGroups.add(processGroupsItem);
    return this;
  }

  /**
   * The process groups being copied.
   * @return processGroups
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCESS_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<VersionedProcessGroup> getProcessGroups() {
    return processGroups;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_PROCESS_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessGroups(@javax.annotation.Nullable Set<VersionedProcessGroup> processGroups) {
    this.processGroups = processGroups;
  }

  public CopyResponseEntity processors(@javax.annotation.Nullable Set<VersionedProcessor> processors) {
    
    this.processors = processors;
    return this;
  }

  public CopyResponseEntity addProcessorsItem(VersionedProcessor processorsItem) {
    if (this.processors == null) {
      this.processors = new LinkedHashSet<>();
    }
    this.processors.add(processorsItem);
    return this;
  }

  /**
   * The processors being copied.
   * @return processors
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCESSORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<VersionedProcessor> getProcessors() {
    return processors;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_PROCESSORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessors(@javax.annotation.Nullable Set<VersionedProcessor> processors) {
    this.processors = processors;
  }

  public CopyResponseEntity remoteProcessGroups(@javax.annotation.Nullable Set<VersionedRemoteProcessGroup> remoteProcessGroups) {
    
    this.remoteProcessGroups = remoteProcessGroups;
    return this;
  }

  public CopyResponseEntity addRemoteProcessGroupsItem(VersionedRemoteProcessGroup remoteProcessGroupsItem) {
    if (this.remoteProcessGroups == null) {
      this.remoteProcessGroups = new LinkedHashSet<>();
    }
    this.remoteProcessGroups.add(remoteProcessGroupsItem);
    return this;
  }

  /**
   * The remote process groups being copied.
   * @return remoteProcessGroups
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REMOTE_PROCESS_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<VersionedRemoteProcessGroup> getRemoteProcessGroups() {
    return remoteProcessGroups;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_REMOTE_PROCESS_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRemoteProcessGroups(@javax.annotation.Nullable Set<VersionedRemoteProcessGroup> remoteProcessGroups) {
    this.remoteProcessGroups = remoteProcessGroups;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CopyResponseEntity copyResponseEntity = (CopyResponseEntity) o;
    return Objects.equals(this.connections, copyResponseEntity.connections) &&
        Objects.equals(this.externalControllerServiceReferences, copyResponseEntity.externalControllerServiceReferences) &&
        Objects.equals(this.funnels, copyResponseEntity.funnels) &&
        Objects.equals(this.id, copyResponseEntity.id) &&
        Objects.equals(this.inputPorts, copyResponseEntity.inputPorts) &&
        Objects.equals(this.labels, copyResponseEntity.labels) &&
        Objects.equals(this.outputPorts, copyResponseEntity.outputPorts) &&
        Objects.equals(this.parameterContexts, copyResponseEntity.parameterContexts) &&
        Objects.equals(this.parameterProviders, copyResponseEntity.parameterProviders) &&
        Objects.equals(this.processGroups, copyResponseEntity.processGroups) &&
        Objects.equals(this.processors, copyResponseEntity.processors) &&
        Objects.equals(this.remoteProcessGroups, copyResponseEntity.remoteProcessGroups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(connections, externalControllerServiceReferences, funnels, id, inputPorts, labels, outputPorts, parameterContexts, parameterProviders, processGroups, processors, remoteProcessGroups);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CopyResponseEntity {\n");
    sb.append("    connections: ").append(toIndentedString(connections)).append("\n");
    sb.append("    externalControllerServiceReferences: ").append(toIndentedString(externalControllerServiceReferences)).append("\n");
    sb.append("    funnels: ").append(toIndentedString(funnels)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    inputPorts: ").append(toIndentedString(inputPorts)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    outputPorts: ").append(toIndentedString(outputPorts)).append("\n");
    sb.append("    parameterContexts: ").append(toIndentedString(parameterContexts)).append("\n");
    sb.append("    parameterProviders: ").append(toIndentedString(parameterProviders)).append("\n");
    sb.append("    processGroups: ").append(toIndentedString(processGroups)).append("\n");
    sb.append("    processors: ").append(toIndentedString(processors)).append("\n");
    sb.append("    remoteProcessGroups: ").append(toIndentedString(remoteProcessGroups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

