/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.giwi.nifi.tester.model.CounterDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The counters from the node.
 */
@JsonPropertyOrder({
  CountersSnapshotDTO.JSON_PROPERTY_COUNTERS,
  CountersSnapshotDTO.JSON_PROPERTY_GENERATED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class CountersSnapshotDTO {
  public static final String JSON_PROPERTY_COUNTERS = "counters";
  @javax.annotation.Nullable
  private List<CounterDTO> counters = new ArrayList<>();

  public static final String JSON_PROPERTY_GENERATED = "generated";
  @javax.annotation.Nullable
  private String generated;

  public CountersSnapshotDTO() {
  }

  public CountersSnapshotDTO counters(@javax.annotation.Nullable List<CounterDTO> counters) {
    
    this.counters = counters;
    return this;
  }

  public CountersSnapshotDTO addCountersItem(CounterDTO countersItem) {
    if (this.counters == null) {
      this.counters = new ArrayList<>();
    }
    this.counters.add(countersItem);
    return this;
  }

  /**
   * All counters in the NiFi.
   * @return counters
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CounterDTO> getCounters() {
    return counters;
  }


  @JsonProperty(JSON_PROPERTY_COUNTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCounters(@javax.annotation.Nullable List<CounterDTO> counters) {
    this.counters = counters;
  }

  public CountersSnapshotDTO generated(@javax.annotation.Nullable String generated) {
    
    this.generated = generated;
    return this;
  }

  /**
   * The timestamp when the report was generated.
   * @return generated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GENERATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGenerated() {
    return generated;
  }


  @JsonProperty(JSON_PROPERTY_GENERATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGenerated(@javax.annotation.Nullable String generated) {
    this.generated = generated;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CountersSnapshotDTO countersSnapshotDTO = (CountersSnapshotDTO) o;
    return Objects.equals(this.counters, countersSnapshotDTO.counters) &&
        Objects.equals(this.generated, countersSnapshotDTO.generated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(counters, generated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CountersSnapshotDTO {\n");
    sb.append("    counters: ").append(toIndentedString(counters)).append("\n");
    sb.append("    generated: ").append(toIndentedString(generated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

