/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.giwi.nifi.tester.model.FlowBreadcrumbDTO;
import org.giwi.nifi.tester.model.PermissionsDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The breadcrumb of the process group.
 */
@JsonPropertyOrder({
  FlowBreadcrumbEntity.JSON_PROPERTY_BREADCRUMB,
  FlowBreadcrumbEntity.JSON_PROPERTY_ID,
  FlowBreadcrumbEntity.JSON_PROPERTY_PARENT_BREADCRUMB,
  FlowBreadcrumbEntity.JSON_PROPERTY_PERMISSIONS,
  FlowBreadcrumbEntity.JSON_PROPERTY_VERSIONED_FLOW_STATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class FlowBreadcrumbEntity {
  public static final String JSON_PROPERTY_BREADCRUMB = "breadcrumb";
  @javax.annotation.Nullable
  private FlowBreadcrumbDTO breadcrumb;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_PARENT_BREADCRUMB = "parentBreadcrumb";
  @javax.annotation.Nullable
  private FlowBreadcrumbEntity parentBreadcrumb;

  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  @javax.annotation.Nullable
  private PermissionsDTO permissions;

  /**
   * The current state of the Process Group, as it relates to the Versioned Flow
   */
  public enum VersionedFlowStateEnum {
    LOCALLY_MODIFIED(String.valueOf("LOCALLY_MODIFIED")),
    
    STALE(String.valueOf("STALE")),
    
    LOCALLY_MODIFIED_AND_STALE(String.valueOf("LOCALLY_MODIFIED_AND_STALE")),
    
    UP_TO_DATE(String.valueOf("UP_TO_DATE")),
    
    SYNC_FAILURE(String.valueOf("SYNC_FAILURE"));

    private String value;

    VersionedFlowStateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VersionedFlowStateEnum fromValue(String value) {
      for (VersionedFlowStateEnum b : VersionedFlowStateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VERSIONED_FLOW_STATE = "versionedFlowState";
  @javax.annotation.Nullable
  private VersionedFlowStateEnum versionedFlowState;

  public FlowBreadcrumbEntity() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public FlowBreadcrumbEntity(
    @JsonProperty(JSON_PROPERTY_VERSIONED_FLOW_STATE) VersionedFlowStateEnum versionedFlowState
  ) {
    this();
    this.versionedFlowState = versionedFlowState;
  }

  public FlowBreadcrumbEntity breadcrumb(@javax.annotation.Nullable FlowBreadcrumbDTO breadcrumb) {
    
    this.breadcrumb = breadcrumb;
    return this;
  }

  /**
   * Get breadcrumb
   * @return breadcrumb
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BREADCRUMB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FlowBreadcrumbDTO getBreadcrumb() {
    return breadcrumb;
  }


  @JsonProperty(JSON_PROPERTY_BREADCRUMB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBreadcrumb(@javax.annotation.Nullable FlowBreadcrumbDTO breadcrumb) {
    this.breadcrumb = breadcrumb;
  }

  public FlowBreadcrumbEntity id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * The id of this ancestor ProcessGroup.
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public FlowBreadcrumbEntity parentBreadcrumb(@javax.annotation.Nullable FlowBreadcrumbEntity parentBreadcrumb) {
    
    this.parentBreadcrumb = parentBreadcrumb;
    return this;
  }

  /**
   * Get parentBreadcrumb
   * @return parentBreadcrumb
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARENT_BREADCRUMB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FlowBreadcrumbEntity getParentBreadcrumb() {
    return parentBreadcrumb;
  }


  @JsonProperty(JSON_PROPERTY_PARENT_BREADCRUMB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParentBreadcrumb(@javax.annotation.Nullable FlowBreadcrumbEntity parentBreadcrumb) {
    this.parentBreadcrumb = parentBreadcrumb;
  }

  public FlowBreadcrumbEntity permissions(@javax.annotation.Nullable PermissionsDTO permissions) {
    
    this.permissions = permissions;
    return this;
  }

  /**
   * Get permissions
   * @return permissions
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PermissionsDTO getPermissions() {
    return permissions;
  }


  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermissions(@javax.annotation.Nullable PermissionsDTO permissions) {
    this.permissions = permissions;
  }

  /**
   * The current state of the Process Group, as it relates to the Versioned Flow
   * @return versionedFlowState
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSIONED_FLOW_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VersionedFlowStateEnum getVersionedFlowState() {
    return versionedFlowState;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlowBreadcrumbEntity flowBreadcrumbEntity = (FlowBreadcrumbEntity) o;
    return Objects.equals(this.breadcrumb, flowBreadcrumbEntity.breadcrumb) &&
        Objects.equals(this.id, flowBreadcrumbEntity.id) &&
        Objects.equals(this.parentBreadcrumb, flowBreadcrumbEntity.parentBreadcrumb) &&
        Objects.equals(this.permissions, flowBreadcrumbEntity.permissions) &&
        Objects.equals(this.versionedFlowState, flowBreadcrumbEntity.versionedFlowState);
  }

  @Override
  public int hashCode() {
    return Objects.hash(breadcrumb, id, parentBreadcrumb, permissions, versionedFlowState);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlowBreadcrumbEntity {\n");
    sb.append("    breadcrumb: ").append(toIndentedString(breadcrumb)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    parentBreadcrumb: ").append(toIndentedString(parentBreadcrumb)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    versionedFlowState: ").append(toIndentedString(versionedFlowState)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

