/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.LinkedHashSet;
import java.util.Set;
import org.giwi.nifi.tester.model.FlowAnalysisRuleEntity;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FlowAnalysisRulesEntity
 */
@JsonPropertyOrder({
  FlowAnalysisRulesEntity.JSON_PROPERTY_CURRENT_TIME,
  FlowAnalysisRulesEntity.JSON_PROPERTY_FLOW_ANALYSIS_RULES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class FlowAnalysisRulesEntity {
  public static final String JSON_PROPERTY_CURRENT_TIME = "currentTime";
  @javax.annotation.Nullable
  private String currentTime;

  public static final String JSON_PROPERTY_FLOW_ANALYSIS_RULES = "flowAnalysisRules";
  @javax.annotation.Nullable
  private Set<FlowAnalysisRuleEntity> flowAnalysisRules = new LinkedHashSet<>();

  public FlowAnalysisRulesEntity() {
  }

  public FlowAnalysisRulesEntity currentTime(@javax.annotation.Nullable String currentTime) {
    
    this.currentTime = currentTime;
    return this;
  }

  /**
   * The current time on the system.
   * @return currentTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrentTime() {
    return currentTime;
  }


  @JsonProperty(JSON_PROPERTY_CURRENT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrentTime(@javax.annotation.Nullable String currentTime) {
    this.currentTime = currentTime;
  }

  public FlowAnalysisRulesEntity flowAnalysisRules(@javax.annotation.Nullable Set<FlowAnalysisRuleEntity> flowAnalysisRules) {
    
    this.flowAnalysisRules = flowAnalysisRules;
    return this;
  }

  public FlowAnalysisRulesEntity addFlowAnalysisRulesItem(FlowAnalysisRuleEntity flowAnalysisRulesItem) {
    if (this.flowAnalysisRules == null) {
      this.flowAnalysisRules = new LinkedHashSet<>();
    }
    this.flowAnalysisRules.add(flowAnalysisRulesItem);
    return this;
  }

  /**
   * Get flowAnalysisRules
   * @return flowAnalysisRules
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLOW_ANALYSIS_RULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<FlowAnalysisRuleEntity> getFlowAnalysisRules() {
    return flowAnalysisRules;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_FLOW_ANALYSIS_RULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowAnalysisRules(@javax.annotation.Nullable Set<FlowAnalysisRuleEntity> flowAnalysisRules) {
    this.flowAnalysisRules = flowAnalysisRules;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlowAnalysisRulesEntity flowAnalysisRulesEntity = (FlowAnalysisRulesEntity) o;
    return Objects.equals(this.currentTime, flowAnalysisRulesEntity.currentTime) &&
        Objects.equals(this.flowAnalysisRules, flowAnalysisRulesEntity.flowAnalysisRules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentTime, flowAnalysisRules);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlowAnalysisRulesEntity {\n");
    sb.append("    currentTime: ").append(toIndentedString(currentTime)).append("\n");
    sb.append("    flowAnalysisRules: ").append(toIndentedString(flowAnalysisRules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

