/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.giwi.nifi.tester.model.ProvenanceEventDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * LatestProvenanceEventsDTO
 */
@JsonPropertyOrder({
  LatestProvenanceEventsDTO.JSON_PROPERTY_COMPONENT_ID,
  LatestProvenanceEventsDTO.JSON_PROPERTY_PROVENANCE_EVENTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class LatestProvenanceEventsDTO {
  public static final String JSON_PROPERTY_COMPONENT_ID = "componentId";
  @javax.annotation.Nullable
  private String componentId;

  public static final String JSON_PROPERTY_PROVENANCE_EVENTS = "provenanceEvents";
  @javax.annotation.Nullable
  private List<ProvenanceEventDTO> provenanceEvents = new ArrayList<>();

  public LatestProvenanceEventsDTO() {
  }

  public LatestProvenanceEventsDTO componentId(@javax.annotation.Nullable String componentId) {
    
    this.componentId = componentId;
    return this;
  }

  /**
   * Get componentId
   * @return componentId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPONENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComponentId() {
    return componentId;
  }


  @JsonProperty(JSON_PROPERTY_COMPONENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComponentId(@javax.annotation.Nullable String componentId) {
    this.componentId = componentId;
  }

  public LatestProvenanceEventsDTO provenanceEvents(@javax.annotation.Nullable List<ProvenanceEventDTO> provenanceEvents) {
    
    this.provenanceEvents = provenanceEvents;
    return this;
  }

  public LatestProvenanceEventsDTO addProvenanceEventsItem(ProvenanceEventDTO provenanceEventsItem) {
    if (this.provenanceEvents == null) {
      this.provenanceEvents = new ArrayList<>();
    }
    this.provenanceEvents.add(provenanceEventsItem);
    return this;
  }

  /**
   * Get provenanceEvents
   * @return provenanceEvents
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROVENANCE_EVENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ProvenanceEventDTO> getProvenanceEvents() {
    return provenanceEvents;
  }


  @JsonProperty(JSON_PROPERTY_PROVENANCE_EVENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvenanceEvents(@javax.annotation.Nullable List<ProvenanceEventDTO> provenanceEvents) {
    this.provenanceEvents = provenanceEvents;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LatestProvenanceEventsDTO latestProvenanceEventsDTO = (LatestProvenanceEventsDTO) o;
    return Objects.equals(this.componentId, latestProvenanceEventsDTO.componentId) &&
        Objects.equals(this.provenanceEvents, latestProvenanceEventsDTO.provenanceEvents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(componentId, provenanceEvents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LatestProvenanceEventsDTO {\n");
    sb.append("    componentId: ").append(toIndentedString(componentId)).append("\n");
    sb.append("    provenanceEvents: ").append(toIndentedString(provenanceEvents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

