/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.giwi.nifi.tester.model.ListingRequestDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ListingRequestEntity
 */
@JsonPropertyOrder({
  ListingRequestEntity.JSON_PROPERTY_LISTING_REQUEST
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ListingRequestEntity {
  public static final String JSON_PROPERTY_LISTING_REQUEST = "listingRequest";
  @javax.annotation.Nullable
  private ListingRequestDTO listingRequest;

  public ListingRequestEntity() {
  }

  public ListingRequestEntity listingRequest(@javax.annotation.Nullable ListingRequestDTO listingRequest) {
    
    this.listingRequest = listingRequest;
    return this;
  }

  /**
   * Get listingRequest
   * @return listingRequest
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LISTING_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ListingRequestDTO getListingRequest() {
    return listingRequest;
  }


  @JsonProperty(JSON_PROPERTY_LISTING_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setListingRequest(@javax.annotation.Nullable ListingRequestDTO listingRequest) {
    this.listingRequest = listingRequest;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListingRequestEntity listingRequestEntity = (ListingRequestEntity) o;
    return Objects.equals(this.listingRequest, listingRequestEntity.listingRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(listingRequest);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListingRequestEntity {\n");
    sb.append("    listingRequest: ").append(toIndentedString(listingRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

