/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.giwi.nifi.tester.model.ProcessGroupStatusSnapshotDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The status reported by each node in the cluster. If the NiFi instance is a standalone instance, rather than a clustered instance, this value may be null.
 */
@JsonPropertyOrder({
  NodeProcessGroupStatusSnapshotDTO.JSON_PROPERTY_ADDRESS,
  NodeProcessGroupStatusSnapshotDTO.JSON_PROPERTY_API_PORT,
  NodeProcessGroupStatusSnapshotDTO.JSON_PROPERTY_NODE_ID,
  NodeProcessGroupStatusSnapshotDTO.JSON_PROPERTY_STATUS_SNAPSHOT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class NodeProcessGroupStatusSnapshotDTO {
  public static final String JSON_PROPERTY_ADDRESS = "address";
  @javax.annotation.Nullable
  private String address;

  public static final String JSON_PROPERTY_API_PORT = "apiPort";
  @javax.annotation.Nullable
  private Integer apiPort;

  public static final String JSON_PROPERTY_NODE_ID = "nodeId";
  @javax.annotation.Nullable
  private String nodeId;

  public static final String JSON_PROPERTY_STATUS_SNAPSHOT = "statusSnapshot";
  @javax.annotation.Nullable
  private ProcessGroupStatusSnapshotDTO statusSnapshot;

  public NodeProcessGroupStatusSnapshotDTO() {
  }

  public NodeProcessGroupStatusSnapshotDTO address(@javax.annotation.Nullable String address) {
    
    this.address = address;
    return this;
  }

  /**
   * The API address of the node
   * @return address
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(@javax.annotation.Nullable String address) {
    this.address = address;
  }

  public NodeProcessGroupStatusSnapshotDTO apiPort(@javax.annotation.Nullable Integer apiPort) {
    
    this.apiPort = apiPort;
    return this;
  }

  /**
   * The API port used to communicate with the node
   * @return apiPort
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getApiPort() {
    return apiPort;
  }


  @JsonProperty(JSON_PROPERTY_API_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiPort(@javax.annotation.Nullable Integer apiPort) {
    this.apiPort = apiPort;
  }

  public NodeProcessGroupStatusSnapshotDTO nodeId(@javax.annotation.Nullable String nodeId) {
    
    this.nodeId = nodeId;
    return this;
  }

  /**
   * The unique ID that identifies the node
   * @return nodeId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NODE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNodeId() {
    return nodeId;
  }


  @JsonProperty(JSON_PROPERTY_NODE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNodeId(@javax.annotation.Nullable String nodeId) {
    this.nodeId = nodeId;
  }

  public NodeProcessGroupStatusSnapshotDTO statusSnapshot(@javax.annotation.Nullable ProcessGroupStatusSnapshotDTO statusSnapshot) {
    
    this.statusSnapshot = statusSnapshot;
    return this;
  }

  /**
   * Get statusSnapshot
   * @return statusSnapshot
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS_SNAPSHOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProcessGroupStatusSnapshotDTO getStatusSnapshot() {
    return statusSnapshot;
  }


  @JsonProperty(JSON_PROPERTY_STATUS_SNAPSHOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusSnapshot(@javax.annotation.Nullable ProcessGroupStatusSnapshotDTO statusSnapshot) {
    this.statusSnapshot = statusSnapshot;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeProcessGroupStatusSnapshotDTO nodeProcessGroupStatusSnapshotDTO = (NodeProcessGroupStatusSnapshotDTO) o;
    return Objects.equals(this.address, nodeProcessGroupStatusSnapshotDTO.address) &&
        Objects.equals(this.apiPort, nodeProcessGroupStatusSnapshotDTO.apiPort) &&
        Objects.equals(this.nodeId, nodeProcessGroupStatusSnapshotDTO.nodeId) &&
        Objects.equals(this.statusSnapshot, nodeProcessGroupStatusSnapshotDTO.statusSnapshot);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, apiPort, nodeId, statusSnapshot);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeProcessGroupStatusSnapshotDTO {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    apiPort: ").append(toIndentedString(apiPort)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    statusSnapshot: ").append(toIndentedString(statusSnapshot)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

