/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.giwi.nifi.tester.model.ConnectionStatisticsSnapshotDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A list of status snapshots for each node
 */
@JsonPropertyOrder({
  NodeConnectionStatisticsSnapshotDTO.JSON_PROPERTY_ADDRESS,
  NodeConnectionStatisticsSnapshotDTO.JSON_PROPERTY_API_PORT,
  NodeConnectionStatisticsSnapshotDTO.JSON_PROPERTY_NODE_ID,
  NodeConnectionStatisticsSnapshotDTO.JSON_PROPERTY_STATISTICS_SNAPSHOT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class NodeConnectionStatisticsSnapshotDTO {
  public static final String JSON_PROPERTY_ADDRESS = "address";
  @javax.annotation.Nullable
  private String address;

  public static final String JSON_PROPERTY_API_PORT = "apiPort";
  @javax.annotation.Nullable
  private Integer apiPort;

  public static final String JSON_PROPERTY_NODE_ID = "nodeId";
  @javax.annotation.Nullable
  private String nodeId;

  public static final String JSON_PROPERTY_STATISTICS_SNAPSHOT = "statisticsSnapshot";
  @javax.annotation.Nullable
  private ConnectionStatisticsSnapshotDTO statisticsSnapshot;

  public NodeConnectionStatisticsSnapshotDTO() {
  }

  public NodeConnectionStatisticsSnapshotDTO address(@javax.annotation.Nullable String address) {
    
    this.address = address;
    return this;
  }

  /**
   * The API address of the node
   * @return address
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(@javax.annotation.Nullable String address) {
    this.address = address;
  }

  public NodeConnectionStatisticsSnapshotDTO apiPort(@javax.annotation.Nullable Integer apiPort) {
    
    this.apiPort = apiPort;
    return this;
  }

  /**
   * The API port used to communicate with the node
   * @return apiPort
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getApiPort() {
    return apiPort;
  }


  @JsonProperty(JSON_PROPERTY_API_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiPort(@javax.annotation.Nullable Integer apiPort) {
    this.apiPort = apiPort;
  }

  public NodeConnectionStatisticsSnapshotDTO nodeId(@javax.annotation.Nullable String nodeId) {
    
    this.nodeId = nodeId;
    return this;
  }

  /**
   * The unique ID that identifies the node
   * @return nodeId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NODE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNodeId() {
    return nodeId;
  }


  @JsonProperty(JSON_PROPERTY_NODE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNodeId(@javax.annotation.Nullable String nodeId) {
    this.nodeId = nodeId;
  }

  public NodeConnectionStatisticsSnapshotDTO statisticsSnapshot(@javax.annotation.Nullable ConnectionStatisticsSnapshotDTO statisticsSnapshot) {
    
    this.statisticsSnapshot = statisticsSnapshot;
    return this;
  }

  /**
   * Get statisticsSnapshot
   * @return statisticsSnapshot
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATISTICS_SNAPSHOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConnectionStatisticsSnapshotDTO getStatisticsSnapshot() {
    return statisticsSnapshot;
  }


  @JsonProperty(JSON_PROPERTY_STATISTICS_SNAPSHOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatisticsSnapshot(@javax.annotation.Nullable ConnectionStatisticsSnapshotDTO statisticsSnapshot) {
    this.statisticsSnapshot = statisticsSnapshot;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeConnectionStatisticsSnapshotDTO nodeConnectionStatisticsSnapshotDTO = (NodeConnectionStatisticsSnapshotDTO) o;
    return Objects.equals(this.address, nodeConnectionStatisticsSnapshotDTO.address) &&
        Objects.equals(this.apiPort, nodeConnectionStatisticsSnapshotDTO.apiPort) &&
        Objects.equals(this.nodeId, nodeConnectionStatisticsSnapshotDTO.nodeId) &&
        Objects.equals(this.statisticsSnapshot, nodeConnectionStatisticsSnapshotDTO.statisticsSnapshot);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, apiPort, nodeId, statisticsSnapshot);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeConnectionStatisticsSnapshotDTO {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    apiPort: ").append(toIndentedString(apiPort)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    statisticsSnapshot: ").append(toIndentedString(statisticsSnapshot)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

