/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.LinkedHashSet;
import java.util.Set;
import org.giwi.nifi.tester.model.DocumentedTypeDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ParameterProviderTypesEntity
 */
@JsonPropertyOrder({
  ParameterProviderTypesEntity.JSON_PROPERTY_PARAMETER_PROVIDER_TYPES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ParameterProviderTypesEntity {
  public static final String JSON_PROPERTY_PARAMETER_PROVIDER_TYPES = "parameterProviderTypes";
  @javax.annotation.Nullable
  private Set<DocumentedTypeDTO> parameterProviderTypes = new LinkedHashSet<>();

  public ParameterProviderTypesEntity() {
  }

  public ParameterProviderTypesEntity parameterProviderTypes(@javax.annotation.Nullable Set<DocumentedTypeDTO> parameterProviderTypes) {
    
    this.parameterProviderTypes = parameterProviderTypes;
    return this;
  }

  public ParameterProviderTypesEntity addParameterProviderTypesItem(DocumentedTypeDTO parameterProviderTypesItem) {
    if (this.parameterProviderTypes == null) {
      this.parameterProviderTypes = new LinkedHashSet<>();
    }
    this.parameterProviderTypes.add(parameterProviderTypesItem);
    return this;
  }

  /**
   * Get parameterProviderTypes
   * @return parameterProviderTypes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARAMETER_PROVIDER_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<DocumentedTypeDTO> getParameterProviderTypes() {
    return parameterProviderTypes;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_PARAMETER_PROVIDER_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParameterProviderTypes(@javax.annotation.Nullable Set<DocumentedTypeDTO> parameterProviderTypes) {
    this.parameterProviderTypes = parameterProviderTypes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParameterProviderTypesEntity parameterProviderTypesEntity = (ParameterProviderTypesEntity) o;
    return Objects.equals(this.parameterProviderTypes, parameterProviderTypesEntity.parameterProviderTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parameterProviderTypes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParameterProviderTypesEntity {\n");
    sb.append("    parameterProviderTypes: ").append(toIndentedString(parameterProviderTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

