/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PeerDTO
 */
@JsonPropertyOrder({
  PeerDTO.JSON_PROPERTY_FLOW_FILE_COUNT,
  PeerDTO.JSON_PROPERTY_HOSTNAME,
  PeerDTO.JSON_PROPERTY_PORT,
  PeerDTO.JSON_PROPERTY_SECURE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class PeerDTO {
  public static final String JSON_PROPERTY_FLOW_FILE_COUNT = "flowFileCount";
  @javax.annotation.Nullable
  private Integer flowFileCount;

  public static final String JSON_PROPERTY_HOSTNAME = "hostname";
  @javax.annotation.Nullable
  private String hostname;

  public static final String JSON_PROPERTY_PORT = "port";
  @javax.annotation.Nullable
  private Integer port;

  public static final String JSON_PROPERTY_SECURE = "secure";
  @javax.annotation.Nullable
  private Boolean secure;

  public PeerDTO() {
  }

  public PeerDTO flowFileCount(@javax.annotation.Nullable Integer flowFileCount) {
    
    this.flowFileCount = flowFileCount;
    return this;
  }

  /**
   * The number of flowFiles this peer holds.
   * @return flowFileCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLOW_FILE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFlowFileCount() {
    return flowFileCount;
  }


  @JsonProperty(JSON_PROPERTY_FLOW_FILE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowFileCount(@javax.annotation.Nullable Integer flowFileCount) {
    this.flowFileCount = flowFileCount;
  }

  public PeerDTO hostname(@javax.annotation.Nullable String hostname) {
    
    this.hostname = hostname;
    return this;
  }

  /**
   * The hostname of this peer.
   * @return hostname
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HOSTNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHostname() {
    return hostname;
  }


  @JsonProperty(JSON_PROPERTY_HOSTNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHostname(@javax.annotation.Nullable String hostname) {
    this.hostname = hostname;
  }

  public PeerDTO port(@javax.annotation.Nullable Integer port) {
    
    this.port = port;
    return this;
  }

  /**
   * The port number of this peer.
   * @return port
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPort() {
    return port;
  }


  @JsonProperty(JSON_PROPERTY_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPort(@javax.annotation.Nullable Integer port) {
    this.port = port;
  }

  public PeerDTO secure(@javax.annotation.Nullable Boolean secure) {
    
    this.secure = secure;
    return this;
  }

  /**
   * Returns if this peer connection is secure.
   * @return secure
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSecure() {
    return secure;
  }


  @JsonProperty(JSON_PROPERTY_SECURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecure(@javax.annotation.Nullable Boolean secure) {
    this.secure = secure;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PeerDTO peerDTO = (PeerDTO) o;
    return Objects.equals(this.flowFileCount, peerDTO.flowFileCount) &&
        Objects.equals(this.hostname, peerDTO.hostname) &&
        Objects.equals(this.port, peerDTO.port) &&
        Objects.equals(this.secure, peerDTO.secure);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flowFileCount, hostname, port, secure);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PeerDTO {\n");
    sb.append("    flowFileCount: ").append(toIndentedString(flowFileCount)).append("\n");
    sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    secure: ").append(toIndentedString(secure)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

