/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.giwi.nifi.tester.model.ProcessGroupReplaceRequestDTO;
import org.giwi.nifi.tester.model.RegisteredFlowSnapshot;
import org.giwi.nifi.tester.model.RevisionDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProcessGroupReplaceRequestEntity
 */
@JsonPropertyOrder({
  ProcessGroupReplaceRequestEntity.JSON_PROPERTY_PROCESS_GROUP_REVISION,
  ProcessGroupReplaceRequestEntity.JSON_PROPERTY_REQUEST,
  ProcessGroupReplaceRequestEntity.JSON_PROPERTY_VERSIONED_FLOW_SNAPSHOT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ProcessGroupReplaceRequestEntity {
  public static final String JSON_PROPERTY_PROCESS_GROUP_REVISION = "processGroupRevision";
  @javax.annotation.Nullable
  private RevisionDTO processGroupRevision;

  public static final String JSON_PROPERTY_REQUEST = "request";
  @javax.annotation.Nullable
  private ProcessGroupReplaceRequestDTO request;

  public static final String JSON_PROPERTY_VERSIONED_FLOW_SNAPSHOT = "versionedFlowSnapshot";
  @javax.annotation.Nullable
  private RegisteredFlowSnapshot versionedFlowSnapshot;

  public ProcessGroupReplaceRequestEntity() {
  }

  public ProcessGroupReplaceRequestEntity processGroupRevision(@javax.annotation.Nullable RevisionDTO processGroupRevision) {
    
    this.processGroupRevision = processGroupRevision;
    return this;
  }

  /**
   * Get processGroupRevision
   * @return processGroupRevision
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCESS_GROUP_REVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RevisionDTO getProcessGroupRevision() {
    return processGroupRevision;
  }


  @JsonProperty(JSON_PROPERTY_PROCESS_GROUP_REVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessGroupRevision(@javax.annotation.Nullable RevisionDTO processGroupRevision) {
    this.processGroupRevision = processGroupRevision;
  }

  public ProcessGroupReplaceRequestEntity request(@javax.annotation.Nullable ProcessGroupReplaceRequestDTO request) {
    
    this.request = request;
    return this;
  }

  /**
   * Get request
   * @return request
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProcessGroupReplaceRequestDTO getRequest() {
    return request;
  }


  @JsonProperty(JSON_PROPERTY_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequest(@javax.annotation.Nullable ProcessGroupReplaceRequestDTO request) {
    this.request = request;
  }

  public ProcessGroupReplaceRequestEntity versionedFlowSnapshot(@javax.annotation.Nullable RegisteredFlowSnapshot versionedFlowSnapshot) {
    
    this.versionedFlowSnapshot = versionedFlowSnapshot;
    return this;
  }

  /**
   * Get versionedFlowSnapshot
   * @return versionedFlowSnapshot
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSIONED_FLOW_SNAPSHOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RegisteredFlowSnapshot getVersionedFlowSnapshot() {
    return versionedFlowSnapshot;
  }


  @JsonProperty(JSON_PROPERTY_VERSIONED_FLOW_SNAPSHOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersionedFlowSnapshot(@javax.annotation.Nullable RegisteredFlowSnapshot versionedFlowSnapshot) {
    this.versionedFlowSnapshot = versionedFlowSnapshot;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessGroupReplaceRequestEntity processGroupReplaceRequestEntity = (ProcessGroupReplaceRequestEntity) o;
    return Objects.equals(this.processGroupRevision, processGroupReplaceRequestEntity.processGroupRevision) &&
        Objects.equals(this.request, processGroupReplaceRequestEntity.request) &&
        Objects.equals(this.versionedFlowSnapshot, processGroupReplaceRequestEntity.versionedFlowSnapshot);
  }

  @Override
  public int hashCode() {
    return Objects.hash(processGroupRevision, request, versionedFlowSnapshot);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessGroupReplaceRequestEntity {\n");
    sb.append("    processGroupRevision: ").append(toIndentedString(processGroupRevision)).append("\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    versionedFlowSnapshot: ").append(toIndentedString(versionedFlowSnapshot)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

