/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.giwi.nifi.tester.model.ProcessGroupStatusSnapshotDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The status of all process groups in the process group.
 */
@JsonPropertyOrder({
  ProcessGroupStatusSnapshotEntity.JSON_PROPERTY_CAN_READ,
  ProcessGroupStatusSnapshotEntity.JSON_PROPERTY_ID,
  ProcessGroupStatusSnapshotEntity.JSON_PROPERTY_PROCESS_GROUP_STATUS_SNAPSHOT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ProcessGroupStatusSnapshotEntity {
  public static final String JSON_PROPERTY_CAN_READ = "canRead";
  @javax.annotation.Nullable
  private Boolean canRead;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_PROCESS_GROUP_STATUS_SNAPSHOT = "processGroupStatusSnapshot";
  @javax.annotation.Nullable
  private ProcessGroupStatusSnapshotDTO processGroupStatusSnapshot;

  public ProcessGroupStatusSnapshotEntity() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public ProcessGroupStatusSnapshotEntity(
    @JsonProperty(JSON_PROPERTY_CAN_READ) Boolean canRead
  ) {
    this();
    this.canRead = canRead;
  }

  /**
   * Indicates whether the user can read a given resource.
   * @return canRead
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAN_READ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanRead() {
    return canRead;
  }



  public ProcessGroupStatusSnapshotEntity id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * The id of the process group.
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public ProcessGroupStatusSnapshotEntity processGroupStatusSnapshot(@javax.annotation.Nullable ProcessGroupStatusSnapshotDTO processGroupStatusSnapshot) {
    
    this.processGroupStatusSnapshot = processGroupStatusSnapshot;
    return this;
  }

  /**
   * Get processGroupStatusSnapshot
   * @return processGroupStatusSnapshot
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCESS_GROUP_STATUS_SNAPSHOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProcessGroupStatusSnapshotDTO getProcessGroupStatusSnapshot() {
    return processGroupStatusSnapshot;
  }


  @JsonProperty(JSON_PROPERTY_PROCESS_GROUP_STATUS_SNAPSHOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessGroupStatusSnapshot(@javax.annotation.Nullable ProcessGroupStatusSnapshotDTO processGroupStatusSnapshot) {
    this.processGroupStatusSnapshot = processGroupStatusSnapshot;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessGroupStatusSnapshotEntity processGroupStatusSnapshotEntity = (ProcessGroupStatusSnapshotEntity) o;
    return Objects.equals(this.canRead, processGroupStatusSnapshotEntity.canRead) &&
        Objects.equals(this.id, processGroupStatusSnapshotEntity.id) &&
        Objects.equals(this.processGroupStatusSnapshot, processGroupStatusSnapshotEntity.processGroupStatusSnapshot);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canRead, id, processGroupStatusSnapshot);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessGroupStatusSnapshotEntity {\n");
    sb.append("    canRead: ").append(toIndentedString(canRead)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    processGroupStatusSnapshot: ").append(toIndentedString(processGroupStatusSnapshot)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

