/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The dependencies that this property has on other properties
 */
@JsonPropertyOrder({
  PropertyDependency.JSON_PROPERTY_DEPENDENT_VALUES,
  PropertyDependency.JSON_PROPERTY_PROPERTY_DISPLAY_NAME,
  PropertyDependency.JSON_PROPERTY_PROPERTY_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class PropertyDependency {
  public static final String JSON_PROPERTY_DEPENDENT_VALUES = "dependentValues";
  @javax.annotation.Nullable
  private List<String> dependentValues = new ArrayList<>();

  public static final String JSON_PROPERTY_PROPERTY_DISPLAY_NAME = "propertyDisplayName";
  @javax.annotation.Nullable
  private String propertyDisplayName;

  public static final String JSON_PROPERTY_PROPERTY_NAME = "propertyName";
  @javax.annotation.Nullable
  private String propertyName;

  public PropertyDependency() {
  }

  public PropertyDependency dependentValues(@javax.annotation.Nullable List<String> dependentValues) {
    
    this.dependentValues = dependentValues;
    return this;
  }

  public PropertyDependency addDependentValuesItem(String dependentValuesItem) {
    if (this.dependentValues == null) {
      this.dependentValues = new ArrayList<>();
    }
    this.dependentValues.add(dependentValuesItem);
    return this;
  }

  /**
   * The values that satisfy the dependency
   * @return dependentValues
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEPENDENT_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getDependentValues() {
    return dependentValues;
  }


  @JsonProperty(JSON_PROPERTY_DEPENDENT_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDependentValues(@javax.annotation.Nullable List<String> dependentValues) {
    this.dependentValues = dependentValues;
  }

  public PropertyDependency propertyDisplayName(@javax.annotation.Nullable String propertyDisplayName) {
    
    this.propertyDisplayName = propertyDisplayName;
    return this;
  }

  /**
   * The name of the property that is depended upon
   * @return propertyDisplayName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPropertyDisplayName() {
    return propertyDisplayName;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPropertyDisplayName(@javax.annotation.Nullable String propertyDisplayName) {
    this.propertyDisplayName = propertyDisplayName;
  }

  public PropertyDependency propertyName(@javax.annotation.Nullable String propertyName) {
    
    this.propertyName = propertyName;
    return this;
  }

  /**
   * The name of the property that is depended upon
   * @return propertyName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPropertyName() {
    return propertyName;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPropertyName(@javax.annotation.Nullable String propertyName) {
    this.propertyName = propertyName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PropertyDependency propertyDependency = (PropertyDependency) o;
    return Objects.equals(this.dependentValues, propertyDependency.dependentValues) &&
        Objects.equals(this.propertyDisplayName, propertyDependency.propertyDisplayName) &&
        Objects.equals(this.propertyName, propertyDependency.propertyName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dependentValues, propertyDisplayName, propertyName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PropertyDependency {\n");
    sb.append("    dependentValues: ").append(toIndentedString(dependentValues)).append("\n");
    sb.append("    propertyDisplayName: ").append(toIndentedString(propertyDisplayName)).append("\n");
    sb.append("    propertyName: ").append(toIndentedString(propertyName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

