/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.giwi.nifi.tester.model.AttributeDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The provenance events that matched the search criteria.
 */
@JsonPropertyOrder({
  ProvenanceEventDTO.JSON_PROPERTY_ALTERNATE_IDENTIFIER_URI,
  ProvenanceEventDTO.JSON_PROPERTY_ATTRIBUTES,
  ProvenanceEventDTO.JSON_PROPERTY_CHILD_UUIDS,
  ProvenanceEventDTO.JSON_PROPERTY_CLUSTER_NODE_ADDRESS,
  ProvenanceEventDTO.JSON_PROPERTY_CLUSTER_NODE_ID,
  ProvenanceEventDTO.JSON_PROPERTY_COMPONENT_ID,
  ProvenanceEventDTO.JSON_PROPERTY_COMPONENT_NAME,
  ProvenanceEventDTO.JSON_PROPERTY_COMPONENT_TYPE,
  ProvenanceEventDTO.JSON_PROPERTY_CONNECTOR_ID,
  ProvenanceEventDTO.JSON_PROPERTY_CONTENT_EQUAL,
  ProvenanceEventDTO.JSON_PROPERTY_DETAILS,
  ProvenanceEventDTO.JSON_PROPERTY_EVENT_DURATION,
  ProvenanceEventDTO.JSON_PROPERTY_EVENT_ID,
  ProvenanceEventDTO.JSON_PROPERTY_EVENT_TIME,
  ProvenanceEventDTO.JSON_PROPERTY_EVENT_TIMESTAMP,
  ProvenanceEventDTO.JSON_PROPERTY_EVENT_TYPE,
  ProvenanceEventDTO.JSON_PROPERTY_FILE_SIZE,
  ProvenanceEventDTO.JSON_PROPERTY_FILE_SIZE_BYTES,
  ProvenanceEventDTO.JSON_PROPERTY_FLOW_FILE_UUID,
  ProvenanceEventDTO.JSON_PROPERTY_GROUP_ID,
  ProvenanceEventDTO.JSON_PROPERTY_ID,
  ProvenanceEventDTO.JSON_PROPERTY_INPUT_CONTENT_AVAILABLE,
  ProvenanceEventDTO.JSON_PROPERTY_INPUT_CONTENT_CLAIM_CONTAINER,
  ProvenanceEventDTO.JSON_PROPERTY_INPUT_CONTENT_CLAIM_FILE_SIZE,
  ProvenanceEventDTO.JSON_PROPERTY_INPUT_CONTENT_CLAIM_FILE_SIZE_BYTES,
  ProvenanceEventDTO.JSON_PROPERTY_INPUT_CONTENT_CLAIM_IDENTIFIER,
  ProvenanceEventDTO.JSON_PROPERTY_INPUT_CONTENT_CLAIM_OFFSET,
  ProvenanceEventDTO.JSON_PROPERTY_INPUT_CONTENT_CLAIM_SECTION,
  ProvenanceEventDTO.JSON_PROPERTY_LINEAGE_DURATION,
  ProvenanceEventDTO.JSON_PROPERTY_OUTPUT_CONTENT_AVAILABLE,
  ProvenanceEventDTO.JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_CONTAINER,
  ProvenanceEventDTO.JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_FILE_SIZE,
  ProvenanceEventDTO.JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_FILE_SIZE_BYTES,
  ProvenanceEventDTO.JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_IDENTIFIER,
  ProvenanceEventDTO.JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_OFFSET,
  ProvenanceEventDTO.JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_SECTION,
  ProvenanceEventDTO.JSON_PROPERTY_PARENT_UUIDS,
  ProvenanceEventDTO.JSON_PROPERTY_RELATIONSHIP,
  ProvenanceEventDTO.JSON_PROPERTY_REPLAY_AVAILABLE,
  ProvenanceEventDTO.JSON_PROPERTY_REPLAY_EXPLANATION,
  ProvenanceEventDTO.JSON_PROPERTY_SOURCE_CONNECTION_IDENTIFIER,
  ProvenanceEventDTO.JSON_PROPERTY_SOURCE_SYSTEM_FLOW_FILE_ID,
  ProvenanceEventDTO.JSON_PROPERTY_TRANSIT_URI
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ProvenanceEventDTO {
  public static final String JSON_PROPERTY_ALTERNATE_IDENTIFIER_URI = "alternateIdentifierUri";
  @javax.annotation.Nullable
  private String alternateIdentifierUri;

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  @javax.annotation.Nullable
  private List<AttributeDTO> attributes = new ArrayList<>();

  public static final String JSON_PROPERTY_CHILD_UUIDS = "childUuids";
  @javax.annotation.Nullable
  private List<String> childUuids = new ArrayList<>();

  public static final String JSON_PROPERTY_CLUSTER_NODE_ADDRESS = "clusterNodeAddress";
  @javax.annotation.Nullable
  private String clusterNodeAddress;

  public static final String JSON_PROPERTY_CLUSTER_NODE_ID = "clusterNodeId";
  @javax.annotation.Nullable
  private String clusterNodeId;

  public static final String JSON_PROPERTY_COMPONENT_ID = "componentId";
  @javax.annotation.Nullable
  private String componentId;

  public static final String JSON_PROPERTY_COMPONENT_NAME = "componentName";
  @javax.annotation.Nullable
  private String componentName;

  public static final String JSON_PROPERTY_COMPONENT_TYPE = "componentType";
  @javax.annotation.Nullable
  private String componentType;

  public static final String JSON_PROPERTY_CONNECTOR_ID = "connectorId";
  @javax.annotation.Nullable
  private String connectorId;

  public static final String JSON_PROPERTY_CONTENT_EQUAL = "contentEqual";
  @javax.annotation.Nullable
  private Boolean contentEqual;

  public static final String JSON_PROPERTY_DETAILS = "details";
  @javax.annotation.Nullable
  private String details;

  public static final String JSON_PROPERTY_EVENT_DURATION = "eventDuration";
  @javax.annotation.Nullable
  private Long eventDuration;

  public static final String JSON_PROPERTY_EVENT_ID = "eventId";
  @javax.annotation.Nullable
  private Long eventId;

  public static final String JSON_PROPERTY_EVENT_TIME = "eventTime";
  @javax.annotation.Nullable
  private String eventTime;

  public static final String JSON_PROPERTY_EVENT_TIMESTAMP = "eventTimestamp";
  @javax.annotation.Nullable
  private String eventTimestamp;

  public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
  @javax.annotation.Nullable
  private String eventType;

  public static final String JSON_PROPERTY_FILE_SIZE = "fileSize";
  @javax.annotation.Nullable
  private String fileSize;

  public static final String JSON_PROPERTY_FILE_SIZE_BYTES = "fileSizeBytes";
  @javax.annotation.Nullable
  private Long fileSizeBytes;

  public static final String JSON_PROPERTY_FLOW_FILE_UUID = "flowFileUuid";
  @javax.annotation.Nullable
  private String flowFileUuid;

  public static final String JSON_PROPERTY_GROUP_ID = "groupId";
  @javax.annotation.Nullable
  private String groupId;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_INPUT_CONTENT_AVAILABLE = "inputContentAvailable";
  @javax.annotation.Nullable
  private Boolean inputContentAvailable;

  public static final String JSON_PROPERTY_INPUT_CONTENT_CLAIM_CONTAINER = "inputContentClaimContainer";
  @javax.annotation.Nullable
  private String inputContentClaimContainer;

  public static final String JSON_PROPERTY_INPUT_CONTENT_CLAIM_FILE_SIZE = "inputContentClaimFileSize";
  @javax.annotation.Nullable
  private String inputContentClaimFileSize;

  public static final String JSON_PROPERTY_INPUT_CONTENT_CLAIM_FILE_SIZE_BYTES = "inputContentClaimFileSizeBytes";
  @javax.annotation.Nullable
  private Long inputContentClaimFileSizeBytes;

  public static final String JSON_PROPERTY_INPUT_CONTENT_CLAIM_IDENTIFIER = "inputContentClaimIdentifier";
  @javax.annotation.Nullable
  private String inputContentClaimIdentifier;

  public static final String JSON_PROPERTY_INPUT_CONTENT_CLAIM_OFFSET = "inputContentClaimOffset";
  @javax.annotation.Nullable
  private Long inputContentClaimOffset;

  public static final String JSON_PROPERTY_INPUT_CONTENT_CLAIM_SECTION = "inputContentClaimSection";
  @javax.annotation.Nullable
  private String inputContentClaimSection;

  public static final String JSON_PROPERTY_LINEAGE_DURATION = "lineageDuration";
  @javax.annotation.Nullable
  private Long lineageDuration;

  public static final String JSON_PROPERTY_OUTPUT_CONTENT_AVAILABLE = "outputContentAvailable";
  @javax.annotation.Nullable
  private Boolean outputContentAvailable;

  public static final String JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_CONTAINER = "outputContentClaimContainer";
  @javax.annotation.Nullable
  private String outputContentClaimContainer;

  public static final String JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_FILE_SIZE = "outputContentClaimFileSize";
  @javax.annotation.Nullable
  private String outputContentClaimFileSize;

  public static final String JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_FILE_SIZE_BYTES = "outputContentClaimFileSizeBytes";
  @javax.annotation.Nullable
  private Long outputContentClaimFileSizeBytes;

  public static final String JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_IDENTIFIER = "outputContentClaimIdentifier";
  @javax.annotation.Nullable
  private String outputContentClaimIdentifier;

  public static final String JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_OFFSET = "outputContentClaimOffset";
  @javax.annotation.Nullable
  private Long outputContentClaimOffset;

  public static final String JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_SECTION = "outputContentClaimSection";
  @javax.annotation.Nullable
  private String outputContentClaimSection;

  public static final String JSON_PROPERTY_PARENT_UUIDS = "parentUuids";
  @javax.annotation.Nullable
  private List<String> parentUuids = new ArrayList<>();

  public static final String JSON_PROPERTY_RELATIONSHIP = "relationship";
  @javax.annotation.Nullable
  private String relationship;

  public static final String JSON_PROPERTY_REPLAY_AVAILABLE = "replayAvailable";
  @javax.annotation.Nullable
  private Boolean replayAvailable;

  public static final String JSON_PROPERTY_REPLAY_EXPLANATION = "replayExplanation";
  @javax.annotation.Nullable
  private String replayExplanation;

  public static final String JSON_PROPERTY_SOURCE_CONNECTION_IDENTIFIER = "sourceConnectionIdentifier";
  @javax.annotation.Nullable
  private String sourceConnectionIdentifier;

  public static final String JSON_PROPERTY_SOURCE_SYSTEM_FLOW_FILE_ID = "sourceSystemFlowFileId";
  @javax.annotation.Nullable
  private String sourceSystemFlowFileId;

  public static final String JSON_PROPERTY_TRANSIT_URI = "transitUri";
  @javax.annotation.Nullable
  private String transitUri;

  public ProvenanceEventDTO() {
  }

  public ProvenanceEventDTO alternateIdentifierUri(@javax.annotation.Nullable String alternateIdentifierUri) {
    
    this.alternateIdentifierUri = alternateIdentifierUri;
    return this;
  }

  /**
   * The alternate identifier uri for the fileflow for the event.
   * @return alternateIdentifierUri
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALTERNATE_IDENTIFIER_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAlternateIdentifierUri() {
    return alternateIdentifierUri;
  }


  @JsonProperty(JSON_PROPERTY_ALTERNATE_IDENTIFIER_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlternateIdentifierUri(@javax.annotation.Nullable String alternateIdentifierUri) {
    this.alternateIdentifierUri = alternateIdentifierUri;
  }

  public ProvenanceEventDTO attributes(@javax.annotation.Nullable List<AttributeDTO> attributes) {
    
    this.attributes = attributes;
    return this;
  }

  public ProvenanceEventDTO addAttributesItem(AttributeDTO attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

  /**
   * The attributes of the flowfile for the event.
   * @return attributes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AttributeDTO> getAttributes() {
    return attributes;
  }


  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAttributes(@javax.annotation.Nullable List<AttributeDTO> attributes) {
    this.attributes = attributes;
  }

  public ProvenanceEventDTO childUuids(@javax.annotation.Nullable List<String> childUuids) {
    
    this.childUuids = childUuids;
    return this;
  }

  public ProvenanceEventDTO addChildUuidsItem(String childUuidsItem) {
    if (this.childUuids == null) {
      this.childUuids = new ArrayList<>();
    }
    this.childUuids.add(childUuidsItem);
    return this;
  }

  /**
   * The child uuids for the event.
   * @return childUuids
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHILD_UUIDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getChildUuids() {
    return childUuids;
  }


  @JsonProperty(JSON_PROPERTY_CHILD_UUIDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChildUuids(@javax.annotation.Nullable List<String> childUuids) {
    this.childUuids = childUuids;
  }

  public ProvenanceEventDTO clusterNodeAddress(@javax.annotation.Nullable String clusterNodeAddress) {
    
    this.clusterNodeAddress = clusterNodeAddress;
    return this;
  }

  /**
   * The label for the node where the event originated.
   * @return clusterNodeAddress
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLUSTER_NODE_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClusterNodeAddress() {
    return clusterNodeAddress;
  }


  @JsonProperty(JSON_PROPERTY_CLUSTER_NODE_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClusterNodeAddress(@javax.annotation.Nullable String clusterNodeAddress) {
    this.clusterNodeAddress = clusterNodeAddress;
  }

  public ProvenanceEventDTO clusterNodeId(@javax.annotation.Nullable String clusterNodeId) {
    
    this.clusterNodeId = clusterNodeId;
    return this;
  }

  /**
   * The identifier for the node where the event originated.
   * @return clusterNodeId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLUSTER_NODE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClusterNodeId() {
    return clusterNodeId;
  }


  @JsonProperty(JSON_PROPERTY_CLUSTER_NODE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClusterNodeId(@javax.annotation.Nullable String clusterNodeId) {
    this.clusterNodeId = clusterNodeId;
  }

  public ProvenanceEventDTO componentId(@javax.annotation.Nullable String componentId) {
    
    this.componentId = componentId;
    return this;
  }

  /**
   * The id of the component that generated the event.
   * @return componentId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPONENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComponentId() {
    return componentId;
  }


  @JsonProperty(JSON_PROPERTY_COMPONENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComponentId(@javax.annotation.Nullable String componentId) {
    this.componentId = componentId;
  }

  public ProvenanceEventDTO componentName(@javax.annotation.Nullable String componentName) {
    
    this.componentName = componentName;
    return this;
  }

  /**
   * The name of the component that generated the event.
   * @return componentName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPONENT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComponentName() {
    return componentName;
  }


  @JsonProperty(JSON_PROPERTY_COMPONENT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComponentName(@javax.annotation.Nullable String componentName) {
    this.componentName = componentName;
  }

  public ProvenanceEventDTO componentType(@javax.annotation.Nullable String componentType) {
    
    this.componentType = componentType;
    return this;
  }

  /**
   * The type of the component that generated the event.
   * @return componentType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPONENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComponentType() {
    return componentType;
  }


  @JsonProperty(JSON_PROPERTY_COMPONENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComponentType(@javax.annotation.Nullable String componentType) {
    this.componentType = componentType;
  }

  public ProvenanceEventDTO connectorId(@javax.annotation.Nullable String connectorId) {
    
    this.connectorId = connectorId;
    return this;
  }

  /**
   * The id of the connector that manages the component that generated the event. If the component is not managed by a connector, this will not be set.
   * @return connectorId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONNECTOR_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConnectorId() {
    return connectorId;
  }


  @JsonProperty(JSON_PROPERTY_CONNECTOR_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConnectorId(@javax.annotation.Nullable String connectorId) {
    this.connectorId = connectorId;
  }

  public ProvenanceEventDTO contentEqual(@javax.annotation.Nullable Boolean contentEqual) {
    
    this.contentEqual = contentEqual;
    return this;
  }

  /**
   * Whether the input and output content claim is the same.
   * @return contentEqual
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTENT_EQUAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getContentEqual() {
    return contentEqual;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT_EQUAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentEqual(@javax.annotation.Nullable Boolean contentEqual) {
    this.contentEqual = contentEqual;
  }

  public ProvenanceEventDTO details(@javax.annotation.Nullable String details) {
    
    this.details = details;
    return this;
  }

  /**
   * The event details.
   * @return details
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDetails() {
    return details;
  }


  @JsonProperty(JSON_PROPERTY_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetails(@javax.annotation.Nullable String details) {
    this.details = details;
  }

  public ProvenanceEventDTO eventDuration(@javax.annotation.Nullable Long eventDuration) {
    
    this.eventDuration = eventDuration;
    return this;
  }

  /**
   * The event duration in milliseconds.
   * @return eventDuration
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getEventDuration() {
    return eventDuration;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventDuration(@javax.annotation.Nullable Long eventDuration) {
    this.eventDuration = eventDuration;
  }

  public ProvenanceEventDTO eventId(@javax.annotation.Nullable Long eventId) {
    
    this.eventId = eventId;
    return this;
  }

  /**
   * The event id. This is a one up number thats unique per node.
   * @return eventId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getEventId() {
    return eventId;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventId(@javax.annotation.Nullable Long eventId) {
    this.eventId = eventId;
  }

  public ProvenanceEventDTO eventTime(@javax.annotation.Nullable String eventTime) {
    
    this.eventTime = eventTime;
    return this;
  }

  /**
   * The timestamp of the event.
   * @return eventTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEventTime() {
    return eventTime;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventTime(@javax.annotation.Nullable String eventTime) {
    this.eventTime = eventTime;
  }

  public ProvenanceEventDTO eventTimestamp(@javax.annotation.Nullable String eventTimestamp) {
    
    this.eventTimestamp = eventTimestamp;
    return this;
  }

  /**
   * Event Timestamp formatted using ISO8601
   * @return eventTimestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEventTimestamp() {
    return eventTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventTimestamp(@javax.annotation.Nullable String eventTimestamp) {
    this.eventTimestamp = eventTimestamp;
  }

  public ProvenanceEventDTO eventType(@javax.annotation.Nullable String eventType) {
    
    this.eventType = eventType;
    return this;
  }

  /**
   * The type of the event.
   * @return eventType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEventType() {
    return eventType;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventType(@javax.annotation.Nullable String eventType) {
    this.eventType = eventType;
  }

  public ProvenanceEventDTO fileSize(@javax.annotation.Nullable String fileSize) {
    
    this.fileSize = fileSize;
    return this;
  }

  /**
   * The size of the flowfile for the event.
   * @return fileSize
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFileSize() {
    return fileSize;
  }


  @JsonProperty(JSON_PROPERTY_FILE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileSize(@javax.annotation.Nullable String fileSize) {
    this.fileSize = fileSize;
  }

  public ProvenanceEventDTO fileSizeBytes(@javax.annotation.Nullable Long fileSizeBytes) {
    
    this.fileSizeBytes = fileSizeBytes;
    return this;
  }

  /**
   * The size of the flowfile in bytes for the event.
   * @return fileSizeBytes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILE_SIZE_BYTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getFileSizeBytes() {
    return fileSizeBytes;
  }


  @JsonProperty(JSON_PROPERTY_FILE_SIZE_BYTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileSizeBytes(@javax.annotation.Nullable Long fileSizeBytes) {
    this.fileSizeBytes = fileSizeBytes;
  }

  public ProvenanceEventDTO flowFileUuid(@javax.annotation.Nullable String flowFileUuid) {
    
    this.flowFileUuid = flowFileUuid;
    return this;
  }

  /**
   * The uuid of the flowfile for the event.
   * @return flowFileUuid
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLOW_FILE_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFlowFileUuid() {
    return flowFileUuid;
  }


  @JsonProperty(JSON_PROPERTY_FLOW_FILE_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowFileUuid(@javax.annotation.Nullable String flowFileUuid) {
    this.flowFileUuid = flowFileUuid;
  }

  public ProvenanceEventDTO groupId(@javax.annotation.Nullable String groupId) {
    
    this.groupId = groupId;
    return this;
  }

  /**
   * The id of the group that the component resides in. If the component is no longer in the flow, the group id will not be set.
   * @return groupId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGroupId() {
    return groupId;
  }


  @JsonProperty(JSON_PROPERTY_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupId(@javax.annotation.Nullable String groupId) {
    this.groupId = groupId;
  }

  public ProvenanceEventDTO id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * The event uuid.
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public ProvenanceEventDTO inputContentAvailable(@javax.annotation.Nullable Boolean inputContentAvailable) {
    
    this.inputContentAvailable = inputContentAvailable;
    return this;
  }

  /**
   * Whether the input content is still available.
   * @return inputContentAvailable
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPUT_CONTENT_AVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getInputContentAvailable() {
    return inputContentAvailable;
  }


  @JsonProperty(JSON_PROPERTY_INPUT_CONTENT_AVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInputContentAvailable(@javax.annotation.Nullable Boolean inputContentAvailable) {
    this.inputContentAvailable = inputContentAvailable;
  }

  public ProvenanceEventDTO inputContentClaimContainer(@javax.annotation.Nullable String inputContentClaimContainer) {
    
    this.inputContentClaimContainer = inputContentClaimContainer;
    return this;
  }

  /**
   * The container in which the input content claim lives.
   * @return inputContentClaimContainer
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPUT_CONTENT_CLAIM_CONTAINER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInputContentClaimContainer() {
    return inputContentClaimContainer;
  }


  @JsonProperty(JSON_PROPERTY_INPUT_CONTENT_CLAIM_CONTAINER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInputContentClaimContainer(@javax.annotation.Nullable String inputContentClaimContainer) {
    this.inputContentClaimContainer = inputContentClaimContainer;
  }

  public ProvenanceEventDTO inputContentClaimFileSize(@javax.annotation.Nullable String inputContentClaimFileSize) {
    
    this.inputContentClaimFileSize = inputContentClaimFileSize;
    return this;
  }

  /**
   * The file size of the input content claim formatted.
   * @return inputContentClaimFileSize
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPUT_CONTENT_CLAIM_FILE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInputContentClaimFileSize() {
    return inputContentClaimFileSize;
  }


  @JsonProperty(JSON_PROPERTY_INPUT_CONTENT_CLAIM_FILE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInputContentClaimFileSize(@javax.annotation.Nullable String inputContentClaimFileSize) {
    this.inputContentClaimFileSize = inputContentClaimFileSize;
  }

  public ProvenanceEventDTO inputContentClaimFileSizeBytes(@javax.annotation.Nullable Long inputContentClaimFileSizeBytes) {
    
    this.inputContentClaimFileSizeBytes = inputContentClaimFileSizeBytes;
    return this;
  }

  /**
   * The file size of the intput content claim in bytes.
   * @return inputContentClaimFileSizeBytes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPUT_CONTENT_CLAIM_FILE_SIZE_BYTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getInputContentClaimFileSizeBytes() {
    return inputContentClaimFileSizeBytes;
  }


  @JsonProperty(JSON_PROPERTY_INPUT_CONTENT_CLAIM_FILE_SIZE_BYTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInputContentClaimFileSizeBytes(@javax.annotation.Nullable Long inputContentClaimFileSizeBytes) {
    this.inputContentClaimFileSizeBytes = inputContentClaimFileSizeBytes;
  }

  public ProvenanceEventDTO inputContentClaimIdentifier(@javax.annotation.Nullable String inputContentClaimIdentifier) {
    
    this.inputContentClaimIdentifier = inputContentClaimIdentifier;
    return this;
  }

  /**
   * The identifier of the input content claim.
   * @return inputContentClaimIdentifier
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPUT_CONTENT_CLAIM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInputContentClaimIdentifier() {
    return inputContentClaimIdentifier;
  }


  @JsonProperty(JSON_PROPERTY_INPUT_CONTENT_CLAIM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInputContentClaimIdentifier(@javax.annotation.Nullable String inputContentClaimIdentifier) {
    this.inputContentClaimIdentifier = inputContentClaimIdentifier;
  }

  public ProvenanceEventDTO inputContentClaimOffset(@javax.annotation.Nullable Long inputContentClaimOffset) {
    
    this.inputContentClaimOffset = inputContentClaimOffset;
    return this;
  }

  /**
   * The offset into the input content claim where the FlowFiles content begins.
   * @return inputContentClaimOffset
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPUT_CONTENT_CLAIM_OFFSET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getInputContentClaimOffset() {
    return inputContentClaimOffset;
  }


  @JsonProperty(JSON_PROPERTY_INPUT_CONTENT_CLAIM_OFFSET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInputContentClaimOffset(@javax.annotation.Nullable Long inputContentClaimOffset) {
    this.inputContentClaimOffset = inputContentClaimOffset;
  }

  public ProvenanceEventDTO inputContentClaimSection(@javax.annotation.Nullable String inputContentClaimSection) {
    
    this.inputContentClaimSection = inputContentClaimSection;
    return this;
  }

  /**
   * The section in which the input content claim lives.
   * @return inputContentClaimSection
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPUT_CONTENT_CLAIM_SECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInputContentClaimSection() {
    return inputContentClaimSection;
  }


  @JsonProperty(JSON_PROPERTY_INPUT_CONTENT_CLAIM_SECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInputContentClaimSection(@javax.annotation.Nullable String inputContentClaimSection) {
    this.inputContentClaimSection = inputContentClaimSection;
  }

  public ProvenanceEventDTO lineageDuration(@javax.annotation.Nullable Long lineageDuration) {
    
    this.lineageDuration = lineageDuration;
    return this;
  }

  /**
   * The duration since the lineage began, in milliseconds.
   * @return lineageDuration
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINEAGE_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLineageDuration() {
    return lineageDuration;
  }


  @JsonProperty(JSON_PROPERTY_LINEAGE_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLineageDuration(@javax.annotation.Nullable Long lineageDuration) {
    this.lineageDuration = lineageDuration;
  }

  public ProvenanceEventDTO outputContentAvailable(@javax.annotation.Nullable Boolean outputContentAvailable) {
    
    this.outputContentAvailable = outputContentAvailable;
    return this;
  }

  /**
   * Whether the output content is still available.
   * @return outputContentAvailable
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OUTPUT_CONTENT_AVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOutputContentAvailable() {
    return outputContentAvailable;
  }


  @JsonProperty(JSON_PROPERTY_OUTPUT_CONTENT_AVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutputContentAvailable(@javax.annotation.Nullable Boolean outputContentAvailable) {
    this.outputContentAvailable = outputContentAvailable;
  }

  public ProvenanceEventDTO outputContentClaimContainer(@javax.annotation.Nullable String outputContentClaimContainer) {
    
    this.outputContentClaimContainer = outputContentClaimContainer;
    return this;
  }

  /**
   * The container in which the output content claim lives.
   * @return outputContentClaimContainer
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_CONTAINER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOutputContentClaimContainer() {
    return outputContentClaimContainer;
  }


  @JsonProperty(JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_CONTAINER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutputContentClaimContainer(@javax.annotation.Nullable String outputContentClaimContainer) {
    this.outputContentClaimContainer = outputContentClaimContainer;
  }

  public ProvenanceEventDTO outputContentClaimFileSize(@javax.annotation.Nullable String outputContentClaimFileSize) {
    
    this.outputContentClaimFileSize = outputContentClaimFileSize;
    return this;
  }

  /**
   * The file size of the output content claim formatted.
   * @return outputContentClaimFileSize
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_FILE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOutputContentClaimFileSize() {
    return outputContentClaimFileSize;
  }


  @JsonProperty(JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_FILE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutputContentClaimFileSize(@javax.annotation.Nullable String outputContentClaimFileSize) {
    this.outputContentClaimFileSize = outputContentClaimFileSize;
  }

  public ProvenanceEventDTO outputContentClaimFileSizeBytes(@javax.annotation.Nullable Long outputContentClaimFileSizeBytes) {
    
    this.outputContentClaimFileSizeBytes = outputContentClaimFileSizeBytes;
    return this;
  }

  /**
   * The file size of the output content claim in bytes.
   * @return outputContentClaimFileSizeBytes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_FILE_SIZE_BYTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getOutputContentClaimFileSizeBytes() {
    return outputContentClaimFileSizeBytes;
  }


  @JsonProperty(JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_FILE_SIZE_BYTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutputContentClaimFileSizeBytes(@javax.annotation.Nullable Long outputContentClaimFileSizeBytes) {
    this.outputContentClaimFileSizeBytes = outputContentClaimFileSizeBytes;
  }

  public ProvenanceEventDTO outputContentClaimIdentifier(@javax.annotation.Nullable String outputContentClaimIdentifier) {
    
    this.outputContentClaimIdentifier = outputContentClaimIdentifier;
    return this;
  }

  /**
   * The identifier of the output content claim.
   * @return outputContentClaimIdentifier
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOutputContentClaimIdentifier() {
    return outputContentClaimIdentifier;
  }


  @JsonProperty(JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutputContentClaimIdentifier(@javax.annotation.Nullable String outputContentClaimIdentifier) {
    this.outputContentClaimIdentifier = outputContentClaimIdentifier;
  }

  public ProvenanceEventDTO outputContentClaimOffset(@javax.annotation.Nullable Long outputContentClaimOffset) {
    
    this.outputContentClaimOffset = outputContentClaimOffset;
    return this;
  }

  /**
   * The offset into the output content claim where the FlowFiles content begins.
   * @return outputContentClaimOffset
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_OFFSET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getOutputContentClaimOffset() {
    return outputContentClaimOffset;
  }


  @JsonProperty(JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_OFFSET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutputContentClaimOffset(@javax.annotation.Nullable Long outputContentClaimOffset) {
    this.outputContentClaimOffset = outputContentClaimOffset;
  }

  public ProvenanceEventDTO outputContentClaimSection(@javax.annotation.Nullable String outputContentClaimSection) {
    
    this.outputContentClaimSection = outputContentClaimSection;
    return this;
  }

  /**
   * The section in which the output content claim lives.
   * @return outputContentClaimSection
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_SECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOutputContentClaimSection() {
    return outputContentClaimSection;
  }


  @JsonProperty(JSON_PROPERTY_OUTPUT_CONTENT_CLAIM_SECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutputContentClaimSection(@javax.annotation.Nullable String outputContentClaimSection) {
    this.outputContentClaimSection = outputContentClaimSection;
  }

  public ProvenanceEventDTO parentUuids(@javax.annotation.Nullable List<String> parentUuids) {
    
    this.parentUuids = parentUuids;
    return this;
  }

  public ProvenanceEventDTO addParentUuidsItem(String parentUuidsItem) {
    if (this.parentUuids == null) {
      this.parentUuids = new ArrayList<>();
    }
    this.parentUuids.add(parentUuidsItem);
    return this;
  }

  /**
   * The parent uuids for the event.
   * @return parentUuids
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARENT_UUIDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getParentUuids() {
    return parentUuids;
  }


  @JsonProperty(JSON_PROPERTY_PARENT_UUIDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParentUuids(@javax.annotation.Nullable List<String> parentUuids) {
    this.parentUuids = parentUuids;
  }

  public ProvenanceEventDTO relationship(@javax.annotation.Nullable String relationship) {
    
    this.relationship = relationship;
    return this;
  }

  /**
   * The relationship to which the flowfile was routed if the event is of type ROUTE.
   * @return relationship
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATIONSHIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelationship() {
    return relationship;
  }


  @JsonProperty(JSON_PROPERTY_RELATIONSHIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelationship(@javax.annotation.Nullable String relationship) {
    this.relationship = relationship;
  }

  public ProvenanceEventDTO replayAvailable(@javax.annotation.Nullable Boolean replayAvailable) {
    
    this.replayAvailable = replayAvailable;
    return this;
  }

  /**
   * Whether or not replay is available.
   * @return replayAvailable
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPLAY_AVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getReplayAvailable() {
    return replayAvailable;
  }


  @JsonProperty(JSON_PROPERTY_REPLAY_AVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplayAvailable(@javax.annotation.Nullable Boolean replayAvailable) {
    this.replayAvailable = replayAvailable;
  }

  public ProvenanceEventDTO replayExplanation(@javax.annotation.Nullable String replayExplanation) {
    
    this.replayExplanation = replayExplanation;
    return this;
  }

  /**
   * Explanation as to why replay is unavailable.
   * @return replayExplanation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPLAY_EXPLANATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReplayExplanation() {
    return replayExplanation;
  }


  @JsonProperty(JSON_PROPERTY_REPLAY_EXPLANATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplayExplanation(@javax.annotation.Nullable String replayExplanation) {
    this.replayExplanation = replayExplanation;
  }

  public ProvenanceEventDTO sourceConnectionIdentifier(@javax.annotation.Nullable String sourceConnectionIdentifier) {
    
    this.sourceConnectionIdentifier = sourceConnectionIdentifier;
    return this;
  }

  /**
   * The identifier of the queue/connection from which the flowfile was pulled to genereate this event. May be null if the queue/connection is unknown or the flowfile was generated from this event.
   * @return sourceConnectionIdentifier
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE_CONNECTION_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceConnectionIdentifier() {
    return sourceConnectionIdentifier;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_CONNECTION_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceConnectionIdentifier(@javax.annotation.Nullable String sourceConnectionIdentifier) {
    this.sourceConnectionIdentifier = sourceConnectionIdentifier;
  }

  public ProvenanceEventDTO sourceSystemFlowFileId(@javax.annotation.Nullable String sourceSystemFlowFileId) {
    
    this.sourceSystemFlowFileId = sourceSystemFlowFileId;
    return this;
  }

  /**
   * The source system flowfile id.
   * @return sourceSystemFlowFileId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE_SYSTEM_FLOW_FILE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceSystemFlowFileId() {
    return sourceSystemFlowFileId;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_SYSTEM_FLOW_FILE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceSystemFlowFileId(@javax.annotation.Nullable String sourceSystemFlowFileId) {
    this.sourceSystemFlowFileId = sourceSystemFlowFileId;
  }

  public ProvenanceEventDTO transitUri(@javax.annotation.Nullable String transitUri) {
    
    this.transitUri = transitUri;
    return this;
  }

  /**
   * The source/destination system uri if the event was a RECEIVE/SEND.
   * @return transitUri
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSIT_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransitUri() {
    return transitUri;
  }


  @JsonProperty(JSON_PROPERTY_TRANSIT_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransitUri(@javax.annotation.Nullable String transitUri) {
    this.transitUri = transitUri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProvenanceEventDTO provenanceEventDTO = (ProvenanceEventDTO) o;
    return Objects.equals(this.alternateIdentifierUri, provenanceEventDTO.alternateIdentifierUri) &&
        Objects.equals(this.attributes, provenanceEventDTO.attributes) &&
        Objects.equals(this.childUuids, provenanceEventDTO.childUuids) &&
        Objects.equals(this.clusterNodeAddress, provenanceEventDTO.clusterNodeAddress) &&
        Objects.equals(this.clusterNodeId, provenanceEventDTO.clusterNodeId) &&
        Objects.equals(this.componentId, provenanceEventDTO.componentId) &&
        Objects.equals(this.componentName, provenanceEventDTO.componentName) &&
        Objects.equals(this.componentType, provenanceEventDTO.componentType) &&
        Objects.equals(this.connectorId, provenanceEventDTO.connectorId) &&
        Objects.equals(this.contentEqual, provenanceEventDTO.contentEqual) &&
        Objects.equals(this.details, provenanceEventDTO.details) &&
        Objects.equals(this.eventDuration, provenanceEventDTO.eventDuration) &&
        Objects.equals(this.eventId, provenanceEventDTO.eventId) &&
        Objects.equals(this.eventTime, provenanceEventDTO.eventTime) &&
        Objects.equals(this.eventTimestamp, provenanceEventDTO.eventTimestamp) &&
        Objects.equals(this.eventType, provenanceEventDTO.eventType) &&
        Objects.equals(this.fileSize, provenanceEventDTO.fileSize) &&
        Objects.equals(this.fileSizeBytes, provenanceEventDTO.fileSizeBytes) &&
        Objects.equals(this.flowFileUuid, provenanceEventDTO.flowFileUuid) &&
        Objects.equals(this.groupId, provenanceEventDTO.groupId) &&
        Objects.equals(this.id, provenanceEventDTO.id) &&
        Objects.equals(this.inputContentAvailable, provenanceEventDTO.inputContentAvailable) &&
        Objects.equals(this.inputContentClaimContainer, provenanceEventDTO.inputContentClaimContainer) &&
        Objects.equals(this.inputContentClaimFileSize, provenanceEventDTO.inputContentClaimFileSize) &&
        Objects.equals(this.inputContentClaimFileSizeBytes, provenanceEventDTO.inputContentClaimFileSizeBytes) &&
        Objects.equals(this.inputContentClaimIdentifier, provenanceEventDTO.inputContentClaimIdentifier) &&
        Objects.equals(this.inputContentClaimOffset, provenanceEventDTO.inputContentClaimOffset) &&
        Objects.equals(this.inputContentClaimSection, provenanceEventDTO.inputContentClaimSection) &&
        Objects.equals(this.lineageDuration, provenanceEventDTO.lineageDuration) &&
        Objects.equals(this.outputContentAvailable, provenanceEventDTO.outputContentAvailable) &&
        Objects.equals(this.outputContentClaimContainer, provenanceEventDTO.outputContentClaimContainer) &&
        Objects.equals(this.outputContentClaimFileSize, provenanceEventDTO.outputContentClaimFileSize) &&
        Objects.equals(this.outputContentClaimFileSizeBytes, provenanceEventDTO.outputContentClaimFileSizeBytes) &&
        Objects.equals(this.outputContentClaimIdentifier, provenanceEventDTO.outputContentClaimIdentifier) &&
        Objects.equals(this.outputContentClaimOffset, provenanceEventDTO.outputContentClaimOffset) &&
        Objects.equals(this.outputContentClaimSection, provenanceEventDTO.outputContentClaimSection) &&
        Objects.equals(this.parentUuids, provenanceEventDTO.parentUuids) &&
        Objects.equals(this.relationship, provenanceEventDTO.relationship) &&
        Objects.equals(this.replayAvailable, provenanceEventDTO.replayAvailable) &&
        Objects.equals(this.replayExplanation, provenanceEventDTO.replayExplanation) &&
        Objects.equals(this.sourceConnectionIdentifier, provenanceEventDTO.sourceConnectionIdentifier) &&
        Objects.equals(this.sourceSystemFlowFileId, provenanceEventDTO.sourceSystemFlowFileId) &&
        Objects.equals(this.transitUri, provenanceEventDTO.transitUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alternateIdentifierUri, attributes, childUuids, clusterNodeAddress, clusterNodeId, componentId, componentName, componentType, connectorId, contentEqual, details, eventDuration, eventId, eventTime, eventTimestamp, eventType, fileSize, fileSizeBytes, flowFileUuid, groupId, id, inputContentAvailable, inputContentClaimContainer, inputContentClaimFileSize, inputContentClaimFileSizeBytes, inputContentClaimIdentifier, inputContentClaimOffset, inputContentClaimSection, lineageDuration, outputContentAvailable, outputContentClaimContainer, outputContentClaimFileSize, outputContentClaimFileSizeBytes, outputContentClaimIdentifier, outputContentClaimOffset, outputContentClaimSection, parentUuids, relationship, replayAvailable, replayExplanation, sourceConnectionIdentifier, sourceSystemFlowFileId, transitUri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProvenanceEventDTO {\n");
    sb.append("    alternateIdentifierUri: ").append(toIndentedString(alternateIdentifierUri)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    childUuids: ").append(toIndentedString(childUuids)).append("\n");
    sb.append("    clusterNodeAddress: ").append(toIndentedString(clusterNodeAddress)).append("\n");
    sb.append("    clusterNodeId: ").append(toIndentedString(clusterNodeId)).append("\n");
    sb.append("    componentId: ").append(toIndentedString(componentId)).append("\n");
    sb.append("    componentName: ").append(toIndentedString(componentName)).append("\n");
    sb.append("    componentType: ").append(toIndentedString(componentType)).append("\n");
    sb.append("    connectorId: ").append(toIndentedString(connectorId)).append("\n");
    sb.append("    contentEqual: ").append(toIndentedString(contentEqual)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    eventDuration: ").append(toIndentedString(eventDuration)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    eventTime: ").append(toIndentedString(eventTime)).append("\n");
    sb.append("    eventTimestamp: ").append(toIndentedString(eventTimestamp)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    fileSize: ").append(toIndentedString(fileSize)).append("\n");
    sb.append("    fileSizeBytes: ").append(toIndentedString(fileSizeBytes)).append("\n");
    sb.append("    flowFileUuid: ").append(toIndentedString(flowFileUuid)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    inputContentAvailable: ").append(toIndentedString(inputContentAvailable)).append("\n");
    sb.append("    inputContentClaimContainer: ").append(toIndentedString(inputContentClaimContainer)).append("\n");
    sb.append("    inputContentClaimFileSize: ").append(toIndentedString(inputContentClaimFileSize)).append("\n");
    sb.append("    inputContentClaimFileSizeBytes: ").append(toIndentedString(inputContentClaimFileSizeBytes)).append("\n");
    sb.append("    inputContentClaimIdentifier: ").append(toIndentedString(inputContentClaimIdentifier)).append("\n");
    sb.append("    inputContentClaimOffset: ").append(toIndentedString(inputContentClaimOffset)).append("\n");
    sb.append("    inputContentClaimSection: ").append(toIndentedString(inputContentClaimSection)).append("\n");
    sb.append("    lineageDuration: ").append(toIndentedString(lineageDuration)).append("\n");
    sb.append("    outputContentAvailable: ").append(toIndentedString(outputContentAvailable)).append("\n");
    sb.append("    outputContentClaimContainer: ").append(toIndentedString(outputContentClaimContainer)).append("\n");
    sb.append("    outputContentClaimFileSize: ").append(toIndentedString(outputContentClaimFileSize)).append("\n");
    sb.append("    outputContentClaimFileSizeBytes: ").append(toIndentedString(outputContentClaimFileSizeBytes)).append("\n");
    sb.append("    outputContentClaimIdentifier: ").append(toIndentedString(outputContentClaimIdentifier)).append("\n");
    sb.append("    outputContentClaimOffset: ").append(toIndentedString(outputContentClaimOffset)).append("\n");
    sb.append("    outputContentClaimSection: ").append(toIndentedString(outputContentClaimSection)).append("\n");
    sb.append("    parentUuids: ").append(toIndentedString(parentUuids)).append("\n");
    sb.append("    relationship: ").append(toIndentedString(relationship)).append("\n");
    sb.append("    replayAvailable: ").append(toIndentedString(replayAvailable)).append("\n");
    sb.append("    replayExplanation: ").append(toIndentedString(replayExplanation)).append("\n");
    sb.append("    sourceConnectionIdentifier: ").append(toIndentedString(sourceConnectionIdentifier)).append("\n");
    sb.append("    sourceSystemFlowFileId: ").append(toIndentedString(sourceSystemFlowFileId)).append("\n");
    sb.append("    transitUri: ").append(toIndentedString(transitUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

