/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RegisteredFlowSnapshotMetadata
 */
@JsonPropertyOrder({
  RegisteredFlowSnapshotMetadata.JSON_PROPERTY_AUTHOR,
  RegisteredFlowSnapshotMetadata.JSON_PROPERTY_BRANCH,
  RegisteredFlowSnapshotMetadata.JSON_PROPERTY_BUCKET_IDENTIFIER,
  RegisteredFlowSnapshotMetadata.JSON_PROPERTY_COMMENTS,
  RegisteredFlowSnapshotMetadata.JSON_PROPERTY_FLOW_IDENTIFIER,
  RegisteredFlowSnapshotMetadata.JSON_PROPERTY_FLOW_NAME,
  RegisteredFlowSnapshotMetadata.JSON_PROPERTY_REGISTRY_IDENTIFIER,
  RegisteredFlowSnapshotMetadata.JSON_PROPERTY_REGISTRY_NAME,
  RegisteredFlowSnapshotMetadata.JSON_PROPERTY_TIMESTAMP,
  RegisteredFlowSnapshotMetadata.JSON_PROPERTY_VERSION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class RegisteredFlowSnapshotMetadata {
  public static final String JSON_PROPERTY_AUTHOR = "author";
  @javax.annotation.Nullable
  private String author;

  public static final String JSON_PROPERTY_BRANCH = "branch";
  @javax.annotation.Nullable
  private String branch;

  public static final String JSON_PROPERTY_BUCKET_IDENTIFIER = "bucketIdentifier";
  @javax.annotation.Nullable
  private String bucketIdentifier;

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  @javax.annotation.Nullable
  private String comments;

  public static final String JSON_PROPERTY_FLOW_IDENTIFIER = "flowIdentifier";
  @javax.annotation.Nullable
  private String flowIdentifier;

  public static final String JSON_PROPERTY_FLOW_NAME = "flowName";
  @javax.annotation.Nullable
  private String flowName;

  public static final String JSON_PROPERTY_REGISTRY_IDENTIFIER = "registryIdentifier";
  @javax.annotation.Nullable
  private String registryIdentifier;

  public static final String JSON_PROPERTY_REGISTRY_NAME = "registryName";
  @javax.annotation.Nullable
  private String registryName;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nullable
  private Long timestamp;

  public static final String JSON_PROPERTY_VERSION = "version";
  @javax.annotation.Nullable
  private String version;

  public RegisteredFlowSnapshotMetadata() {
  }

  public RegisteredFlowSnapshotMetadata author(@javax.annotation.Nullable String author) {
    
    this.author = author;
    return this;
  }

  /**
   * Get author
   * @return author
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuthor() {
    return author;
  }


  @JsonProperty(JSON_PROPERTY_AUTHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthor(@javax.annotation.Nullable String author) {
    this.author = author;
  }

  public RegisteredFlowSnapshotMetadata branch(@javax.annotation.Nullable String branch) {
    
    this.branch = branch;
    return this;
  }

  /**
   * Get branch
   * @return branch
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BRANCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBranch() {
    return branch;
  }


  @JsonProperty(JSON_PROPERTY_BRANCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBranch(@javax.annotation.Nullable String branch) {
    this.branch = branch;
  }

  public RegisteredFlowSnapshotMetadata bucketIdentifier(@javax.annotation.Nullable String bucketIdentifier) {
    
    this.bucketIdentifier = bucketIdentifier;
    return this;
  }

  /**
   * Get bucketIdentifier
   * @return bucketIdentifier
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUCKET_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBucketIdentifier() {
    return bucketIdentifier;
  }


  @JsonProperty(JSON_PROPERTY_BUCKET_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBucketIdentifier(@javax.annotation.Nullable String bucketIdentifier) {
    this.bucketIdentifier = bucketIdentifier;
  }

  public RegisteredFlowSnapshotMetadata comments(@javax.annotation.Nullable String comments) {
    
    this.comments = comments;
    return this;
  }

  /**
   * Get comments
   * @return comments
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComments() {
    return comments;
  }


  @JsonProperty(JSON_PROPERTY_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
  }

  public RegisteredFlowSnapshotMetadata flowIdentifier(@javax.annotation.Nullable String flowIdentifier) {
    
    this.flowIdentifier = flowIdentifier;
    return this;
  }

  /**
   * Get flowIdentifier
   * @return flowIdentifier
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLOW_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFlowIdentifier() {
    return flowIdentifier;
  }


  @JsonProperty(JSON_PROPERTY_FLOW_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowIdentifier(@javax.annotation.Nullable String flowIdentifier) {
    this.flowIdentifier = flowIdentifier;
  }

  public RegisteredFlowSnapshotMetadata flowName(@javax.annotation.Nullable String flowName) {
    
    this.flowName = flowName;
    return this;
  }

  /**
   * Get flowName
   * @return flowName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLOW_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFlowName() {
    return flowName;
  }


  @JsonProperty(JSON_PROPERTY_FLOW_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowName(@javax.annotation.Nullable String flowName) {
    this.flowName = flowName;
  }

  public RegisteredFlowSnapshotMetadata registryIdentifier(@javax.annotation.Nullable String registryIdentifier) {
    
    this.registryIdentifier = registryIdentifier;
    return this;
  }

  /**
   * Get registryIdentifier
   * @return registryIdentifier
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REGISTRY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRegistryIdentifier() {
    return registryIdentifier;
  }


  @JsonProperty(JSON_PROPERTY_REGISTRY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegistryIdentifier(@javax.annotation.Nullable String registryIdentifier) {
    this.registryIdentifier = registryIdentifier;
  }

  public RegisteredFlowSnapshotMetadata registryName(@javax.annotation.Nullable String registryName) {
    
    this.registryName = registryName;
    return this;
  }

  /**
   * Get registryName
   * @return registryName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REGISTRY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRegistryName() {
    return registryName;
  }


  @JsonProperty(JSON_PROPERTY_REGISTRY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegistryName(@javax.annotation.Nullable String registryName) {
    this.registryName = registryName;
  }

  public RegisteredFlowSnapshotMetadata timestamp(@javax.annotation.Nullable Long timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@javax.annotation.Nullable Long timestamp) {
    this.timestamp = timestamp;
  }

  public RegisteredFlowSnapshotMetadata version(@javax.annotation.Nullable String version) {
    
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(@javax.annotation.Nullable String version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegisteredFlowSnapshotMetadata registeredFlowSnapshotMetadata = (RegisteredFlowSnapshotMetadata) o;
    return Objects.equals(this.author, registeredFlowSnapshotMetadata.author) &&
        Objects.equals(this.branch, registeredFlowSnapshotMetadata.branch) &&
        Objects.equals(this.bucketIdentifier, registeredFlowSnapshotMetadata.bucketIdentifier) &&
        Objects.equals(this.comments, registeredFlowSnapshotMetadata.comments) &&
        Objects.equals(this.flowIdentifier, registeredFlowSnapshotMetadata.flowIdentifier) &&
        Objects.equals(this.flowName, registeredFlowSnapshotMetadata.flowName) &&
        Objects.equals(this.registryIdentifier, registeredFlowSnapshotMetadata.registryIdentifier) &&
        Objects.equals(this.registryName, registeredFlowSnapshotMetadata.registryName) &&
        Objects.equals(this.timestamp, registeredFlowSnapshotMetadata.timestamp) &&
        Objects.equals(this.version, registeredFlowSnapshotMetadata.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(author, branch, bucketIdentifier, comments, flowIdentifier, flowName, registryIdentifier, registryName, timestamp, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegisteredFlowSnapshotMetadata {\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    branch: ").append(toIndentedString(branch)).append("\n");
    sb.append("    bucketIdentifier: ").append(toIndentedString(bucketIdentifier)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    flowIdentifier: ").append(toIndentedString(flowIdentifier)).append("\n");
    sb.append("    flowName: ").append(toIndentedString(flowName)).append("\n");
    sb.append("    registryIdentifier: ").append(toIndentedString(registryIdentifier)).append("\n");
    sb.append("    registryName: ").append(toIndentedString(registryName)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

