/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import org.giwi.nifi.tester.model.ExternalControllerServiceReference;
import org.giwi.nifi.tester.model.FlowRegistryBucket;
import org.giwi.nifi.tester.model.ParameterProviderReference;
import org.giwi.nifi.tester.model.RegisteredFlow;
import org.giwi.nifi.tester.model.RegisteredFlowSnapshotMetadata;
import org.giwi.nifi.tester.model.VersionedParameterContext;
import org.giwi.nifi.tester.model.VersionedProcessGroup;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RegisteredFlowSnapshot
 */
@JsonPropertyOrder({
  RegisteredFlowSnapshot.JSON_PROPERTY_BUCKET,
  RegisteredFlowSnapshot.JSON_PROPERTY_EXTERNAL_CONTROLLER_SERVICES,
  RegisteredFlowSnapshot.JSON_PROPERTY_FLOW,
  RegisteredFlowSnapshot.JSON_PROPERTY_FLOW_CONTENTS,
  RegisteredFlowSnapshot.JSON_PROPERTY_FLOW_ENCODING_VERSION,
  RegisteredFlowSnapshot.JSON_PROPERTY_LATEST,
  RegisteredFlowSnapshot.JSON_PROPERTY_PARAMETER_CONTEXTS,
  RegisteredFlowSnapshot.JSON_PROPERTY_PARAMETER_PROVIDERS,
  RegisteredFlowSnapshot.JSON_PROPERTY_SNAPSHOT_METADATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class RegisteredFlowSnapshot {
  public static final String JSON_PROPERTY_BUCKET = "bucket";
  @javax.annotation.Nullable
  private FlowRegistryBucket bucket;

  public static final String JSON_PROPERTY_EXTERNAL_CONTROLLER_SERVICES = "externalControllerServices";
  @javax.annotation.Nullable
  private Map<String, ExternalControllerServiceReference> externalControllerServices = new HashMap<>();

  public static final String JSON_PROPERTY_FLOW = "flow";
  @javax.annotation.Nullable
  private RegisteredFlow flow;

  public static final String JSON_PROPERTY_FLOW_CONTENTS = "flowContents";
  @javax.annotation.Nullable
  private VersionedProcessGroup flowContents;

  public static final String JSON_PROPERTY_FLOW_ENCODING_VERSION = "flowEncodingVersion";
  @javax.annotation.Nullable
  private String flowEncodingVersion;

  public static final String JSON_PROPERTY_LATEST = "latest";
  @javax.annotation.Nullable
  private Boolean latest;

  public static final String JSON_PROPERTY_PARAMETER_CONTEXTS = "parameterContexts";
  @javax.annotation.Nullable
  private Map<String, VersionedParameterContext> parameterContexts = new HashMap<>();

  public static final String JSON_PROPERTY_PARAMETER_PROVIDERS = "parameterProviders";
  @javax.annotation.Nullable
  private Map<String, ParameterProviderReference> parameterProviders = new HashMap<>();

  public static final String JSON_PROPERTY_SNAPSHOT_METADATA = "snapshotMetadata";
  @javax.annotation.Nullable
  private RegisteredFlowSnapshotMetadata snapshotMetadata;

  public RegisteredFlowSnapshot() {
  }

  public RegisteredFlowSnapshot bucket(@javax.annotation.Nullable FlowRegistryBucket bucket) {
    
    this.bucket = bucket;
    return this;
  }

  /**
   * Get bucket
   * @return bucket
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUCKET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FlowRegistryBucket getBucket() {
    return bucket;
  }


  @JsonProperty(JSON_PROPERTY_BUCKET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBucket(@javax.annotation.Nullable FlowRegistryBucket bucket) {
    this.bucket = bucket;
  }

  public RegisteredFlowSnapshot externalControllerServices(@javax.annotation.Nullable Map<String, ExternalControllerServiceReference> externalControllerServices) {
    
    this.externalControllerServices = externalControllerServices;
    return this;
  }

  public RegisteredFlowSnapshot putExternalControllerServicesItem(String key, ExternalControllerServiceReference externalControllerServicesItem) {
    if (this.externalControllerServices == null) {
      this.externalControllerServices = new HashMap<>();
    }
    this.externalControllerServices.put(key, externalControllerServicesItem);
    return this;
  }

  /**
   * Get externalControllerServices
   * @return externalControllerServices
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTERNAL_CONTROLLER_SERVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, ExternalControllerServiceReference> getExternalControllerServices() {
    return externalControllerServices;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_CONTROLLER_SERVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalControllerServices(@javax.annotation.Nullable Map<String, ExternalControllerServiceReference> externalControllerServices) {
    this.externalControllerServices = externalControllerServices;
  }

  public RegisteredFlowSnapshot flow(@javax.annotation.Nullable RegisteredFlow flow) {
    
    this.flow = flow;
    return this;
  }

  /**
   * Get flow
   * @return flow
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RegisteredFlow getFlow() {
    return flow;
  }


  @JsonProperty(JSON_PROPERTY_FLOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlow(@javax.annotation.Nullable RegisteredFlow flow) {
    this.flow = flow;
  }

  public RegisteredFlowSnapshot flowContents(@javax.annotation.Nullable VersionedProcessGroup flowContents) {
    
    this.flowContents = flowContents;
    return this;
  }

  /**
   * Get flowContents
   * @return flowContents
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLOW_CONTENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VersionedProcessGroup getFlowContents() {
    return flowContents;
  }


  @JsonProperty(JSON_PROPERTY_FLOW_CONTENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowContents(@javax.annotation.Nullable VersionedProcessGroup flowContents) {
    this.flowContents = flowContents;
  }

  public RegisteredFlowSnapshot flowEncodingVersion(@javax.annotation.Nullable String flowEncodingVersion) {
    
    this.flowEncodingVersion = flowEncodingVersion;
    return this;
  }

  /**
   * Get flowEncodingVersion
   * @return flowEncodingVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLOW_ENCODING_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFlowEncodingVersion() {
    return flowEncodingVersion;
  }


  @JsonProperty(JSON_PROPERTY_FLOW_ENCODING_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowEncodingVersion(@javax.annotation.Nullable String flowEncodingVersion) {
    this.flowEncodingVersion = flowEncodingVersion;
  }

  public RegisteredFlowSnapshot latest(@javax.annotation.Nullable Boolean latest) {
    
    this.latest = latest;
    return this;
  }

  /**
   * Get latest
   * @return latest
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LATEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLatest() {
    return latest;
  }


  @JsonProperty(JSON_PROPERTY_LATEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatest(@javax.annotation.Nullable Boolean latest) {
    this.latest = latest;
  }

  public RegisteredFlowSnapshot parameterContexts(@javax.annotation.Nullable Map<String, VersionedParameterContext> parameterContexts) {
    
    this.parameterContexts = parameterContexts;
    return this;
  }

  public RegisteredFlowSnapshot putParameterContextsItem(String key, VersionedParameterContext parameterContextsItem) {
    if (this.parameterContexts == null) {
      this.parameterContexts = new HashMap<>();
    }
    this.parameterContexts.put(key, parameterContextsItem);
    return this;
  }

  /**
   * Get parameterContexts
   * @return parameterContexts
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARAMETER_CONTEXTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, VersionedParameterContext> getParameterContexts() {
    return parameterContexts;
  }


  @JsonProperty(JSON_PROPERTY_PARAMETER_CONTEXTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParameterContexts(@javax.annotation.Nullable Map<String, VersionedParameterContext> parameterContexts) {
    this.parameterContexts = parameterContexts;
  }

  public RegisteredFlowSnapshot parameterProviders(@javax.annotation.Nullable Map<String, ParameterProviderReference> parameterProviders) {
    
    this.parameterProviders = parameterProviders;
    return this;
  }

  public RegisteredFlowSnapshot putParameterProvidersItem(String key, ParameterProviderReference parameterProvidersItem) {
    if (this.parameterProviders == null) {
      this.parameterProviders = new HashMap<>();
    }
    this.parameterProviders.put(key, parameterProvidersItem);
    return this;
  }

  /**
   * Get parameterProviders
   * @return parameterProviders
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARAMETER_PROVIDERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, ParameterProviderReference> getParameterProviders() {
    return parameterProviders;
  }


  @JsonProperty(JSON_PROPERTY_PARAMETER_PROVIDERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParameterProviders(@javax.annotation.Nullable Map<String, ParameterProviderReference> parameterProviders) {
    this.parameterProviders = parameterProviders;
  }

  public RegisteredFlowSnapshot snapshotMetadata(@javax.annotation.Nullable RegisteredFlowSnapshotMetadata snapshotMetadata) {
    
    this.snapshotMetadata = snapshotMetadata;
    return this;
  }

  /**
   * Get snapshotMetadata
   * @return snapshotMetadata
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SNAPSHOT_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RegisteredFlowSnapshotMetadata getSnapshotMetadata() {
    return snapshotMetadata;
  }


  @JsonProperty(JSON_PROPERTY_SNAPSHOT_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSnapshotMetadata(@javax.annotation.Nullable RegisteredFlowSnapshotMetadata snapshotMetadata) {
    this.snapshotMetadata = snapshotMetadata;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegisteredFlowSnapshot registeredFlowSnapshot = (RegisteredFlowSnapshot) o;
    return Objects.equals(this.bucket, registeredFlowSnapshot.bucket) &&
        Objects.equals(this.externalControllerServices, registeredFlowSnapshot.externalControllerServices) &&
        Objects.equals(this.flow, registeredFlowSnapshot.flow) &&
        Objects.equals(this.flowContents, registeredFlowSnapshot.flowContents) &&
        Objects.equals(this.flowEncodingVersion, registeredFlowSnapshot.flowEncodingVersion) &&
        Objects.equals(this.latest, registeredFlowSnapshot.latest) &&
        Objects.equals(this.parameterContexts, registeredFlowSnapshot.parameterContexts) &&
        Objects.equals(this.parameterProviders, registeredFlowSnapshot.parameterProviders) &&
        Objects.equals(this.snapshotMetadata, registeredFlowSnapshot.snapshotMetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bucket, externalControllerServices, flow, flowContents, flowEncodingVersion, latest, parameterContexts, parameterProviders, snapshotMetadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegisteredFlowSnapshot {\n");
    sb.append("    bucket: ").append(toIndentedString(bucket)).append("\n");
    sb.append("    externalControllerServices: ").append(toIndentedString(externalControllerServices)).append("\n");
    sb.append("    flow: ").append(toIndentedString(flow)).append("\n");
    sb.append("    flowContents: ").append(toIndentedString(flowContents)).append("\n");
    sb.append("    flowEncodingVersion: ").append(toIndentedString(flowEncodingVersion)).append("\n");
    sb.append("    latest: ").append(toIndentedString(latest)).append("\n");
    sb.append("    parameterContexts: ").append(toIndentedString(parameterContexts)).append("\n");
    sb.append("    parameterProviders: ").append(toIndentedString(parameterProviders)).append("\n");
    sb.append("    snapshotMetadata: ").append(toIndentedString(snapshotMetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

