/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.tester.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.giwi.nifi.tester.model.StatusHistoryDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StatusHistoryEntity
 */
@JsonPropertyOrder({
  StatusHistoryEntity.JSON_PROPERTY_CAN_READ,
  StatusHistoryEntity.JSON_PROPERTY_STATUS_HISTORY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class StatusHistoryEntity {
  public static final String JSON_PROPERTY_CAN_READ = "canRead";
  @javax.annotation.Nullable
  private Boolean canRead;

  public static final String JSON_PROPERTY_STATUS_HISTORY = "statusHistory";
  @javax.annotation.Nullable
  private StatusHistoryDTO statusHistory;

  public StatusHistoryEntity() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public StatusHistoryEntity(
    @JsonProperty(JSON_PROPERTY_CAN_READ) Boolean canRead
  ) {
    this();
    this.canRead = canRead;
  }

  /**
   * Indicates whether the user can read a given resource.
   * @return canRead
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAN_READ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanRead() {
    return canRead;
  }



  public StatusHistoryEntity statusHistory(@javax.annotation.Nullable StatusHistoryDTO statusHistory) {
    
    this.statusHistory = statusHistory;
    return this;
  }

  /**
   * Get statusHistory
   * @return statusHistory
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS_HISTORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusHistoryDTO getStatusHistory() {
    return statusHistory;
  }


  @JsonProperty(JSON_PROPERTY_STATUS_HISTORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusHistory(@javax.annotation.Nullable StatusHistoryDTO statusHistory) {
    this.statusHistory = statusHistory;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusHistoryEntity statusHistoryEntity = (StatusHistoryEntity) o;
    return Objects.equals(this.canRead, statusHistoryEntity.canRead) &&
        Objects.equals(this.statusHistory, statusHistoryEntity.statusHistory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canRead, statusHistory);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusHistoryEntity {\n");
    sb.append("    canRead: ").append(toIndentedString(canRead)).append("\n");
    sb.append("    statusHistory: ").append(toIndentedString(statusHistory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

