/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.giwi.nifi.client.model.BulletinDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The bulletins for this component.
 */
@JsonPropertyOrder({
  BulletinEntity.JSON_PROPERTY_BULLETIN,
  BulletinEntity.JSON_PROPERTY_CAN_READ,
  BulletinEntity.JSON_PROPERTY_GROUP_ID,
  BulletinEntity.JSON_PROPERTY_ID,
  BulletinEntity.JSON_PROPERTY_NODE_ADDRESS,
  BulletinEntity.JSON_PROPERTY_SOURCE_ID,
  BulletinEntity.JSON_PROPERTY_TIMESTAMP,
  BulletinEntity.JSON_PROPERTY_TIMESTAMP_ISO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class BulletinEntity {
  public static final String JSON_PROPERTY_BULLETIN = "bulletin";
  @javax.annotation.Nullable
  private BulletinDTO bulletin;

  public static final String JSON_PROPERTY_CAN_READ = "canRead";
  @javax.annotation.Nullable
  private Boolean canRead;

  public static final String JSON_PROPERTY_GROUP_ID = "groupId";
  @javax.annotation.Nullable
  private String groupId;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_NODE_ADDRESS = "nodeAddress";
  @javax.annotation.Nullable
  private String nodeAddress;

  public static final String JSON_PROPERTY_SOURCE_ID = "sourceId";
  @javax.annotation.Nullable
  private String sourceId;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nullable
  private String timestamp;

  public static final String JSON_PROPERTY_TIMESTAMP_ISO = "timestampIso";
  @javax.annotation.Nullable
  private String timestampIso;

  public BulletinEntity() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public BulletinEntity(
    @JsonProperty(JSON_PROPERTY_CAN_READ) Boolean canRead
  ) {
    this();
    this.canRead = canRead;
  }

  public BulletinEntity bulletin(@javax.annotation.Nullable BulletinDTO bulletin) {
    
    this.bulletin = bulletin;
    return this;
  }

  /**
   * Get bulletin
   * @return bulletin
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BULLETIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BulletinDTO getBulletin() {
    return bulletin;
  }


  @JsonProperty(JSON_PROPERTY_BULLETIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBulletin(@javax.annotation.Nullable BulletinDTO bulletin) {
    this.bulletin = bulletin;
  }

  /**
   * Indicates whether the user can read a given resource.
   * @return canRead
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAN_READ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanRead() {
    return canRead;
  }



  public BulletinEntity groupId(@javax.annotation.Nullable String groupId) {
    
    this.groupId = groupId;
    return this;
  }

  /**
   * Get groupId
   * @return groupId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGroupId() {
    return groupId;
  }


  @JsonProperty(JSON_PROPERTY_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupId(@javax.annotation.Nullable String groupId) {
    this.groupId = groupId;
  }

  public BulletinEntity id(@javax.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }

  public BulletinEntity nodeAddress(@javax.annotation.Nullable String nodeAddress) {
    
    this.nodeAddress = nodeAddress;
    return this;
  }

  /**
   * Get nodeAddress
   * @return nodeAddress
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NODE_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNodeAddress() {
    return nodeAddress;
  }


  @JsonProperty(JSON_PROPERTY_NODE_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNodeAddress(@javax.annotation.Nullable String nodeAddress) {
    this.nodeAddress = nodeAddress;
  }

  public BulletinEntity sourceId(@javax.annotation.Nullable String sourceId) {
    
    this.sourceId = sourceId;
    return this;
  }

  /**
   * Get sourceId
   * @return sourceId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceId() {
    return sourceId;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceId(@javax.annotation.Nullable String sourceId) {
    this.sourceId = sourceId;
  }

  public BulletinEntity timestamp(@javax.annotation.Nullable String timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

  /**
   * When this bulletin was generated.
   * @return timestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@javax.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
  }

  public BulletinEntity timestampIso(@javax.annotation.Nullable String timestampIso) {
    
    this.timestampIso = timestampIso;
    return this;
  }

  /**
   * When this bulletin was generated in ISO format with full date and milliseconds.
   * @return timestampIso
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMESTAMP_ISO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimestampIso() {
    return timestampIso;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP_ISO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestampIso(@javax.annotation.Nullable String timestampIso) {
    this.timestampIso = timestampIso;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulletinEntity bulletinEntity = (BulletinEntity) o;
    return Objects.equals(this.bulletin, bulletinEntity.bulletin) &&
        Objects.equals(this.canRead, bulletinEntity.canRead) &&
        Objects.equals(this.groupId, bulletinEntity.groupId) &&
        Objects.equals(this.id, bulletinEntity.id) &&
        Objects.equals(this.nodeAddress, bulletinEntity.nodeAddress) &&
        Objects.equals(this.sourceId, bulletinEntity.sourceId) &&
        Objects.equals(this.timestamp, bulletinEntity.timestamp) &&
        Objects.equals(this.timestampIso, bulletinEntity.timestampIso);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bulletin, canRead, groupId, id, nodeAddress, sourceId, timestamp, timestampIso);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulletinEntity {\n");
    sb.append("    bulletin: ").append(toIndentedString(bulletin)).append("\n");
    sb.append("    canRead: ").append(toIndentedString(canRead)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nodeAddress: ").append(toIndentedString(nodeAddress)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    timestampIso: ").append(toIndentedString(timestampIso)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

