/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.giwi.nifi.client.model.NodeDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ClusterDTO
 */
@JsonPropertyOrder({
  ClusterDTO.JSON_PROPERTY_GENERATED,
  ClusterDTO.JSON_PROPERTY_NODES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ClusterDTO {
  public static final String JSON_PROPERTY_GENERATED = "generated";
  @javax.annotation.Nullable
  private String generated;

  public static final String JSON_PROPERTY_NODES = "nodes";
  @javax.annotation.Nullable
  private List<NodeDTO> nodes = new ArrayList<>();

  public ClusterDTO() {
  }

  public ClusterDTO generated(@javax.annotation.Nullable String generated) {
    
    this.generated = generated;
    return this;
  }

  /**
   * The timestamp the report was generated.
   * @return generated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GENERATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGenerated() {
    return generated;
  }


  @JsonProperty(JSON_PROPERTY_GENERATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGenerated(@javax.annotation.Nullable String generated) {
    this.generated = generated;
  }

  public ClusterDTO nodes(@javax.annotation.Nullable List<NodeDTO> nodes) {
    
    this.nodes = nodes;
    return this;
  }

  public ClusterDTO addNodesItem(NodeDTO nodesItem) {
    if (this.nodes == null) {
      this.nodes = new ArrayList<>();
    }
    this.nodes.add(nodesItem);
    return this;
  }

  /**
   * The collection of nodes that are part of the cluster.
   * @return nodes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NodeDTO> getNodes() {
    return nodes;
  }


  @JsonProperty(JSON_PROPERTY_NODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNodes(@javax.annotation.Nullable List<NodeDTO> nodes) {
    this.nodes = nodes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterDTO clusterDTO = (ClusterDTO) o;
    return Objects.equals(this.generated, clusterDTO.generated) &&
        Objects.equals(this.nodes, clusterDTO.nodes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(generated, nodes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterDTO {\n");
    sb.append("    generated: ").append(toIndentedString(generated)).append("\n");
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

