/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import org.giwi.nifi.client.model.PropertyHistoryDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ComponentHistoryDTO
 */
@JsonPropertyOrder({
  ComponentHistoryDTO.JSON_PROPERTY_COMPONENT_ID,
  ComponentHistoryDTO.JSON_PROPERTY_PROPERTY_HISTORY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ComponentHistoryDTO {
  public static final String JSON_PROPERTY_COMPONENT_ID = "componentId";
  @javax.annotation.Nullable
  private String componentId;

  public static final String JSON_PROPERTY_PROPERTY_HISTORY = "propertyHistory";
  @javax.annotation.Nullable
  private Map<String, PropertyHistoryDTO> propertyHistory = new HashMap<>();

  public ComponentHistoryDTO() {
  }

  public ComponentHistoryDTO componentId(@javax.annotation.Nullable String componentId) {
    
    this.componentId = componentId;
    return this;
  }

  /**
   * The component id.
   * @return componentId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPONENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComponentId() {
    return componentId;
  }


  @JsonProperty(JSON_PROPERTY_COMPONENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComponentId(@javax.annotation.Nullable String componentId) {
    this.componentId = componentId;
  }

  public ComponentHistoryDTO propertyHistory(@javax.annotation.Nullable Map<String, PropertyHistoryDTO> propertyHistory) {
    
    this.propertyHistory = propertyHistory;
    return this;
  }

  public ComponentHistoryDTO putPropertyHistoryItem(String key, PropertyHistoryDTO propertyHistoryItem) {
    if (this.propertyHistory == null) {
      this.propertyHistory = new HashMap<>();
    }
    this.propertyHistory.put(key, propertyHistoryItem);
    return this;
  }

  /**
   * The history for the properties of the component.
   * @return propertyHistory
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTY_HISTORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, PropertyHistoryDTO> getPropertyHistory() {
    return propertyHistory;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTY_HISTORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPropertyHistory(@javax.annotation.Nullable Map<String, PropertyHistoryDTO> propertyHistory) {
    this.propertyHistory = propertyHistory;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComponentHistoryDTO componentHistoryDTO = (ComponentHistoryDTO) o;
    return Objects.equals(this.componentId, componentHistoryDTO.componentId) &&
        Objects.equals(this.propertyHistory, componentHistoryDTO.propertyHistory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(componentId, propertyHistory);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComponentHistoryDTO {\n");
    sb.append("    componentId: ").append(toIndentedString(componentId)).append("\n");
    sb.append("    propertyHistory: ").append(toIndentedString(propertyHistory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

