/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The Results of the verification
 */
@JsonPropertyOrder({
  ConfigVerificationResultDTO.JSON_PROPERTY_EXPLANATION,
  ConfigVerificationResultDTO.JSON_PROPERTY_OUTCOME,
  ConfigVerificationResultDTO.JSON_PROPERTY_SUBJECT,
  ConfigVerificationResultDTO.JSON_PROPERTY_VERIFICATION_STEP_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ConfigVerificationResultDTO {
  public static final String JSON_PROPERTY_EXPLANATION = "explanation";
  @javax.annotation.Nullable
  private String explanation;

  /**
   * The outcome of the verification
   */
  public enum OutcomeEnum {
    SUCCESSFUL(String.valueOf("SUCCESSFUL")),
    
    FAILED(String.valueOf("FAILED")),
    
    SKIPPED(String.valueOf("SKIPPED"));

    private String value;

    OutcomeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OutcomeEnum fromValue(String value) {
      for (OutcomeEnum b : OutcomeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OUTCOME = "outcome";
  @javax.annotation.Nullable
  private OutcomeEnum outcome;

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @javax.annotation.Nullable
  private String subject;

  public static final String JSON_PROPERTY_VERIFICATION_STEP_NAME = "verificationStepName";
  @javax.annotation.Nullable
  private String verificationStepName;

  public ConfigVerificationResultDTO() {
  }

  public ConfigVerificationResultDTO explanation(@javax.annotation.Nullable String explanation) {
    
    this.explanation = explanation;
    return this;
  }

  /**
   * An explanation of why the step was or was not successful
   * @return explanation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPLANATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExplanation() {
    return explanation;
  }


  @JsonProperty(JSON_PROPERTY_EXPLANATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExplanation(@javax.annotation.Nullable String explanation) {
    this.explanation = explanation;
  }

  public ConfigVerificationResultDTO outcome(@javax.annotation.Nullable OutcomeEnum outcome) {
    
    this.outcome = outcome;
    return this;
  }

  /**
   * The outcome of the verification
   * @return outcome
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OUTCOME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OutcomeEnum getOutcome() {
    return outcome;
  }


  @JsonProperty(JSON_PROPERTY_OUTCOME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutcome(@javax.annotation.Nullable OutcomeEnum outcome) {
    this.outcome = outcome;
  }

  public ConfigVerificationResultDTO subject(@javax.annotation.Nullable String subject) {
    
    this.subject = subject;
    return this;
  }

  /**
   * The subject of the verification step
   * @return subject
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubject() {
    return subject;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubject(@javax.annotation.Nullable String subject) {
    this.subject = subject;
  }

  public ConfigVerificationResultDTO verificationStepName(@javax.annotation.Nullable String verificationStepName) {
    
    this.verificationStepName = verificationStepName;
    return this;
  }

  /**
   * The name of the verification step
   * @return verificationStepName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERIFICATION_STEP_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVerificationStepName() {
    return verificationStepName;
  }


  @JsonProperty(JSON_PROPERTY_VERIFICATION_STEP_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVerificationStepName(@javax.annotation.Nullable String verificationStepName) {
    this.verificationStepName = verificationStepName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigVerificationResultDTO configVerificationResultDTO = (ConfigVerificationResultDTO) o;
    return Objects.equals(this.explanation, configVerificationResultDTO.explanation) &&
        Objects.equals(this.outcome, configVerificationResultDTO.outcome) &&
        Objects.equals(this.subject, configVerificationResultDTO.subject) &&
        Objects.equals(this.verificationStepName, configVerificationResultDTO.verificationStepName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(explanation, outcome, subject, verificationStepName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigVerificationResultDTO {\n");
    sb.append("    explanation: ").append(toIndentedString(explanation)).append("\n");
    sb.append("    outcome: ").append(toIndentedString(outcome)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    verificationStepName: ").append(toIndentedString(verificationStepName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

