/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.giwi.nifi.client.model.BulletinEntity;
import org.giwi.nifi.client.model.ConnectorDTO;
import org.giwi.nifi.client.model.ConnectorStatusDTO;
import org.giwi.nifi.client.model.PermissionsDTO;
import org.giwi.nifi.client.model.PositionDTO;
import org.giwi.nifi.client.model.RevisionDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConnectorEntity
 */
@JsonPropertyOrder({
  ConnectorEntity.JSON_PROPERTY_BULLETINS,
  ConnectorEntity.JSON_PROPERTY_COMPONENT,
  ConnectorEntity.JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED,
  ConnectorEntity.JSON_PROPERTY_ID,
  ConnectorEntity.JSON_PROPERTY_OPERATE_PERMISSIONS,
  ConnectorEntity.JSON_PROPERTY_PERMISSIONS,
  ConnectorEntity.JSON_PROPERTY_POSITION,
  ConnectorEntity.JSON_PROPERTY_REVISION,
  ConnectorEntity.JSON_PROPERTY_STATUS,
  ConnectorEntity.JSON_PROPERTY_URI
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ConnectorEntity {
  public static final String JSON_PROPERTY_BULLETINS = "bulletins";
  @javax.annotation.Nullable
  private List<BulletinEntity> bulletins = new ArrayList<>();

  public static final String JSON_PROPERTY_COMPONENT = "component";
  @javax.annotation.Nullable
  private ConnectorDTO component;

  public static final String JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED = "disconnectedNodeAcknowledged";
  @javax.annotation.Nullable
  private Boolean disconnectedNodeAcknowledged;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_OPERATE_PERMISSIONS = "operatePermissions";
  @javax.annotation.Nullable
  private PermissionsDTO operatePermissions;

  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  @javax.annotation.Nullable
  private PermissionsDTO permissions;

  public static final String JSON_PROPERTY_POSITION = "position";
  @javax.annotation.Nullable
  private PositionDTO position;

  public static final String JSON_PROPERTY_REVISION = "revision";
  @javax.annotation.Nullable
  private RevisionDTO revision;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private ConnectorStatusDTO status;

  public static final String JSON_PROPERTY_URI = "uri";
  @javax.annotation.Nullable
  private String uri;

  public ConnectorEntity() {
  }

  public ConnectorEntity bulletins(@javax.annotation.Nullable List<BulletinEntity> bulletins) {
    
    this.bulletins = bulletins;
    return this;
  }

  public ConnectorEntity addBulletinsItem(BulletinEntity bulletinsItem) {
    if (this.bulletins == null) {
      this.bulletins = new ArrayList<>();
    }
    this.bulletins.add(bulletinsItem);
    return this;
  }

  /**
   * The bulletins for this component.
   * @return bulletins
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BULLETINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BulletinEntity> getBulletins() {
    return bulletins;
  }


  @JsonProperty(JSON_PROPERTY_BULLETINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBulletins(@javax.annotation.Nullable List<BulletinEntity> bulletins) {
    this.bulletins = bulletins;
  }

  public ConnectorEntity component(@javax.annotation.Nullable ConnectorDTO component) {
    
    this.component = component;
    return this;
  }

  /**
   * Get component
   * @return component
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPONENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConnectorDTO getComponent() {
    return component;
  }


  @JsonProperty(JSON_PROPERTY_COMPONENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComponent(@javax.annotation.Nullable ConnectorDTO component) {
    this.component = component;
  }

  public ConnectorEntity disconnectedNodeAcknowledged(@javax.annotation.Nullable Boolean disconnectedNodeAcknowledged) {
    
    this.disconnectedNodeAcknowledged = disconnectedNodeAcknowledged;
    return this;
  }

  /**
   * Acknowledges that this node is disconnected to allow for mutable requests to proceed.
   * @return disconnectedNodeAcknowledged
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisconnectedNodeAcknowledged() {
    return disconnectedNodeAcknowledged;
  }


  @JsonProperty(JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisconnectedNodeAcknowledged(@javax.annotation.Nullable Boolean disconnectedNodeAcknowledged) {
    this.disconnectedNodeAcknowledged = disconnectedNodeAcknowledged;
  }

  public ConnectorEntity id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * The id of the component.
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public ConnectorEntity operatePermissions(@javax.annotation.Nullable PermissionsDTO operatePermissions) {
    
    this.operatePermissions = operatePermissions;
    return this;
  }

  /**
   * Get operatePermissions
   * @return operatePermissions
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPERATE_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PermissionsDTO getOperatePermissions() {
    return operatePermissions;
  }


  @JsonProperty(JSON_PROPERTY_OPERATE_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperatePermissions(@javax.annotation.Nullable PermissionsDTO operatePermissions) {
    this.operatePermissions = operatePermissions;
  }

  public ConnectorEntity permissions(@javax.annotation.Nullable PermissionsDTO permissions) {
    
    this.permissions = permissions;
    return this;
  }

  /**
   * Get permissions
   * @return permissions
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PermissionsDTO getPermissions() {
    return permissions;
  }


  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermissions(@javax.annotation.Nullable PermissionsDTO permissions) {
    this.permissions = permissions;
  }

  public ConnectorEntity position(@javax.annotation.Nullable PositionDTO position) {
    
    this.position = position;
    return this;
  }

  /**
   * Get position
   * @return position
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PositionDTO getPosition() {
    return position;
  }


  @JsonProperty(JSON_PROPERTY_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPosition(@javax.annotation.Nullable PositionDTO position) {
    this.position = position;
  }

  public ConnectorEntity revision(@javax.annotation.Nullable RevisionDTO revision) {
    
    this.revision = revision;
    return this;
  }

  /**
   * Get revision
   * @return revision
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RevisionDTO getRevision() {
    return revision;
  }


  @JsonProperty(JSON_PROPERTY_REVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRevision(@javax.annotation.Nullable RevisionDTO revision) {
    this.revision = revision;
  }

  public ConnectorEntity status(@javax.annotation.Nullable ConnectorStatusDTO status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConnectorStatusDTO getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable ConnectorStatusDTO status) {
    this.status = status;
  }

  public ConnectorEntity uri(@javax.annotation.Nullable String uri) {
    
    this.uri = uri;
    return this;
  }

  /**
   * The URI for futures requests to the component.
   * @return uri
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUri() {
    return uri;
  }


  @JsonProperty(JSON_PROPERTY_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUri(@javax.annotation.Nullable String uri) {
    this.uri = uri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectorEntity connectorEntity = (ConnectorEntity) o;
    return Objects.equals(this.bulletins, connectorEntity.bulletins) &&
        Objects.equals(this.component, connectorEntity.component) &&
        Objects.equals(this.disconnectedNodeAcknowledged, connectorEntity.disconnectedNodeAcknowledged) &&
        Objects.equals(this.id, connectorEntity.id) &&
        Objects.equals(this.operatePermissions, connectorEntity.operatePermissions) &&
        Objects.equals(this.permissions, connectorEntity.permissions) &&
        Objects.equals(this.position, connectorEntity.position) &&
        Objects.equals(this.revision, connectorEntity.revision) &&
        Objects.equals(this.status, connectorEntity.status) &&
        Objects.equals(this.uri, connectorEntity.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bulletins, component, disconnectedNodeAcknowledged, id, operatePermissions, permissions, position, revision, status, uri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectorEntity {\n");
    sb.append("    bulletins: ").append(toIndentedString(bulletins)).append("\n");
    sb.append("    component: ").append(toIndentedString(component)).append("\n");
    sb.append("    disconnectedNodeAcknowledged: ").append(toIndentedString(disconnectedNodeAcknowledged)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    operatePermissions: ").append(toIndentedString(operatePermissions)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

