/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.giwi.nifi.client.model.ControllerStatusDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ControllerStatusEntity
 */
@JsonPropertyOrder({
  ControllerStatusEntity.JSON_PROPERTY_CONTROLLER_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ControllerStatusEntity {
  public static final String JSON_PROPERTY_CONTROLLER_STATUS = "controllerStatus";
  @javax.annotation.Nullable
  private ControllerStatusDTO controllerStatus;

  public ControllerStatusEntity() {
  }

  public ControllerStatusEntity controllerStatus(@javax.annotation.Nullable ControllerStatusDTO controllerStatus) {
    
    this.controllerStatus = controllerStatus;
    return this;
  }

  /**
   * Get controllerStatus
   * @return controllerStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTROLLER_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ControllerStatusDTO getControllerStatus() {
    return controllerStatus;
  }


  @JsonProperty(JSON_PROPERTY_CONTROLLER_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setControllerStatus(@javax.annotation.Nullable ControllerStatusDTO controllerStatus) {
    this.controllerStatus = controllerStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ControllerStatusEntity controllerStatusEntity = (ControllerStatusEntity) o;
    return Objects.equals(this.controllerStatus, controllerStatusEntity.controllerStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(controllerStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ControllerStatusEntity {\n");
    sb.append("    controllerStatus: ").append(toIndentedString(controllerStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

