/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.giwi.nifi.client.model.CountersDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CountersEntity
 */
@JsonPropertyOrder({
  CountersEntity.JSON_PROPERTY_COUNTERS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class CountersEntity {
  public static final String JSON_PROPERTY_COUNTERS = "counters";
  @javax.annotation.Nullable
  private CountersDTO counters;

  public CountersEntity() {
  }

  public CountersEntity counters(@javax.annotation.Nullable CountersDTO counters) {
    
    this.counters = counters;
    return this;
  }

  /**
   * Get counters
   * @return counters
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CountersDTO getCounters() {
    return counters;
  }


  @JsonProperty(JSON_PROPERTY_COUNTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCounters(@javax.annotation.Nullable CountersDTO counters) {
    this.counters = counters;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CountersEntity countersEntity = (CountersEntity) o;
    return Objects.equals(this.counters, countersEntity.counters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(counters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CountersEntity {\n");
    sb.append("    counters: ").append(toIndentedString(counters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

