/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.giwi.nifi.client.model.CountersSnapshotDTO;
import org.giwi.nifi.client.model.NodeCountersSnapshotDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CountersDTO
 */
@JsonPropertyOrder({
  CountersDTO.JSON_PROPERTY_AGGREGATE_SNAPSHOT,
  CountersDTO.JSON_PROPERTY_NODE_SNAPSHOTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class CountersDTO {
  public static final String JSON_PROPERTY_AGGREGATE_SNAPSHOT = "aggregateSnapshot";
  @javax.annotation.Nullable
  private CountersSnapshotDTO aggregateSnapshot;

  public static final String JSON_PROPERTY_NODE_SNAPSHOTS = "nodeSnapshots";
  @javax.annotation.Nullable
  private List<NodeCountersSnapshotDTO> nodeSnapshots = new ArrayList<>();

  public CountersDTO() {
  }

  public CountersDTO aggregateSnapshot(@javax.annotation.Nullable CountersSnapshotDTO aggregateSnapshot) {
    
    this.aggregateSnapshot = aggregateSnapshot;
    return this;
  }

  /**
   * Get aggregateSnapshot
   * @return aggregateSnapshot
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AGGREGATE_SNAPSHOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CountersSnapshotDTO getAggregateSnapshot() {
    return aggregateSnapshot;
  }


  @JsonProperty(JSON_PROPERTY_AGGREGATE_SNAPSHOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAggregateSnapshot(@javax.annotation.Nullable CountersSnapshotDTO aggregateSnapshot) {
    this.aggregateSnapshot = aggregateSnapshot;
  }

  public CountersDTO nodeSnapshots(@javax.annotation.Nullable List<NodeCountersSnapshotDTO> nodeSnapshots) {
    
    this.nodeSnapshots = nodeSnapshots;
    return this;
  }

  public CountersDTO addNodeSnapshotsItem(NodeCountersSnapshotDTO nodeSnapshotsItem) {
    if (this.nodeSnapshots == null) {
      this.nodeSnapshots = new ArrayList<>();
    }
    this.nodeSnapshots.add(nodeSnapshotsItem);
    return this;
  }

  /**
   * A Counters snapshot for each node in the cluster. If the NiFi instance is a standalone instance, rather than a cluster, this may be null.
   * @return nodeSnapshots
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NODE_SNAPSHOTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NodeCountersSnapshotDTO> getNodeSnapshots() {
    return nodeSnapshots;
  }


  @JsonProperty(JSON_PROPERTY_NODE_SNAPSHOTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNodeSnapshots(@javax.annotation.Nullable List<NodeCountersSnapshotDTO> nodeSnapshots) {
    this.nodeSnapshots = nodeSnapshots;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CountersDTO countersDTO = (CountersDTO) o;
    return Objects.equals(this.aggregateSnapshot, countersDTO.aggregateSnapshot) &&
        Objects.equals(this.nodeSnapshots, countersDTO.nodeSnapshots);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aggregateSnapshot, nodeSnapshots);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CountersDTO {\n");
    sb.append("    aggregateSnapshot: ").append(toIndentedString(aggregateSnapshot)).append("\n");
    sb.append("    nodeSnapshots: ").append(toIndentedString(nodeSnapshots)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

