/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Describes the dynamic properties supported by this component
 */
@JsonPropertyOrder({
  DynamicProperty.JSON_PROPERTY_DESCRIPTION,
  DynamicProperty.JSON_PROPERTY_EXPRESSION_LANGUAGE_SCOPE,
  DynamicProperty.JSON_PROPERTY_NAME,
  DynamicProperty.JSON_PROPERTY_VALUE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class DynamicProperty {
  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  /**
   * The scope of the expression language support
   */
  public enum ExpressionLanguageScopeEnum {
    NONE(String.valueOf("NONE")),
    
    ENVIRONMENT(String.valueOf("ENVIRONMENT")),
    
    FLOWFILE_ATTRIBUTES(String.valueOf("FLOWFILE_ATTRIBUTES"));

    private String value;

    ExpressionLanguageScopeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ExpressionLanguageScopeEnum fromValue(String value) {
      for (ExpressionLanguageScopeEnum b : ExpressionLanguageScopeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_EXPRESSION_LANGUAGE_SCOPE = "expressionLanguageScope";
  @javax.annotation.Nullable
  private ExpressionLanguageScopeEnum expressionLanguageScope;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_VALUE = "value";
  @javax.annotation.Nullable
  private String value;

  public DynamicProperty() {
  }

  public DynamicProperty description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * The description of the dynamic property
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public DynamicProperty expressionLanguageScope(@javax.annotation.Nullable ExpressionLanguageScopeEnum expressionLanguageScope) {
    
    this.expressionLanguageScope = expressionLanguageScope;
    return this;
  }

  /**
   * The scope of the expression language support
   * @return expressionLanguageScope
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPRESSION_LANGUAGE_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ExpressionLanguageScopeEnum getExpressionLanguageScope() {
    return expressionLanguageScope;
  }


  @JsonProperty(JSON_PROPERTY_EXPRESSION_LANGUAGE_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpressionLanguageScope(@javax.annotation.Nullable ExpressionLanguageScopeEnum expressionLanguageScope) {
    this.expressionLanguageScope = expressionLanguageScope;
  }

  public DynamicProperty name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The description of the dynamic property name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public DynamicProperty value(@javax.annotation.Nullable String value) {
    
    this.value = value;
    return this;
  }

  /**
   * The description of the dynamic property value
   * @return value
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(@javax.annotation.Nullable String value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DynamicProperty dynamicProperty = (DynamicProperty) o;
    return Objects.equals(this.description, dynamicProperty.description) &&
        Objects.equals(this.expressionLanguageScope, dynamicProperty.expressionLanguageScope) &&
        Objects.equals(this.name, dynamicProperty.name) &&
        Objects.equals(this.value, dynamicProperty.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, expressionLanguageScope, name, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DynamicProperty {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    expressionLanguageScope: ").append(toIndentedString(expressionLanguageScope)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

