/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.giwi.nifi.client.model.NarSummaryEntity;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * NarSummariesEntity
 */
@JsonPropertyOrder({
  NarSummariesEntity.JSON_PROPERTY_CURRENT_TIME,
  NarSummariesEntity.JSON_PROPERTY_NAR_SUMMARIES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class NarSummariesEntity {
  public static final String JSON_PROPERTY_CURRENT_TIME = "currentTime";
  @javax.annotation.Nullable
  private String currentTime;

  public static final String JSON_PROPERTY_NAR_SUMMARIES = "narSummaries";
  @javax.annotation.Nullable
  private List<NarSummaryEntity> narSummaries = new ArrayList<>();

  public NarSummariesEntity() {
  }

  public NarSummariesEntity currentTime(@javax.annotation.Nullable String currentTime) {
    
    this.currentTime = currentTime;
    return this;
  }

  /**
   * The current time on the system.
   * @return currentTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrentTime() {
    return currentTime;
  }


  @JsonProperty(JSON_PROPERTY_CURRENT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrentTime(@javax.annotation.Nullable String currentTime) {
    this.currentTime = currentTime;
  }

  public NarSummariesEntity narSummaries(@javax.annotation.Nullable List<NarSummaryEntity> narSummaries) {
    
    this.narSummaries = narSummaries;
    return this;
  }

  public NarSummariesEntity addNarSummariesItem(NarSummaryEntity narSummariesItem) {
    if (this.narSummaries == null) {
      this.narSummaries = new ArrayList<>();
    }
    this.narSummaries.add(narSummariesItem);
    return this;
  }

  /**
   * The NAR summaries
   * @return narSummaries
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAR_SUMMARIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NarSummaryEntity> getNarSummaries() {
    return narSummaries;
  }


  @JsonProperty(JSON_PROPERTY_NAR_SUMMARIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNarSummaries(@javax.annotation.Nullable List<NarSummaryEntity> narSummaries) {
    this.narSummaries = narSummaries;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NarSummariesEntity narSummariesEntity = (NarSummariesEntity) o;
    return Objects.equals(this.currentTime, narSummariesEntity.currentTime) &&
        Objects.equals(this.narSummaries, narSummariesEntity.narSummaries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentTime, narSummaries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NarSummariesEntity {\n");
    sb.append("    currentTime: ").append(toIndentedString(currentTime)).append("\n");
    sb.append("    narSummaries: ").append(toIndentedString(narSummaries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

