/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.giwi.nifi.client.model.NodeEventDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * NodeDTO
 */
@JsonPropertyOrder({
  NodeDTO.JSON_PROPERTY_ACTIVE_THREAD_COUNT,
  NodeDTO.JSON_PROPERTY_ADDRESS,
  NodeDTO.JSON_PROPERTY_API_PORT,
  NodeDTO.JSON_PROPERTY_BYTES_QUEUED,
  NodeDTO.JSON_PROPERTY_CONNECTION_REQUESTED,
  NodeDTO.JSON_PROPERTY_EVENTS,
  NodeDTO.JSON_PROPERTY_FLOW_FILE_BYTES,
  NodeDTO.JSON_PROPERTY_FLOW_FILES_QUEUED,
  NodeDTO.JSON_PROPERTY_HEARTBEAT,
  NodeDTO.JSON_PROPERTY_NODE_ID,
  NodeDTO.JSON_PROPERTY_NODE_START_TIME,
  NodeDTO.JSON_PROPERTY_QUEUED,
  NodeDTO.JSON_PROPERTY_ROLES,
  NodeDTO.JSON_PROPERTY_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class NodeDTO {
  public static final String JSON_PROPERTY_ACTIVE_THREAD_COUNT = "activeThreadCount";
  @javax.annotation.Nullable
  private Integer activeThreadCount;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @javax.annotation.Nullable
  private String address;

  public static final String JSON_PROPERTY_API_PORT = "apiPort";
  @javax.annotation.Nullable
  private Integer apiPort;

  public static final String JSON_PROPERTY_BYTES_QUEUED = "bytesQueued";
  @javax.annotation.Nullable
  private Long bytesQueued;

  public static final String JSON_PROPERTY_CONNECTION_REQUESTED = "connectionRequested";
  @javax.annotation.Nullable
  private String connectionRequested;

  public static final String JSON_PROPERTY_EVENTS = "events";
  @javax.annotation.Nullable
  private List<NodeEventDTO> events = new ArrayList<>();

  public static final String JSON_PROPERTY_FLOW_FILE_BYTES = "flowFileBytes";
  @javax.annotation.Nullable
  private Long flowFileBytes;

  public static final String JSON_PROPERTY_FLOW_FILES_QUEUED = "flowFilesQueued";
  @javax.annotation.Nullable
  private Integer flowFilesQueued;

  public static final String JSON_PROPERTY_HEARTBEAT = "heartbeat";
  @javax.annotation.Nullable
  private String heartbeat;

  public static final String JSON_PROPERTY_NODE_ID = "nodeId";
  @javax.annotation.Nullable
  private String nodeId;

  public static final String JSON_PROPERTY_NODE_START_TIME = "nodeStartTime";
  @javax.annotation.Nullable
  private String nodeStartTime;

  public static final String JSON_PROPERTY_QUEUED = "queued";
  @javax.annotation.Nullable
  private String queued;

  public static final String JSON_PROPERTY_ROLES = "roles";
  @javax.annotation.Nullable
  private Set<String> roles = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public NodeDTO() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public NodeDTO(
    @JsonProperty(JSON_PROPERTY_ACTIVE_THREAD_COUNT) Integer activeThreadCount, 
    @JsonProperty(JSON_PROPERTY_ADDRESS) String address, 
    @JsonProperty(JSON_PROPERTY_API_PORT) Integer apiPort, 
    @JsonProperty(JSON_PROPERTY_BYTES_QUEUED) Long bytesQueued, 
    @JsonProperty(JSON_PROPERTY_CONNECTION_REQUESTED) String connectionRequested, 
    @JsonProperty(JSON_PROPERTY_EVENTS) List<NodeEventDTO> events, 
    @JsonProperty(JSON_PROPERTY_FLOW_FILES_QUEUED) Integer flowFilesQueued, 
    @JsonProperty(JSON_PROPERTY_HEARTBEAT) String heartbeat, 
    @JsonProperty(JSON_PROPERTY_NODE_ID) String nodeId, 
    @JsonProperty(JSON_PROPERTY_NODE_START_TIME) String nodeStartTime, 
    @JsonProperty(JSON_PROPERTY_QUEUED) String queued, 
    @JsonProperty(JSON_PROPERTY_ROLES) Set<String> roles
  ) {
    this();
    this.activeThreadCount = activeThreadCount;
    this.address = address;
    this.apiPort = apiPort;
    this.bytesQueued = bytesQueued;
    this.connectionRequested = connectionRequested;
    this.events = events;
    this.flowFilesQueued = flowFilesQueued;
    this.heartbeat = heartbeat;
    this.nodeId = nodeId;
    this.nodeStartTime = nodeStartTime;
    this.queued = queued;
    this.roles = roles;
  }

  /**
   * The active threads for the NiFi on the node.
   * @return activeThreadCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTIVE_THREAD_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getActiveThreadCount() {
    return activeThreadCount;
  }



  /**
   * The node&#39;s host/ip address.
   * @return address
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress() {
    return address;
  }



  /**
   * The port the node is listening for API requests.
   * @return apiPort
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getApiPort() {
    return apiPort;
  }



  /**
   * The total size of all FlowFiles that are queued up on the node
   * @return bytesQueued
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BYTES_QUEUED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getBytesQueued() {
    return bytesQueued;
  }



  /**
   * The time of the node&#39;s last connection request.
   * @return connectionRequested
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONNECTION_REQUESTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConnectionRequested() {
    return connectionRequested;
  }



  /**
   * The node&#39;s events.
   * @return events
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NodeEventDTO> getEvents() {
    return events;
  }



  public NodeDTO flowFileBytes(@javax.annotation.Nullable Long flowFileBytes) {
    
    this.flowFileBytes = flowFileBytes;
    return this;
  }

  /**
   * Get flowFileBytes
   * @return flowFileBytes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLOW_FILE_BYTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getFlowFileBytes() {
    return flowFileBytes;
  }


  @JsonProperty(JSON_PROPERTY_FLOW_FILE_BYTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowFileBytes(@javax.annotation.Nullable Long flowFileBytes) {
    this.flowFileBytes = flowFileBytes;
  }

  /**
   * The number of FlowFiles that are queued up on the node
   * @return flowFilesQueued
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLOW_FILES_QUEUED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFlowFilesQueued() {
    return flowFilesQueued;
  }



  /**
   * the time of the nodes&#39;s last heartbeat.
   * @return heartbeat
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HEARTBEAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHeartbeat() {
    return heartbeat;
  }



  /**
   * The id of the node.
   * @return nodeId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NODE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNodeId() {
    return nodeId;
  }



  /**
   * The time at which this Node was last refreshed.
   * @return nodeStartTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NODE_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNodeStartTime() {
    return nodeStartTime;
  }



  /**
   * The queue the NiFi on the node.
   * @return queued
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUEUED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQueued() {
    return queued;
  }



  /**
   * The roles of this node.
   * @return roles
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<String> getRoles() {
    return roles;
  }



  public NodeDTO status(@javax.annotation.Nullable String status) {
    
    this.status = status;
    return this;
  }

  /**
   * The node&#39;s status.
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeDTO nodeDTO = (NodeDTO) o;
    return Objects.equals(this.activeThreadCount, nodeDTO.activeThreadCount) &&
        Objects.equals(this.address, nodeDTO.address) &&
        Objects.equals(this.apiPort, nodeDTO.apiPort) &&
        Objects.equals(this.bytesQueued, nodeDTO.bytesQueued) &&
        Objects.equals(this.connectionRequested, nodeDTO.connectionRequested) &&
        Objects.equals(this.events, nodeDTO.events) &&
        Objects.equals(this.flowFileBytes, nodeDTO.flowFileBytes) &&
        Objects.equals(this.flowFilesQueued, nodeDTO.flowFilesQueued) &&
        Objects.equals(this.heartbeat, nodeDTO.heartbeat) &&
        Objects.equals(this.nodeId, nodeDTO.nodeId) &&
        Objects.equals(this.nodeStartTime, nodeDTO.nodeStartTime) &&
        Objects.equals(this.queued, nodeDTO.queued) &&
        Objects.equals(this.roles, nodeDTO.roles) &&
        Objects.equals(this.status, nodeDTO.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeThreadCount, address, apiPort, bytesQueued, connectionRequested, events, flowFileBytes, flowFilesQueued, heartbeat, nodeId, nodeStartTime, queued, roles, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeDTO {\n");
    sb.append("    activeThreadCount: ").append(toIndentedString(activeThreadCount)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    apiPort: ").append(toIndentedString(apiPort)).append("\n");
    sb.append("    bytesQueued: ").append(toIndentedString(bytesQueued)).append("\n");
    sb.append("    connectionRequested: ").append(toIndentedString(connectionRequested)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    flowFileBytes: ").append(toIndentedString(flowFileBytes)).append("\n");
    sb.append("    flowFilesQueued: ").append(toIndentedString(flowFilesQueued)).append("\n");
    sb.append("    heartbeat: ").append(toIndentedString(heartbeat)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    nodeStartTime: ").append(toIndentedString(nodeStartTime)).append("\n");
    sb.append("    queued: ").append(toIndentedString(queued)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

