/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.giwi.nifi.client.model.ParameterProviderConfigurationDTO;
import org.giwi.nifi.client.model.PermissionsDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Optional configuration for a Parameter Provider
 */
@JsonPropertyOrder({
  ParameterProviderConfigurationEntity.JSON_PROPERTY_COMPONENT,
  ParameterProviderConfigurationEntity.JSON_PROPERTY_ID,
  ParameterProviderConfigurationEntity.JSON_PROPERTY_PERMISSIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ParameterProviderConfigurationEntity {
  public static final String JSON_PROPERTY_COMPONENT = "component";
  @javax.annotation.Nullable
  private ParameterProviderConfigurationDTO component;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  @javax.annotation.Nullable
  private PermissionsDTO permissions;

  public ParameterProviderConfigurationEntity() {
  }

  public ParameterProviderConfigurationEntity component(@javax.annotation.Nullable ParameterProviderConfigurationDTO component) {
    
    this.component = component;
    return this;
  }

  /**
   * Get component
   * @return component
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPONENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ParameterProviderConfigurationDTO getComponent() {
    return component;
  }


  @JsonProperty(JSON_PROPERTY_COMPONENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComponent(@javax.annotation.Nullable ParameterProviderConfigurationDTO component) {
    this.component = component;
  }

  public ParameterProviderConfigurationEntity id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * The id of the component.
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public ParameterProviderConfigurationEntity permissions(@javax.annotation.Nullable PermissionsDTO permissions) {
    
    this.permissions = permissions;
    return this;
  }

  /**
   * Get permissions
   * @return permissions
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PermissionsDTO getPermissions() {
    return permissions;
  }


  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermissions(@javax.annotation.Nullable PermissionsDTO permissions) {
    this.permissions = permissions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParameterProviderConfigurationEntity parameterProviderConfigurationEntity = (ParameterProviderConfigurationEntity) o;
    return Objects.equals(this.component, parameterProviderConfigurationEntity.component) &&
        Objects.equals(this.id, parameterProviderConfigurationEntity.id) &&
        Objects.equals(this.permissions, parameterProviderConfigurationEntity.permissions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(component, id, permissions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParameterProviderConfigurationEntity {\n");
    sb.append("    component: ").append(toIndentedString(component)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

