/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.LinkedHashSet;
import java.util.Set;
import org.giwi.nifi.client.model.DocumentedTypeDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProcessorTypesEntity
 */
@JsonPropertyOrder({
  ProcessorTypesEntity.JSON_PROPERTY_PROCESSOR_TYPES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ProcessorTypesEntity {
  public static final String JSON_PROPERTY_PROCESSOR_TYPES = "processorTypes";
  @javax.annotation.Nullable
  private Set<DocumentedTypeDTO> processorTypes = new LinkedHashSet<>();

  public ProcessorTypesEntity() {
  }

  public ProcessorTypesEntity processorTypes(@javax.annotation.Nullable Set<DocumentedTypeDTO> processorTypes) {
    
    this.processorTypes = processorTypes;
    return this;
  }

  public ProcessorTypesEntity addProcessorTypesItem(DocumentedTypeDTO processorTypesItem) {
    if (this.processorTypes == null) {
      this.processorTypes = new LinkedHashSet<>();
    }
    this.processorTypes.add(processorTypesItem);
    return this;
  }

  /**
   * Get processorTypes
   * @return processorTypes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCESSOR_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<DocumentedTypeDTO> getProcessorTypes() {
    return processorTypes;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_PROCESSOR_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessorTypes(@javax.annotation.Nullable Set<DocumentedTypeDTO> processorTypes) {
    this.processorTypes = processorTypes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessorTypesEntity processorTypesEntity = (ProcessorTypesEntity) o;
    return Objects.equals(this.processorTypes, processorTypesEntity.processorTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(processorTypes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessorTypesEntity {\n");
    sb.append("    processorTypes: ").append(toIndentedString(processorTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

