/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A list of dependencies that must be met in order for this Property to be relevant. If any of these dependencies is not met, the property described by this Property Descriptor is not relevant.
 */
@JsonPropertyOrder({
  PropertyDependencyDTO.JSON_PROPERTY_DEPENDENT_VALUES,
  PropertyDependencyDTO.JSON_PROPERTY_PROPERTY_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class PropertyDependencyDTO {
  public static final String JSON_PROPERTY_DEPENDENT_VALUES = "dependentValues";
  @javax.annotation.Nullable
  private Set<String> dependentValues = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_PROPERTY_NAME = "propertyName";
  @javax.annotation.Nullable
  private String propertyName;

  public PropertyDependencyDTO() {
  }

  public PropertyDependencyDTO dependentValues(@javax.annotation.Nullable Set<String> dependentValues) {
    
    this.dependentValues = dependentValues;
    return this;
  }

  public PropertyDependencyDTO addDependentValuesItem(String dependentValuesItem) {
    if (this.dependentValues == null) {
      this.dependentValues = new LinkedHashSet<>();
    }
    this.dependentValues.add(dependentValuesItem);
    return this;
  }

  /**
   * The values for the property that satisfies the dependency, or null if the dependency is satisfied by the presence of any value for the associated property name
   * @return dependentValues
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEPENDENT_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<String> getDependentValues() {
    return dependentValues;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_DEPENDENT_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDependentValues(@javax.annotation.Nullable Set<String> dependentValues) {
    this.dependentValues = dependentValues;
  }

  public PropertyDependencyDTO propertyName(@javax.annotation.Nullable String propertyName) {
    
    this.propertyName = propertyName;
    return this;
  }

  /**
   * The name of the property that is being depended upon
   * @return propertyName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPropertyName() {
    return propertyName;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPropertyName(@javax.annotation.Nullable String propertyName) {
    this.propertyName = propertyName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PropertyDependencyDTO propertyDependencyDTO = (PropertyDependencyDTO) o;
    return Objects.equals(this.dependentValues, propertyDependencyDTO.dependentValues) &&
        Objects.equals(this.propertyName, propertyDependencyDTO.propertyName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dependentValues, propertyName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PropertyDependencyDTO {\n");
    sb.append("    dependentValues: ").append(toIndentedString(dependentValues)).append("\n");
    sb.append("    propertyName: ").append(toIndentedString(propertyName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

