/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.giwi.nifi.client.model.DefinedType;
import org.giwi.nifi.client.model.PropertyAllowableValue;
import org.giwi.nifi.client.model.PropertyDependency;
import org.giwi.nifi.client.model.PropertyListenPortDefinition;
import org.giwi.nifi.client.model.PropertyResourceDefinition;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Descriptions of configuration properties applicable to this component.
 */
@JsonPropertyOrder({
  PropertyDescriptor.JSON_PROPERTY_ALLOWABLE_VALUES,
  PropertyDescriptor.JSON_PROPERTY_DEFAULT_VALUE,
  PropertyDescriptor.JSON_PROPERTY_DEPENDENCIES,
  PropertyDescriptor.JSON_PROPERTY_DESCRIPTION,
  PropertyDescriptor.JSON_PROPERTY_DISPLAY_NAME,
  PropertyDescriptor.JSON_PROPERTY_DYNAMIC,
  PropertyDescriptor.JSON_PROPERTY_EXPRESSION_LANGUAGE_SCOPE,
  PropertyDescriptor.JSON_PROPERTY_EXPRESSION_LANGUAGE_SCOPE_DESCRIPTION,
  PropertyDescriptor.JSON_PROPERTY_LISTEN_PORT_DEFINITION,
  PropertyDescriptor.JSON_PROPERTY_NAME,
  PropertyDescriptor.JSON_PROPERTY_REQUIRED,
  PropertyDescriptor.JSON_PROPERTY_RESOURCE_DEFINITION,
  PropertyDescriptor.JSON_PROPERTY_SENSITIVE,
  PropertyDescriptor.JSON_PROPERTY_TYPE_PROVIDED_BY_VALUE,
  PropertyDescriptor.JSON_PROPERTY_VALID_REGEX,
  PropertyDescriptor.JSON_PROPERTY_VALIDATOR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class PropertyDescriptor {
  public static final String JSON_PROPERTY_ALLOWABLE_VALUES = "allowableValues";
  @javax.annotation.Nullable
  private List<PropertyAllowableValue> allowableValues = new ArrayList<>();

  public static final String JSON_PROPERTY_DEFAULT_VALUE = "defaultValue";
  @javax.annotation.Nullable
  private String defaultValue;

  public static final String JSON_PROPERTY_DEPENDENCIES = "dependencies";
  @javax.annotation.Nullable
  private List<PropertyDependency> dependencies = new ArrayList<>();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  @javax.annotation.Nullable
  private String displayName;

  public static final String JSON_PROPERTY_DYNAMIC = "dynamic";
  @javax.annotation.Nullable
  private Boolean dynamic;

  /**
   * The scope of expression language supported by this property
   */
  public enum ExpressionLanguageScopeEnum {
    NONE(String.valueOf("NONE")),
    
    ENVIRONMENT(String.valueOf("ENVIRONMENT")),
    
    FLOWFILE_ATTRIBUTES(String.valueOf("FLOWFILE_ATTRIBUTES"));

    private String value;

    ExpressionLanguageScopeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ExpressionLanguageScopeEnum fromValue(String value) {
      for (ExpressionLanguageScopeEnum b : ExpressionLanguageScopeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_EXPRESSION_LANGUAGE_SCOPE = "expressionLanguageScope";
  @javax.annotation.Nullable
  private ExpressionLanguageScopeEnum expressionLanguageScope;

  public static final String JSON_PROPERTY_EXPRESSION_LANGUAGE_SCOPE_DESCRIPTION = "expressionLanguageScopeDescription";
  @javax.annotation.Nullable
  private String expressionLanguageScopeDescription;

  public static final String JSON_PROPERTY_LISTEN_PORT_DEFINITION = "listenPortDefinition";
  @javax.annotation.Nullable
  private PropertyListenPortDefinition listenPortDefinition;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_REQUIRED = "required";
  @javax.annotation.Nullable
  private Boolean required;

  public static final String JSON_PROPERTY_RESOURCE_DEFINITION = "resourceDefinition";
  @javax.annotation.Nullable
  private PropertyResourceDefinition resourceDefinition;

  public static final String JSON_PROPERTY_SENSITIVE = "sensitive";
  @javax.annotation.Nullable
  private Boolean sensitive;

  public static final String JSON_PROPERTY_TYPE_PROVIDED_BY_VALUE = "typeProvidedByValue";
  @javax.annotation.Nullable
  private DefinedType typeProvidedByValue;

  public static final String JSON_PROPERTY_VALID_REGEX = "validRegex";
  @javax.annotation.Nullable
  private String validRegex;

  public static final String JSON_PROPERTY_VALIDATOR = "validator";
  @javax.annotation.Nullable
  private String validator;

  public PropertyDescriptor() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public PropertyDescriptor(
    @JsonProperty(JSON_PROPERTY_EXPRESSION_LANGUAGE_SCOPE_DESCRIPTION) String expressionLanguageScopeDescription
  ) {
    this();
    this.expressionLanguageScopeDescription = expressionLanguageScopeDescription;
  }

  public PropertyDescriptor allowableValues(@javax.annotation.Nullable List<PropertyAllowableValue> allowableValues) {
    
    this.allowableValues = allowableValues;
    return this;
  }

  public PropertyDescriptor addAllowableValuesItem(PropertyAllowableValue allowableValuesItem) {
    if (this.allowableValues == null) {
      this.allowableValues = new ArrayList<>();
    }
    this.allowableValues.add(allowableValuesItem);
    return this;
  }

  /**
   * A list of the allowable values for the property
   * @return allowableValues
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALLOWABLE_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PropertyAllowableValue> getAllowableValues() {
    return allowableValues;
  }


  @JsonProperty(JSON_PROPERTY_ALLOWABLE_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowableValues(@javax.annotation.Nullable List<PropertyAllowableValue> allowableValues) {
    this.allowableValues = allowableValues;
  }

  public PropertyDescriptor defaultValue(@javax.annotation.Nullable String defaultValue) {
    
    this.defaultValue = defaultValue;
    return this;
  }

  /**
   * The default value if a user-set value is not specified
   * @return defaultValue
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEFAULT_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefaultValue() {
    return defaultValue;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultValue(@javax.annotation.Nullable String defaultValue) {
    this.defaultValue = defaultValue;
  }

  public PropertyDescriptor dependencies(@javax.annotation.Nullable List<PropertyDependency> dependencies) {
    
    this.dependencies = dependencies;
    return this;
  }

  public PropertyDescriptor addDependenciesItem(PropertyDependency dependenciesItem) {
    if (this.dependencies == null) {
      this.dependencies = new ArrayList<>();
    }
    this.dependencies.add(dependenciesItem);
    return this;
  }

  /**
   * The dependencies that this property has on other properties
   * @return dependencies
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEPENDENCIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PropertyDependency> getDependencies() {
    return dependencies;
  }


  @JsonProperty(JSON_PROPERTY_DEPENDENCIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDependencies(@javax.annotation.Nullable List<PropertyDependency> dependencies) {
    this.dependencies = dependencies;
  }

  public PropertyDescriptor description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * The description of what the property does
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public PropertyDescriptor displayName(@javax.annotation.Nullable String displayName) {
    
    this.displayName = displayName;
    return this;
  }

  /**
   * The display name of the property key, if different from the name
   * @return displayName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayName(@javax.annotation.Nullable String displayName) {
    this.displayName = displayName;
  }

  public PropertyDescriptor dynamic(@javax.annotation.Nullable Boolean dynamic) {
    
    this.dynamic = dynamic;
    return this;
  }

  /**
   * Whether or not the descriptor is for a dynamically added property
   * @return dynamic
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DYNAMIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDynamic() {
    return dynamic;
  }


  @JsonProperty(JSON_PROPERTY_DYNAMIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDynamic(@javax.annotation.Nullable Boolean dynamic) {
    this.dynamic = dynamic;
  }

  public PropertyDescriptor expressionLanguageScope(@javax.annotation.Nullable ExpressionLanguageScopeEnum expressionLanguageScope) {
    
    this.expressionLanguageScope = expressionLanguageScope;
    return this;
  }

  /**
   * The scope of expression language supported by this property
   * @return expressionLanguageScope
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPRESSION_LANGUAGE_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ExpressionLanguageScopeEnum getExpressionLanguageScope() {
    return expressionLanguageScope;
  }


  @JsonProperty(JSON_PROPERTY_EXPRESSION_LANGUAGE_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpressionLanguageScope(@javax.annotation.Nullable ExpressionLanguageScopeEnum expressionLanguageScope) {
    this.expressionLanguageScope = expressionLanguageScope;
  }

  /**
   * The description of the expression language scope supported by this property
   * @return expressionLanguageScopeDescription
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPRESSION_LANGUAGE_SCOPE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExpressionLanguageScopeDescription() {
    return expressionLanguageScopeDescription;
  }



  public PropertyDescriptor listenPortDefinition(@javax.annotation.Nullable PropertyListenPortDefinition listenPortDefinition) {
    
    this.listenPortDefinition = listenPortDefinition;
    return this;
  }

  /**
   * Get listenPortDefinition
   * @return listenPortDefinition
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LISTEN_PORT_DEFINITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PropertyListenPortDefinition getListenPortDefinition() {
    return listenPortDefinition;
  }


  @JsonProperty(JSON_PROPERTY_LISTEN_PORT_DEFINITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setListenPortDefinition(@javax.annotation.Nullable PropertyListenPortDefinition listenPortDefinition) {
    this.listenPortDefinition = listenPortDefinition;
  }

  public PropertyDescriptor name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of the property key
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public PropertyDescriptor required(@javax.annotation.Nullable Boolean required) {
    
    this.required = required;
    return this;
  }

  /**
   * Whether or not  the property is required for the component
   * @return required
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRequired() {
    return required;
  }


  @JsonProperty(JSON_PROPERTY_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequired(@javax.annotation.Nullable Boolean required) {
    this.required = required;
  }

  public PropertyDescriptor resourceDefinition(@javax.annotation.Nullable PropertyResourceDefinition resourceDefinition) {
    
    this.resourceDefinition = resourceDefinition;
    return this;
  }

  /**
   * Get resourceDefinition
   * @return resourceDefinition
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESOURCE_DEFINITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PropertyResourceDefinition getResourceDefinition() {
    return resourceDefinition;
  }


  @JsonProperty(JSON_PROPERTY_RESOURCE_DEFINITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResourceDefinition(@javax.annotation.Nullable PropertyResourceDefinition resourceDefinition) {
    this.resourceDefinition = resourceDefinition;
  }

  public PropertyDescriptor sensitive(@javax.annotation.Nullable Boolean sensitive) {
    
    this.sensitive = sensitive;
    return this;
  }

  /**
   * Whether or not  the value of the property is considered sensitive (e.g., passwords and keys)
   * @return sensitive
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SENSITIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSensitive() {
    return sensitive;
  }


  @JsonProperty(JSON_PROPERTY_SENSITIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSensitive(@javax.annotation.Nullable Boolean sensitive) {
    this.sensitive = sensitive;
  }

  public PropertyDescriptor typeProvidedByValue(@javax.annotation.Nullable DefinedType typeProvidedByValue) {
    
    this.typeProvidedByValue = typeProvidedByValue;
    return this;
  }

  /**
   * Get typeProvidedByValue
   * @return typeProvidedByValue
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE_PROVIDED_BY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DefinedType getTypeProvidedByValue() {
    return typeProvidedByValue;
  }


  @JsonProperty(JSON_PROPERTY_TYPE_PROVIDED_BY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTypeProvidedByValue(@javax.annotation.Nullable DefinedType typeProvidedByValue) {
    this.typeProvidedByValue = typeProvidedByValue;
  }

  public PropertyDescriptor validRegex(@javax.annotation.Nullable String validRegex) {
    
    this.validRegex = validRegex;
    return this;
  }

  /**
   * A regular expression that can be used to validate the value of this property
   * @return validRegex
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALID_REGEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValidRegex() {
    return validRegex;
  }


  @JsonProperty(JSON_PROPERTY_VALID_REGEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidRegex(@javax.annotation.Nullable String validRegex) {
    this.validRegex = validRegex;
  }

  public PropertyDescriptor validator(@javax.annotation.Nullable String validator) {
    
    this.validator = validator;
    return this;
  }

  /**
   * Name of the validator used for this property descriptor
   * @return validator
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALIDATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValidator() {
    return validator;
  }


  @JsonProperty(JSON_PROPERTY_VALIDATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidator(@javax.annotation.Nullable String validator) {
    this.validator = validator;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PropertyDescriptor propertyDescriptor = (PropertyDescriptor) o;
    return Objects.equals(this.allowableValues, propertyDescriptor.allowableValues) &&
        Objects.equals(this.defaultValue, propertyDescriptor.defaultValue) &&
        Objects.equals(this.dependencies, propertyDescriptor.dependencies) &&
        Objects.equals(this.description, propertyDescriptor.description) &&
        Objects.equals(this.displayName, propertyDescriptor.displayName) &&
        Objects.equals(this.dynamic, propertyDescriptor.dynamic) &&
        Objects.equals(this.expressionLanguageScope, propertyDescriptor.expressionLanguageScope) &&
        Objects.equals(this.expressionLanguageScopeDescription, propertyDescriptor.expressionLanguageScopeDescription) &&
        Objects.equals(this.listenPortDefinition, propertyDescriptor.listenPortDefinition) &&
        Objects.equals(this.name, propertyDescriptor.name) &&
        Objects.equals(this.required, propertyDescriptor.required) &&
        Objects.equals(this.resourceDefinition, propertyDescriptor.resourceDefinition) &&
        Objects.equals(this.sensitive, propertyDescriptor.sensitive) &&
        Objects.equals(this.typeProvidedByValue, propertyDescriptor.typeProvidedByValue) &&
        Objects.equals(this.validRegex, propertyDescriptor.validRegex) &&
        Objects.equals(this.validator, propertyDescriptor.validator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowableValues, defaultValue, dependencies, description, displayName, dynamic, expressionLanguageScope, expressionLanguageScopeDescription, listenPortDefinition, name, required, resourceDefinition, sensitive, typeProvidedByValue, validRegex, validator);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PropertyDescriptor {\n");
    sb.append("    allowableValues: ").append(toIndentedString(allowableValues)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    dependencies: ").append(toIndentedString(dependencies)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    dynamic: ").append(toIndentedString(dynamic)).append("\n");
    sb.append("    expressionLanguageScope: ").append(toIndentedString(expressionLanguageScope)).append("\n");
    sb.append("    expressionLanguageScopeDescription: ").append(toIndentedString(expressionLanguageScopeDescription)).append("\n");
    sb.append("    listenPortDefinition: ").append(toIndentedString(listenPortDefinition)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    resourceDefinition: ").append(toIndentedString(resourceDefinition)).append("\n");
    sb.append("    sensitive: ").append(toIndentedString(sensitive)).append("\n");
    sb.append("    typeProvidedByValue: ").append(toIndentedString(typeProvidedByValue)).append("\n");
    sb.append("    validRegex: ").append(toIndentedString(validRegex)).append("\n");
    sb.append("    validator: ").append(toIndentedString(validator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

