/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The links between the nodes in the lineage.
 */
@JsonPropertyOrder({
  ProvenanceLinkDTO.JSON_PROPERTY_FLOW_FILE_UUID,
  ProvenanceLinkDTO.JSON_PROPERTY_MILLIS,
  ProvenanceLinkDTO.JSON_PROPERTY_SOURCE_ID,
  ProvenanceLinkDTO.JSON_PROPERTY_TARGET_ID,
  ProvenanceLinkDTO.JSON_PROPERTY_TIMESTAMP
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ProvenanceLinkDTO {
  public static final String JSON_PROPERTY_FLOW_FILE_UUID = "flowFileUuid";
  @javax.annotation.Nullable
  private String flowFileUuid;

  public static final String JSON_PROPERTY_MILLIS = "millis";
  @javax.annotation.Nullable
  private Long millis;

  public static final String JSON_PROPERTY_SOURCE_ID = "sourceId";
  @javax.annotation.Nullable
  private String sourceId;

  public static final String JSON_PROPERTY_TARGET_ID = "targetId";
  @javax.annotation.Nullable
  private String targetId;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nullable
  private String timestamp;

  public ProvenanceLinkDTO() {
  }

  public ProvenanceLinkDTO flowFileUuid(@javax.annotation.Nullable String flowFileUuid) {
    
    this.flowFileUuid = flowFileUuid;
    return this;
  }

  /**
   * The flowfile uuid that traversed the link.
   * @return flowFileUuid
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLOW_FILE_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFlowFileUuid() {
    return flowFileUuid;
  }


  @JsonProperty(JSON_PROPERTY_FLOW_FILE_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowFileUuid(@javax.annotation.Nullable String flowFileUuid) {
    this.flowFileUuid = flowFileUuid;
  }

  public ProvenanceLinkDTO millis(@javax.annotation.Nullable Long millis) {
    
    this.millis = millis;
    return this;
  }

  /**
   * The timestamp of this link in milliseconds.
   * @return millis
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MILLIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMillis() {
    return millis;
  }


  @JsonProperty(JSON_PROPERTY_MILLIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMillis(@javax.annotation.Nullable Long millis) {
    this.millis = millis;
  }

  public ProvenanceLinkDTO sourceId(@javax.annotation.Nullable String sourceId) {
    
    this.sourceId = sourceId;
    return this;
  }

  /**
   * The source node id of the link.
   * @return sourceId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceId() {
    return sourceId;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceId(@javax.annotation.Nullable String sourceId) {
    this.sourceId = sourceId;
  }

  public ProvenanceLinkDTO targetId(@javax.annotation.Nullable String targetId) {
    
    this.targetId = targetId;
    return this;
  }

  /**
   * The target node id of the link.
   * @return targetId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TARGET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTargetId() {
    return targetId;
  }


  @JsonProperty(JSON_PROPERTY_TARGET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetId(@javax.annotation.Nullable String targetId) {
    this.targetId = targetId;
  }

  public ProvenanceLinkDTO timestamp(@javax.annotation.Nullable String timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

  /**
   * The timestamp of the link (based on the destination).
   * @return timestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@javax.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProvenanceLinkDTO provenanceLinkDTO = (ProvenanceLinkDTO) o;
    return Objects.equals(this.flowFileUuid, provenanceLinkDTO.flowFileUuid) &&
        Objects.equals(this.millis, provenanceLinkDTO.millis) &&
        Objects.equals(this.sourceId, provenanceLinkDTO.sourceId) &&
        Objects.equals(this.targetId, provenanceLinkDTO.targetId) &&
        Objects.equals(this.timestamp, provenanceLinkDTO.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flowFileUuid, millis, sourceId, targetId, timestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProvenanceLinkDTO {\n");
    sb.append("    flowFileUuid: ").append(toIndentedString(flowFileUuid)).append("\n");
    sb.append("    millis: ").append(toIndentedString(millis)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    targetId: ").append(toIndentedString(targetId)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

