/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The available relationships that the processor currently supports.
 */
@JsonPropertyOrder({
  RelationshipDTO.JSON_PROPERTY_AUTO_TERMINATE,
  RelationshipDTO.JSON_PROPERTY_DESCRIPTION,
  RelationshipDTO.JSON_PROPERTY_NAME,
  RelationshipDTO.JSON_PROPERTY_RETRY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class RelationshipDTO {
  public static final String JSON_PROPERTY_AUTO_TERMINATE = "autoTerminate";
  @javax.annotation.Nullable
  private Boolean autoTerminate;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_RETRY = "retry";
  @javax.annotation.Nullable
  private Boolean retry;

  public RelationshipDTO() {
  }

  public RelationshipDTO autoTerminate(@javax.annotation.Nullable Boolean autoTerminate) {
    
    this.autoTerminate = autoTerminate;
    return this;
  }

  /**
   * Whether or not FlowFiles sent to this relationship should auto terminate.
   * @return autoTerminate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTO_TERMINATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAutoTerminate() {
    return autoTerminate;
  }


  @JsonProperty(JSON_PROPERTY_AUTO_TERMINATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutoTerminate(@javax.annotation.Nullable Boolean autoTerminate) {
    this.autoTerminate = autoTerminate;
  }

  public RelationshipDTO description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * The relationship description.
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public RelationshipDTO name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The relationship name.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public RelationshipDTO retry(@javax.annotation.Nullable Boolean retry) {
    
    this.retry = retry;
    return this;
  }

  /**
   * Whether or not FlowFiles sent to this relationship should retry.
   * @return retry
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RETRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRetry() {
    return retry;
  }


  @JsonProperty(JSON_PROPERTY_RETRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetry(@javax.annotation.Nullable Boolean retry) {
    this.retry = retry;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RelationshipDTO relationshipDTO = (RelationshipDTO) o;
    return Objects.equals(this.autoTerminate, relationshipDTO.autoTerminate) &&
        Objects.equals(this.description, relationshipDTO.description) &&
        Objects.equals(this.name, relationshipDTO.name) &&
        Objects.equals(this.retry, relationshipDTO.retry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoTerminate, description, name, retry);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RelationshipDTO {\n");
    sb.append("    autoTerminate: ").append(toIndentedString(autoTerminate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    retry: ").append(toIndentedString(retry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

