/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.LinkedHashSet;
import java.util.Set;
import org.giwi.nifi.client.model.DocumentedTypeDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ReportingTaskTypesEntity
 */
@JsonPropertyOrder({
  ReportingTaskTypesEntity.JSON_PROPERTY_REPORTING_TASK_TYPES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class ReportingTaskTypesEntity {
  public static final String JSON_PROPERTY_REPORTING_TASK_TYPES = "reportingTaskTypes";
  @javax.annotation.Nullable
  private Set<DocumentedTypeDTO> reportingTaskTypes = new LinkedHashSet<>();

  public ReportingTaskTypesEntity() {
  }

  public ReportingTaskTypesEntity reportingTaskTypes(@javax.annotation.Nullable Set<DocumentedTypeDTO> reportingTaskTypes) {
    
    this.reportingTaskTypes = reportingTaskTypes;
    return this;
  }

  public ReportingTaskTypesEntity addReportingTaskTypesItem(DocumentedTypeDTO reportingTaskTypesItem) {
    if (this.reportingTaskTypes == null) {
      this.reportingTaskTypes = new LinkedHashSet<>();
    }
    this.reportingTaskTypes.add(reportingTaskTypesItem);
    return this;
  }

  /**
   * Get reportingTaskTypes
   * @return reportingTaskTypes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORTING_TASK_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<DocumentedTypeDTO> getReportingTaskTypes() {
    return reportingTaskTypes;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_REPORTING_TASK_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportingTaskTypes(@javax.annotation.Nullable Set<DocumentedTypeDTO> reportingTaskTypes) {
    this.reportingTaskTypes = reportingTaskTypes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportingTaskTypesEntity reportingTaskTypesEntity = (ReportingTaskTypesEntity) o;
    return Objects.equals(this.reportingTaskTypes, reportingTaskTypesEntity.reportingTaskTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reportingTaskTypes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportingTaskTypesEntity {\n");
    sb.append("    reportingTaskTypes: ").append(toIndentedString(reportingTaskTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

