/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.giwi.nifi.client.model.SnippetDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SnippetEntity
 */
@JsonPropertyOrder({
  SnippetEntity.JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED,
  SnippetEntity.JSON_PROPERTY_SNIPPET
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class SnippetEntity {
  public static final String JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED = "disconnectedNodeAcknowledged";
  @javax.annotation.Nullable
  private Boolean disconnectedNodeAcknowledged;

  public static final String JSON_PROPERTY_SNIPPET = "snippet";
  @javax.annotation.Nullable
  private SnippetDTO snippet;

  public SnippetEntity() {
  }

  public SnippetEntity disconnectedNodeAcknowledged(@javax.annotation.Nullable Boolean disconnectedNodeAcknowledged) {
    
    this.disconnectedNodeAcknowledged = disconnectedNodeAcknowledged;
    return this;
  }

  /**
   * Acknowledges that this node is disconnected to allow for mutable requests to proceed.
   * @return disconnectedNodeAcknowledged
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisconnectedNodeAcknowledged() {
    return disconnectedNodeAcknowledged;
  }


  @JsonProperty(JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisconnectedNodeAcknowledged(@javax.annotation.Nullable Boolean disconnectedNodeAcknowledged) {
    this.disconnectedNodeAcknowledged = disconnectedNodeAcknowledged;
  }

  public SnippetEntity snippet(@javax.annotation.Nullable SnippetDTO snippet) {
    
    this.snippet = snippet;
    return this;
  }

  /**
   * Get snippet
   * @return snippet
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SNIPPET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SnippetDTO getSnippet() {
    return snippet;
  }


  @JsonProperty(JSON_PROPERTY_SNIPPET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSnippet(@javax.annotation.Nullable SnippetDTO snippet) {
    this.snippet = snippet;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SnippetEntity snippetEntity = (SnippetEntity) o;
    return Objects.equals(this.disconnectedNodeAcknowledged, snippetEntity.disconnectedNodeAcknowledged) &&
        Objects.equals(this.snippet, snippetEntity.snippet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disconnectedNodeAcknowledged, snippet);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SnippetEntity {\n");
    sb.append("    disconnectedNodeAcknowledged: ").append(toIndentedString(disconnectedNodeAcknowledged)).append("\n");
    sb.append("    snippet: ").append(toIndentedString(snippet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

