/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.giwi.nifi.client.model.StateEntryDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The local state for this component.
 */
@JsonPropertyOrder({
  StateMapDTO.JSON_PROPERTY_SCOPE,
  StateMapDTO.JSON_PROPERTY_STATE,
  StateMapDTO.JSON_PROPERTY_TOTAL_ENTRY_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class StateMapDTO {
  public static final String JSON_PROPERTY_SCOPE = "scope";
  @javax.annotation.Nullable
  private String scope;

  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nullable
  private List<StateEntryDTO> state = new ArrayList<>();

  public static final String JSON_PROPERTY_TOTAL_ENTRY_COUNT = "totalEntryCount";
  @javax.annotation.Nullable
  private Integer totalEntryCount;

  public StateMapDTO() {
  }

  public StateMapDTO scope(@javax.annotation.Nullable String scope) {
    
    this.scope = scope;
    return this;
  }

  /**
   * The scope of this StateMap.
   * @return scope
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getScope() {
    return scope;
  }


  @JsonProperty(JSON_PROPERTY_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScope(@javax.annotation.Nullable String scope) {
    this.scope = scope;
  }

  public StateMapDTO state(@javax.annotation.Nullable List<StateEntryDTO> state) {
    
    this.state = state;
    return this;
  }

  public StateMapDTO addStateItem(StateEntryDTO stateItem) {
    if (this.state == null) {
      this.state = new ArrayList<>();
    }
    this.state.add(stateItem);
    return this;
  }

  /**
   * The state.
   * @return state
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<StateEntryDTO> getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@javax.annotation.Nullable List<StateEntryDTO> state) {
    this.state = state;
  }

  public StateMapDTO totalEntryCount(@javax.annotation.Nullable Integer totalEntryCount) {
    
    this.totalEntryCount = totalEntryCount;
    return this;
  }

  /**
   * The total number of state entries. When the state map is lengthy, only of portion of the entries are returned.
   * @return totalEntryCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_ENTRY_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalEntryCount() {
    return totalEntryCount;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_ENTRY_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalEntryCount(@javax.annotation.Nullable Integer totalEntryCount) {
    this.totalEntryCount = totalEntryCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StateMapDTO stateMapDTO = (StateMapDTO) o;
    return Objects.equals(this.scope, stateMapDTO.scope) &&
        Objects.equals(this.state, stateMapDTO.state) &&
        Objects.equals(this.totalEntryCount, stateMapDTO.totalEntryCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scope, state, totalEntryCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StateMapDTO {\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    totalEntryCount: ").append(toIndentedString(totalEntryCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

