/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.giwi.nifi.client.model.VersionedControllerService;
import org.giwi.nifi.client.model.VersionedReportingTask;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VersionedReportingTaskSnapshot
 */
@JsonPropertyOrder({
  VersionedReportingTaskSnapshot.JSON_PROPERTY_CONTROLLER_SERVICES,
  VersionedReportingTaskSnapshot.JSON_PROPERTY_REPORTING_TASKS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class VersionedReportingTaskSnapshot {
  public static final String JSON_PROPERTY_CONTROLLER_SERVICES = "controllerServices";
  @javax.annotation.Nullable
  private List<VersionedControllerService> controllerServices = new ArrayList<>();

  public static final String JSON_PROPERTY_REPORTING_TASKS = "reportingTasks";
  @javax.annotation.Nullable
  private List<VersionedReportingTask> reportingTasks = new ArrayList<>();

  public VersionedReportingTaskSnapshot() {
  }

  public VersionedReportingTaskSnapshot controllerServices(@javax.annotation.Nullable List<VersionedControllerService> controllerServices) {
    
    this.controllerServices = controllerServices;
    return this;
  }

  public VersionedReportingTaskSnapshot addControllerServicesItem(VersionedControllerService controllerServicesItem) {
    if (this.controllerServices == null) {
      this.controllerServices = new ArrayList<>();
    }
    this.controllerServices.add(controllerServicesItem);
    return this;
  }

  /**
   * The controller services
   * @return controllerServices
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTROLLER_SERVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<VersionedControllerService> getControllerServices() {
    return controllerServices;
  }


  @JsonProperty(JSON_PROPERTY_CONTROLLER_SERVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setControllerServices(@javax.annotation.Nullable List<VersionedControllerService> controllerServices) {
    this.controllerServices = controllerServices;
  }

  public VersionedReportingTaskSnapshot reportingTasks(@javax.annotation.Nullable List<VersionedReportingTask> reportingTasks) {
    
    this.reportingTasks = reportingTasks;
    return this;
  }

  public VersionedReportingTaskSnapshot addReportingTasksItem(VersionedReportingTask reportingTasksItem) {
    if (this.reportingTasks == null) {
      this.reportingTasks = new ArrayList<>();
    }
    this.reportingTasks.add(reportingTasksItem);
    return this;
  }

  /**
   * The reporting tasks
   * @return reportingTasks
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORTING_TASKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<VersionedReportingTask> getReportingTasks() {
    return reportingTasks;
  }


  @JsonProperty(JSON_PROPERTY_REPORTING_TASKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportingTasks(@javax.annotation.Nullable List<VersionedReportingTask> reportingTasks) {
    this.reportingTasks = reportingTasks;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionedReportingTaskSnapshot versionedReportingTaskSnapshot = (VersionedReportingTaskSnapshot) o;
    return Objects.equals(this.controllerServices, versionedReportingTaskSnapshot.controllerServices) &&
        Objects.equals(this.reportingTasks, versionedReportingTaskSnapshot.reportingTasks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(controllerServices, reportingTasks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionedReportingTaskSnapshot {\n");
    sb.append("    controllerServices: ").append(toIndentedString(controllerServices)).append("\n");
    sb.append("    reportingTasks: ").append(toIndentedString(reportingTasks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

