/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.giwi.nifi.client.model.Position;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The Output Ports
 */
@JsonPropertyOrder({
  VersionedPort.JSON_PROPERTY_ALLOW_REMOTE_ACCESS,
  VersionedPort.JSON_PROPERTY_COMMENTS,
  VersionedPort.JSON_PROPERTY_COMPONENT_TYPE,
  VersionedPort.JSON_PROPERTY_CONCURRENTLY_SCHEDULABLE_TASK_COUNT,
  VersionedPort.JSON_PROPERTY_GROUP_IDENTIFIER,
  VersionedPort.JSON_PROPERTY_IDENTIFIER,
  VersionedPort.JSON_PROPERTY_INSTANCE_IDENTIFIER,
  VersionedPort.JSON_PROPERTY_NAME,
  VersionedPort.JSON_PROPERTY_PORT_FUNCTION,
  VersionedPort.JSON_PROPERTY_POSITION,
  VersionedPort.JSON_PROPERTY_SCHEDULED_STATE,
  VersionedPort.JSON_PROPERTY_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class VersionedPort {
  public static final String JSON_PROPERTY_ALLOW_REMOTE_ACCESS = "allowRemoteAccess";
  @javax.annotation.Nullable
  private Boolean allowRemoteAccess;

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  @javax.annotation.Nullable
  private String comments;

  /**
   * Gets or Sets componentType
   */
  public enum ComponentTypeEnum {
    CONNECTION(String.valueOf("CONNECTION")),
    
    PROCESSOR(String.valueOf("PROCESSOR")),
    
    PROCESS_GROUP(String.valueOf("PROCESS_GROUP")),
    
    REMOTE_PROCESS_GROUP(String.valueOf("REMOTE_PROCESS_GROUP")),
    
    INPUT_PORT(String.valueOf("INPUT_PORT")),
    
    OUTPUT_PORT(String.valueOf("OUTPUT_PORT")),
    
    REMOTE_INPUT_PORT(String.valueOf("REMOTE_INPUT_PORT")),
    
    REMOTE_OUTPUT_PORT(String.valueOf("REMOTE_OUTPUT_PORT")),
    
    FUNNEL(String.valueOf("FUNNEL")),
    
    LABEL(String.valueOf("LABEL")),
    
    CONTROLLER_SERVICE(String.valueOf("CONTROLLER_SERVICE")),
    
    REPORTING_TASK(String.valueOf("REPORTING_TASK")),
    
    FLOW_ANALYSIS_RULE(String.valueOf("FLOW_ANALYSIS_RULE")),
    
    PARAMETER_CONTEXT(String.valueOf("PARAMETER_CONTEXT")),
    
    PARAMETER_PROVIDER(String.valueOf("PARAMETER_PROVIDER")),
    
    FLOW_REGISTRY_CLIENT(String.valueOf("FLOW_REGISTRY_CLIENT")),
    
    CONNECTOR(String.valueOf("CONNECTOR"));

    private String value;

    ComponentTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ComponentTypeEnum fromValue(String value) {
      for (ComponentTypeEnum b : ComponentTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_COMPONENT_TYPE = "componentType";
  @javax.annotation.Nullable
  private ComponentTypeEnum componentType;

  public static final String JSON_PROPERTY_CONCURRENTLY_SCHEDULABLE_TASK_COUNT = "concurrentlySchedulableTaskCount";
  @javax.annotation.Nullable
  private Integer concurrentlySchedulableTaskCount;

  public static final String JSON_PROPERTY_GROUP_IDENTIFIER = "groupIdentifier";
  @javax.annotation.Nullable
  private String groupIdentifier;

  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  @javax.annotation.Nullable
  private String identifier;

  public static final String JSON_PROPERTY_INSTANCE_IDENTIFIER = "instanceIdentifier";
  @javax.annotation.Nullable
  private String instanceIdentifier;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  /**
   * Specifies how the Port should function
   */
  public enum PortFunctionEnum {
    STANDARD(String.valueOf("STANDARD")),
    
    FAILURE(String.valueOf("FAILURE"));

    private String value;

    PortFunctionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PortFunctionEnum fromValue(String value) {
      for (PortFunctionEnum b : PortFunctionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PORT_FUNCTION = "portFunction";
  @javax.annotation.Nullable
  private PortFunctionEnum portFunction;

  public static final String JSON_PROPERTY_POSITION = "position";
  @javax.annotation.Nullable
  private Position position;

  /**
   * The scheduled state of the component
   */
  public enum ScheduledStateEnum {
    ENABLED(String.valueOf("ENABLED")),
    
    DISABLED(String.valueOf("DISABLED")),
    
    RUNNING(String.valueOf("RUNNING"));

    private String value;

    ScheduledStateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ScheduledStateEnum fromValue(String value) {
      for (ScheduledStateEnum b : ScheduledStateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SCHEDULED_STATE = "scheduledState";
  @javax.annotation.Nullable
  private ScheduledStateEnum scheduledState;

  /**
   * The type of port.
   */
  public enum TypeEnum {
    INPUT_PORT(String.valueOf("INPUT_PORT")),
    
    OUTPUT_PORT(String.valueOf("OUTPUT_PORT"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nullable
  private TypeEnum type;

  public VersionedPort() {
  }

  public VersionedPort allowRemoteAccess(@javax.annotation.Nullable Boolean allowRemoteAccess) {
    
    this.allowRemoteAccess = allowRemoteAccess;
    return this;
  }

  /**
   * Whether or not this port allows remote access for site-to-site
   * @return allowRemoteAccess
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALLOW_REMOTE_ACCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAllowRemoteAccess() {
    return allowRemoteAccess;
  }


  @JsonProperty(JSON_PROPERTY_ALLOW_REMOTE_ACCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowRemoteAccess(@javax.annotation.Nullable Boolean allowRemoteAccess) {
    this.allowRemoteAccess = allowRemoteAccess;
  }

  public VersionedPort comments(@javax.annotation.Nullable String comments) {
    
    this.comments = comments;
    return this;
  }

  /**
   * The user-supplied comments for the component
   * @return comments
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComments() {
    return comments;
  }


  @JsonProperty(JSON_PROPERTY_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
  }

  public VersionedPort componentType(@javax.annotation.Nullable ComponentTypeEnum componentType) {
    
    this.componentType = componentType;
    return this;
  }

  /**
   * Get componentType
   * @return componentType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPONENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ComponentTypeEnum getComponentType() {
    return componentType;
  }


  @JsonProperty(JSON_PROPERTY_COMPONENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComponentType(@javax.annotation.Nullable ComponentTypeEnum componentType) {
    this.componentType = componentType;
  }

  public VersionedPort concurrentlySchedulableTaskCount(@javax.annotation.Nullable Integer concurrentlySchedulableTaskCount) {
    
    this.concurrentlySchedulableTaskCount = concurrentlySchedulableTaskCount;
    return this;
  }

  /**
   * The number of tasks that should be concurrently scheduled for the port.
   * @return concurrentlySchedulableTaskCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONCURRENTLY_SCHEDULABLE_TASK_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getConcurrentlySchedulableTaskCount() {
    return concurrentlySchedulableTaskCount;
  }


  @JsonProperty(JSON_PROPERTY_CONCURRENTLY_SCHEDULABLE_TASK_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConcurrentlySchedulableTaskCount(@javax.annotation.Nullable Integer concurrentlySchedulableTaskCount) {
    this.concurrentlySchedulableTaskCount = concurrentlySchedulableTaskCount;
  }

  public VersionedPort groupIdentifier(@javax.annotation.Nullable String groupIdentifier) {
    
    this.groupIdentifier = groupIdentifier;
    return this;
  }

  /**
   * The ID of the Process Group that this component belongs to
   * @return groupIdentifier
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGroupIdentifier() {
    return groupIdentifier;
  }


  @JsonProperty(JSON_PROPERTY_GROUP_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupIdentifier(@javax.annotation.Nullable String groupIdentifier) {
    this.groupIdentifier = groupIdentifier;
  }

  public VersionedPort identifier(@javax.annotation.Nullable String identifier) {
    
    this.identifier = identifier;
    return this;
  }

  /**
   * The component&#39;s unique identifier
   * @return identifier
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdentifier() {
    return identifier;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentifier(@javax.annotation.Nullable String identifier) {
    this.identifier = identifier;
  }

  public VersionedPort instanceIdentifier(@javax.annotation.Nullable String instanceIdentifier) {
    
    this.instanceIdentifier = instanceIdentifier;
    return this;
  }

  /**
   * The instance ID of an existing component that is described by this VersionedComponent, or null if this is not mapped to an instantiated component
   * @return instanceIdentifier
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INSTANCE_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInstanceIdentifier() {
    return instanceIdentifier;
  }


  @JsonProperty(JSON_PROPERTY_INSTANCE_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstanceIdentifier(@javax.annotation.Nullable String instanceIdentifier) {
    this.instanceIdentifier = instanceIdentifier;
  }

  public VersionedPort name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The component&#39;s name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public VersionedPort portFunction(@javax.annotation.Nullable PortFunctionEnum portFunction) {
    
    this.portFunction = portFunction;
    return this;
  }

  /**
   * Specifies how the Port should function
   * @return portFunction
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PORT_FUNCTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PortFunctionEnum getPortFunction() {
    return portFunction;
  }


  @JsonProperty(JSON_PROPERTY_PORT_FUNCTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPortFunction(@javax.annotation.Nullable PortFunctionEnum portFunction) {
    this.portFunction = portFunction;
  }

  public VersionedPort position(@javax.annotation.Nullable Position position) {
    
    this.position = position;
    return this;
  }

  /**
   * Get position
   * @return position
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Position getPosition() {
    return position;
  }


  @JsonProperty(JSON_PROPERTY_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPosition(@javax.annotation.Nullable Position position) {
    this.position = position;
  }

  public VersionedPort scheduledState(@javax.annotation.Nullable ScheduledStateEnum scheduledState) {
    
    this.scheduledState = scheduledState;
    return this;
  }

  /**
   * The scheduled state of the component
   * @return scheduledState
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCHEDULED_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ScheduledStateEnum getScheduledState() {
    return scheduledState;
  }


  @JsonProperty(JSON_PROPERTY_SCHEDULED_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScheduledState(@javax.annotation.Nullable ScheduledStateEnum scheduledState) {
    this.scheduledState = scheduledState;
  }

  public VersionedPort type(@javax.annotation.Nullable TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * The type of port.
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@javax.annotation.Nullable TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionedPort versionedPort = (VersionedPort) o;
    return Objects.equals(this.allowRemoteAccess, versionedPort.allowRemoteAccess) &&
        Objects.equals(this.comments, versionedPort.comments) &&
        Objects.equals(this.componentType, versionedPort.componentType) &&
        Objects.equals(this.concurrentlySchedulableTaskCount, versionedPort.concurrentlySchedulableTaskCount) &&
        Objects.equals(this.groupIdentifier, versionedPort.groupIdentifier) &&
        Objects.equals(this.identifier, versionedPort.identifier) &&
        Objects.equals(this.instanceIdentifier, versionedPort.instanceIdentifier) &&
        Objects.equals(this.name, versionedPort.name) &&
        Objects.equals(this.portFunction, versionedPort.portFunction) &&
        Objects.equals(this.position, versionedPort.position) &&
        Objects.equals(this.scheduledState, versionedPort.scheduledState) &&
        Objects.equals(this.type, versionedPort.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowRemoteAccess, comments, componentType, concurrentlySchedulableTaskCount, groupIdentifier, identifier, instanceIdentifier, name, portFunction, position, scheduledState, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionedPort {\n");
    sb.append("    allowRemoteAccess: ").append(toIndentedString(allowRemoteAccess)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    componentType: ").append(toIndentedString(componentType)).append("\n");
    sb.append("    concurrentlySchedulableTaskCount: ").append(toIndentedString(concurrentlySchedulableTaskCount)).append("\n");
    sb.append("    groupIdentifier: ").append(toIndentedString(groupIdentifier)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    instanceIdentifier: ").append(toIndentedString(instanceIdentifier)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    portFunction: ").append(toIndentedString(portFunction)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    scheduledState: ").append(toIndentedString(scheduledState)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

