/*
 * Apache NiFi REST API
 * REST API definition for Apache NiFi web services
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.giwi.nifi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.giwi.nifi.client.model.RegisteredFlowSnapshot;
import org.giwi.nifi.client.model.RevisionDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VersionedFlowSnapshotEntity
 */
@JsonPropertyOrder({
  VersionedFlowSnapshotEntity.JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED,
  VersionedFlowSnapshotEntity.JSON_PROPERTY_PROCESS_GROUP_REVISION,
  VersionedFlowSnapshotEntity.JSON_PROPERTY_REGISTRY_ID,
  VersionedFlowSnapshotEntity.JSON_PROPERTY_UPDATE_DESCENDANT_VERSIONED_FLOWS,
  VersionedFlowSnapshotEntity.JSON_PROPERTY_VERSIONED_FLOW,
  VersionedFlowSnapshotEntity.JSON_PROPERTY_VERSIONED_FLOW_SNAPSHOT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-27T21:33:06.905180638+02:00[Europe/Paris]", comments = "Generator version: 7.14.0")
public class VersionedFlowSnapshotEntity {
  public static final String JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED = "disconnectedNodeAcknowledged";
  @javax.annotation.Nullable
  private Boolean disconnectedNodeAcknowledged;

  public static final String JSON_PROPERTY_PROCESS_GROUP_REVISION = "processGroupRevision";
  @javax.annotation.Nullable
  private RevisionDTO processGroupRevision;

  public static final String JSON_PROPERTY_REGISTRY_ID = "registryId";
  @javax.annotation.Nullable
  private String registryId;

  public static final String JSON_PROPERTY_UPDATE_DESCENDANT_VERSIONED_FLOWS = "updateDescendantVersionedFlows";
  @javax.annotation.Nullable
  private Boolean updateDescendantVersionedFlows;

  public static final String JSON_PROPERTY_VERSIONED_FLOW = "versionedFlow";
  @javax.annotation.Nullable
  private RegisteredFlowSnapshot versionedFlow;

  public static final String JSON_PROPERTY_VERSIONED_FLOW_SNAPSHOT = "versionedFlowSnapshot";
  @javax.annotation.Nullable
  private RegisteredFlowSnapshot versionedFlowSnapshot;

  public VersionedFlowSnapshotEntity() {
  }

  public VersionedFlowSnapshotEntity disconnectedNodeAcknowledged(@javax.annotation.Nullable Boolean disconnectedNodeAcknowledged) {
    
    this.disconnectedNodeAcknowledged = disconnectedNodeAcknowledged;
    return this;
  }

  /**
   * Acknowledges that this node is disconnected to allow for mutable requests to proceed.
   * @return disconnectedNodeAcknowledged
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisconnectedNodeAcknowledged() {
    return disconnectedNodeAcknowledged;
  }


  @JsonProperty(JSON_PROPERTY_DISCONNECTED_NODE_ACKNOWLEDGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisconnectedNodeAcknowledged(@javax.annotation.Nullable Boolean disconnectedNodeAcknowledged) {
    this.disconnectedNodeAcknowledged = disconnectedNodeAcknowledged;
  }

  public VersionedFlowSnapshotEntity processGroupRevision(@javax.annotation.Nullable RevisionDTO processGroupRevision) {
    
    this.processGroupRevision = processGroupRevision;
    return this;
  }

  /**
   * Get processGroupRevision
   * @return processGroupRevision
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCESS_GROUP_REVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RevisionDTO getProcessGroupRevision() {
    return processGroupRevision;
  }


  @JsonProperty(JSON_PROPERTY_PROCESS_GROUP_REVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessGroupRevision(@javax.annotation.Nullable RevisionDTO processGroupRevision) {
    this.processGroupRevision = processGroupRevision;
  }

  public VersionedFlowSnapshotEntity registryId(@javax.annotation.Nullable String registryId) {
    
    this.registryId = registryId;
    return this;
  }

  /**
   * The ID of the Registry that this flow belongs to
   * @return registryId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REGISTRY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRegistryId() {
    return registryId;
  }


  @JsonProperty(JSON_PROPERTY_REGISTRY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegistryId(@javax.annotation.Nullable String registryId) {
    this.registryId = registryId;
  }

  public VersionedFlowSnapshotEntity updateDescendantVersionedFlows(@javax.annotation.Nullable Boolean updateDescendantVersionedFlows) {
    
    this.updateDescendantVersionedFlows = updateDescendantVersionedFlows;
    return this;
  }

  /**
   * If the Process Group to be updated has a child or descendant Process Group that is also under Version Control, this specifies whether or not the contents of that child/descendant Process Group should be updated.
   * @return updateDescendantVersionedFlows
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATE_DESCENDANT_VERSIONED_FLOWS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUpdateDescendantVersionedFlows() {
    return updateDescendantVersionedFlows;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_DESCENDANT_VERSIONED_FLOWS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateDescendantVersionedFlows(@javax.annotation.Nullable Boolean updateDescendantVersionedFlows) {
    this.updateDescendantVersionedFlows = updateDescendantVersionedFlows;
  }

  public VersionedFlowSnapshotEntity versionedFlow(@javax.annotation.Nullable RegisteredFlowSnapshot versionedFlow) {
    
    this.versionedFlow = versionedFlow;
    return this;
  }

  /**
   * Get versionedFlow
   * @return versionedFlow
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSIONED_FLOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RegisteredFlowSnapshot getVersionedFlow() {
    return versionedFlow;
  }


  @JsonProperty(JSON_PROPERTY_VERSIONED_FLOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersionedFlow(@javax.annotation.Nullable RegisteredFlowSnapshot versionedFlow) {
    this.versionedFlow = versionedFlow;
  }

  public VersionedFlowSnapshotEntity versionedFlowSnapshot(@javax.annotation.Nullable RegisteredFlowSnapshot versionedFlowSnapshot) {
    
    this.versionedFlowSnapshot = versionedFlowSnapshot;
    return this;
  }

  /**
   * Get versionedFlowSnapshot
   * @return versionedFlowSnapshot
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSIONED_FLOW_SNAPSHOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RegisteredFlowSnapshot getVersionedFlowSnapshot() {
    return versionedFlowSnapshot;
  }


  @JsonProperty(JSON_PROPERTY_VERSIONED_FLOW_SNAPSHOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersionedFlowSnapshot(@javax.annotation.Nullable RegisteredFlowSnapshot versionedFlowSnapshot) {
    this.versionedFlowSnapshot = versionedFlowSnapshot;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionedFlowSnapshotEntity versionedFlowSnapshotEntity = (VersionedFlowSnapshotEntity) o;
    return Objects.equals(this.disconnectedNodeAcknowledged, versionedFlowSnapshotEntity.disconnectedNodeAcknowledged) &&
        Objects.equals(this.processGroupRevision, versionedFlowSnapshotEntity.processGroupRevision) &&
        Objects.equals(this.registryId, versionedFlowSnapshotEntity.registryId) &&
        Objects.equals(this.updateDescendantVersionedFlows, versionedFlowSnapshotEntity.updateDescendantVersionedFlows) &&
        Objects.equals(this.versionedFlow, versionedFlowSnapshotEntity.versionedFlow) &&
        Objects.equals(this.versionedFlowSnapshot, versionedFlowSnapshotEntity.versionedFlowSnapshot);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disconnectedNodeAcknowledged, processGroupRevision, registryId, updateDescendantVersionedFlows, versionedFlow, versionedFlowSnapshot);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionedFlowSnapshotEntity {\n");
    sb.append("    disconnectedNodeAcknowledged: ").append(toIndentedString(disconnectedNodeAcknowledged)).append("\n");
    sb.append("    processGroupRevision: ").append(toIndentedString(processGroupRevision)).append("\n");
    sb.append("    registryId: ").append(toIndentedString(registryId)).append("\n");
    sb.append("    updateDescendantVersionedFlows: ").append(toIndentedString(updateDescendantVersionedFlows)).append("\n");
    sb.append("    versionedFlow: ").append(toIndentedString(versionedFlow)).append("\n");
    sb.append("    versionedFlowSnapshot: ").append(toIndentedString(versionedFlowSnapshot)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

